/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "activity_feature.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL function 'startActivity' ******/
static const FeatureType system_internal_activity_startActivity_parameters[] = {
    FT_STRING,
    FT_ANY_REF,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_startActivity_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_startActivity) },
    .parameters = system_internal_activity_startActivity_parameters,
    .return_type = FT_INT,
};


/****** for JIDL function 'stopActivity' ******/
static const FeatureType system_internal_activity_stopActivity_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_stopActivity_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_stopActivity) },
    .parameters = system_internal_activity_stopActivity_parameters,
    .return_type = FT_INT,
};


/****** for JIDL function 'startService' ******/
static const FeatureType system_internal_activity_startService_parameters[] = {
    FT_STRING,
    FT_ANY_REF,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_startService_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_startService) },
    .parameters = system_internal_activity_startService_parameters,
    .return_type = FT_INT,
};


/****** for JIDL function 'stopService' ******/
static const FeatureType system_internal_activity_stopService_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_stopService_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_stopService) },
    .parameters = system_internal_activity_stopService_parameters,
    .return_type = FT_INT,
};


/****** for JIDL callback 'onConnected_cb' ******/
static const FeatureType system_internal_activity_onConnected_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_internal_activity_onConnected_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_internal_activity_onConnected_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'onDisconnected_cb' ******/
static const FeatureType system_internal_activity_onDisconnected_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_internal_activity_onDisconnected_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_internal_activity_onDisconnected_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'ServiceConnection' ******/
static ObjectMember system_internal_activity_ServiceConnection_struct_members[] = {
    { "connectCallBack", FT_MK_COMPLEX(&system_internal_activity_onConnected_cb_callback_type), offsetof(system_internal_activity_ServiceConnection, _connectCallBack), sizeof(FtCallbackId) },
    { "disconnectCallBack", FT_MK_COMPLEX(&system_internal_activity_onDisconnected_cb_callback_type), offsetof(system_internal_activity_ServiceConnection, _disconnectCallBack), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_internal_activity_ServiceConnection_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_internal_activity_ServiceConnection) },
    .members = system_internal_activity_ServiceConnection_struct_members
};

system_internal_activity_ServiceConnection* system_internal_activityMallocServiceConnection () {
    return (system_internal_activity_ServiceConnection*)FeatureMalloc(
        sizeof(system_internal_activity_ServiceConnection), FT_MK_COMPLEX(&system_internal_activity_ServiceConnection_struct_type));
}


/****** for JIDL function 'bindService' ******/
static const FeatureType system_internal_activity_bindService_parameters[] = {
    FT_STRING,
    FT_ANY_REF,
    FT_MK_COMPLEX_REF(&system_internal_activity_ServiceConnection_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_bindService_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_bindService) },
    .parameters = system_internal_activity_bindService_parameters,
    .return_type = FT_INT,
};


/****** for JIDL function 'unbindService' ******/
static const FeatureType system_internal_activity_unbindService_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_unbindService_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_unbindService) },
    .parameters = system_internal_activity_unbindService_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'moveToBackground' ******/
static const FeatureType system_internal_activity_moveToBackground_parameters[] = {
    FT_BOOLEAN,
    FT_PARAM_END
};

static const MemberMethod system_internal_activity_moveToBackground_member_method = {
    .func = { .callback = FFI_FN(system_internal_activity_wrap_moveToBackground) },
    .parameters = system_internal_activity_moveToBackground_parameters,
    .return_type = FT_BOOLEAN,
};


// members
static const Member system_internal_activity_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "startActivity",
        .method = system_internal_activity_startActivity_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "stopActivity",
        .method = system_internal_activity_stopActivity_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "startService",
        .method = system_internal_activity_startService_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "stopService",
        .method = system_internal_activity_stopService_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "bindService",
        .method = system_internal_activity_bindService_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "unbindService",
        .method = system_internal_activity_unbindService_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "moveToBackground",
        .method = system_internal_activity_moveToBackground_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_internal_activity_callbacks {
    system_internal_activity_onRegister,
    system_internal_activity_onCreate,
    system_internal_activity_onRequired,
    system_internal_activity_onDetached,
    system_internal_activity_onDestroy,
    system_internal_activity_onUnregister
};

static const FeatureDescription system_internal_activity_desc = {
    .version = 1,
    .name = "system.internal.activity",
    .description = "system.internal.activity",
    { .dynamic = false },
    .native_callbacks = &system_internal_activity_callbacks,
    .member_count = countof(system_internal_activity_members),
    .members = system_internal_activity_members,
};

QAPPFEATURE_INIT(system_internal_activity)
{
    return mgr->registerFeature(features, &system_internal_activity_desc);
}
/* clang-format on */
