/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef _CRYPTO_UTILS_H_
#define _CRYPTO_UTILS_H_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef enum Cipher_ErrorCode {
    GOOD = 0,
    GENERAL = 200,
    ARGSERROR = 202,
    UNSUPPORTED = 203,
    TIMEOUT = 204,
    IOERROR = 300
} Cipher_ErrorCode;

#define arrayof(array) sizeof(array) / sizeof(array[0])

#define INVOKE_SUCCESS_CB_INTERFACE(cb, ...) \
    do { \
        if (!FeatureInvokeCallback(handle, cb, ##__VA_ARGS__)) { \
            FEATURE_LOG_ERROR("invoke success callback failed !"); \
        } \
    } while (0)

#define INVOKE_FAIL_CB_INTERFACE(cb, msg, code) \
    do { \
        ft_value_t ret_data = ft_from_string(ft_ctx, msg); \
        if (!FeatureInvokeCallback(handle, cb, ret_data, code)) { \
            FEATURE_LOG_ERROR("invoke fail callback failed !"); \
        } \
    } while (0)

#define INVOKE_COMPLET_CB_INTERFACE(cb) \
    do { \
        if (!FeatureInvokeCallback(handle, cb)) { \
            FEATURE_LOG_ERROR("invoke complete callback failed !"); \
        } \
    } while (0)

#define REMOVE_ALL_CBS_INTERFACE(options) \
    do { \
        FeatureRemoveCallback(handle, options->success); \
        FeatureRemoveCallback(handle, options->fail); \
        FeatureRemoveCallback(handle, options->complete); \
    } while (0)

#define INVOKE_SUCCESS_CB(cb, ...) \
    do { \
        if (!FeatureInvokeCallback(feature, cb, ##__VA_ARGS__)) { \
            FEATURE_LOG_ERROR("invoke success callback failed !"); \
        } \
    } while (0)

#define INVOKE_FAIL_CB(cb, msg, code) \
    do { \
        if (!FeatureInvokeCallback(feature, cb, msg, code)) { \
            FEATURE_LOG_ERROR("invoke fail callback failed !"); \
        } \
    } while (0)

#define INVOKE_COMPLET_CB(cb) \
    do { \
        if (!FeatureInvokeCallback(feature, cb)) { \
            FEATURE_LOG_ERROR("invoke complete callback failed !"); \
        } \
    } while (0)

#define REMOVE_ALL_CBS(options) \
    do {                                                     \
        FeatureRemoveCallback(feature, options->success);            \
        FeatureRemoveCallback(feature, options->fail);            \
        FeatureRemoveCallback(feature, options->complete);         \
    } while (0)

#define CHECK_ERR_RET(ptr, msg) \
    do { \
        if (ptr == NULL) { \
            crypto_err = msg; \
            return NULL;\
        } \
    } while (0)

#define CHECK_ERR_BREAK(ptr, msg) \
    if (ptr == NULL) { \
        crypto_err = msg; \
        break; \
    }

#define check_str(ptr) ((ptr) && strlen(ptr) > 0)

#define check_any(ptr) ((ptr) && (ft_get_type (ft_ctx, *ptr) >= 0))

bool has_type(const char** type_array, int size, const char* type);

char** split_str(const char* input, const char* delimiter, int* count);

void free_str_array(char** str_array, int count);

#endif // _CRYPTO_UTILS_H_