/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "device.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'Device' ******/
static ObjectMember system_device_Device_struct_members[] = {
    { "brand", FT_STRING, offsetof(system_device_Device, brand), sizeof(FtString) },
    { "IMEI", FT_STRING, offsetof(system_device_Device, IMEI), sizeof(FtString) },
    { "manufacturer", FT_STRING, offsetof(system_device_Device, manufacturer), sizeof(FtString) },
    { "model", FT_STRING, offsetof(system_device_Device, model), sizeof(FtString) },
    { "product", FT_STRING, offsetof(system_device_Device, product), sizeof(FtString) },
    { "osType", FT_STRING, offsetof(system_device_Device, osType), sizeof(FtString) },
    { "osVersionName", FT_STRING, offsetof(system_device_Device, osVersionName), sizeof(FtString) },
    { "osVersionCode", FT_INT, offsetof(system_device_Device, osVersionCode), sizeof(FtInt) },
    { "platformVersionName", FT_STRING, offsetof(system_device_Device, platformVersionName), sizeof(FtString) },
    { "platformVersionCode", FT_INT, offsetof(system_device_Device, platformVersionCode), sizeof(FtInt) },
    { "APILevel", FT_INT, offsetof(system_device_Device, APILevel), sizeof(FtInt) },
    { "language", FT_STRING, offsetof(system_device_Device, language), sizeof(FtString) },
    { "region", FT_STRING, offsetof(system_device_Device, region), sizeof(FtString) },
    { "screenWidth", FT_INT, offsetof(system_device_Device, screenWidth), sizeof(FtInt) },
    { "screenHeight", FT_INT, offsetof(system_device_Device, screenHeight), sizeof(FtInt) },
    { "deviceType", FT_STRING, offsetof(system_device_Device, deviceType), sizeof(FtString) },
    { "screenShape", FT_STRING, offsetof(system_device_Device, screenShape), sizeof(FtString) },
    { "deviceId", FT_STRING, offsetof(system_device_Device, deviceId), sizeof(FtString) },
    { "serial", FT_STRING, offsetof(system_device_Device, serial), sizeof(FtString) },
    { "totalStorage", FT_STRING, offsetof(system_device_Device, totalStorage), sizeof(FtString) },
    { "availableStorage", FT_STRING, offsetof(system_device_Device, availableStorage), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_device_Device_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_device_Device) },
    .members = system_device_Device_struct_members
};

system_device_Device* system_deviceMallocDevice () {
    return (system_device_Device*)FeatureMalloc(
        sizeof(system_device_Device), FT_MK_COMPLEX(&system_device_Device_struct_type));
}


/****** for JIDL callback 'success_cb' ******/
static const FeatureType system_device_success_cb_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_Device_struct_type),
    FT_PARAM_END
};

static const CallbackType system_device_success_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_device_success_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'fail_cb' ******/
static const FeatureType system_device_fail_cb_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_device_fail_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_device_fail_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_device_complete_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_device_complete_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_device_complete_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'CallBack' ******/
static ObjectMember system_device_CallBack_struct_members[] = {
    { "success", FT_MK_COMPLEX(&system_device_success_cb_callback_type), offsetof(system_device_CallBack, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_device_fail_cb_callback_type), offsetof(system_device_CallBack, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_device_complete_cb_callback_type), offsetof(system_device_CallBack, complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_device_CallBack_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_device_CallBack) },
    .members = system_device_CallBack_struct_members
};

system_device_CallBack* system_deviceMallocCallBack () {
    return (system_device_CallBack*)FeatureMalloc(
        sizeof(system_device_CallBack), FT_MK_COMPLEX(&system_device_CallBack_struct_type));
}


/****** for JIDL function 'getInfo' ******/
static const FeatureType system_device_getInfo_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getInfo_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getInfo) },
    .parameters = system_device_getInfo_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_device_Device_struct_type),
};


/****** for JIDL function 'getDeviceId' ******/
static const FeatureType system_device_getDeviceId_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getDeviceId_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getDeviceId) },
    .parameters = system_device_getDeviceId_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL function 'getId' ******/
static const FeatureType system_device_getId_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getId_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getId) },
    .parameters = system_device_getId_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL function 'getSerial' ******/
static const FeatureType system_device_getSerial_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getSerial_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getSerial) },
    .parameters = system_device_getSerial_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL function 'getTotalStorage' ******/
static const FeatureType system_device_getTotalStorage_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getTotalStorage_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getTotalStorage) },
    .parameters = system_device_getTotalStorage_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL function 'getAvailableStorage' ******/
static const FeatureType system_device_getAvailableStorage_parameters[] = {
    FT_MK_COMPLEX_REF(&system_device_CallBack_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_device_getAvailableStorage_member_method = {
    .func = { .callback = FFI_FN(system_device_wrap_getAvailableStorage) },
    .parameters = system_device_getAvailableStorage_parameters,
    .return_type = FT_STRING,
};


// members
static const Member system_device_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "getInfo",
        .method = system_device_getInfo_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getDeviceId",
        .method = system_device_getDeviceId_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getId",
        .method = system_device_getId_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getSerial",
        .method = system_device_getSerial_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getTotalStorage",
        .method = system_device_getTotalStorage_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getAvailableStorage",
        .method = system_device_getAvailableStorage_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_device_callbacks {
    system_device_onRegister,
    system_device_onCreate,
    system_device_onRequired,
    system_device_onDetached,
    system_device_onDestroy,
    system_device_onUnregister
};

static const FeatureDescription system_device_desc = {
    .version = 1,
    .name = "system.device",
    .description = "system.device",
    { .dynamic = false },
    .native_callbacks = &system_device_callbacks,
    .member_count = countof(system_device_members),
    .members = system_device_members,
};

QAPPFEATURE_INIT(system_device)
{
    return mgr->registerFeature(features, &system_device_desc);
}
/* clang-format on */
