/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_DEVICE_H_
#define JSON_AST_GEN_MODULE_DEVICE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void device_onRegister(const char* feature_name);
void device_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void device_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void device_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void device_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void device_onUnregister(const char* feature_name);

// Struct defines
typedef struct _Device {
  FtString _brand;
  FtString _IMEI;
  FtString _manufacturer;
  FtString _model;
  FtString _product;
  FtString _osType;
  FtString _osVersionName;
  FtInt _osVersionCode;
  FtString _platformVersionName;
  FtInt _platformVersionCode;
  FtInt _APILevel;
  FtString _language;
  FtString _region;
  FtInt _screenWidth;
  FtInt _screenHeight;
  FtString _deviceType;
  FtString _screenShape;
} device_Device;

device_Device* deviceMallocDevice();


// Function wrappers to be implemented
device_Device * device_wrap_getInfo(FeatureInstanceHandle feature, AppendData append_data);
FtString device_wrap_getDeviceid(FeatureInstanceHandle feature, AppendData append_data);
FtString device_wrap_getid(FeatureInstanceHandle feature, AppendData append_data);
FtString device_wrap_getserial(FeatureInstanceHandle feature, AppendData append_data);
FtString device_wrap_gettotalstorage(FeatureInstanceHandle feature, AppendData append_data);
FtString device_wrap_getavailablestorage(FeatureInstanceHandle feature, AppendData append_data);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_DEVICE_H_
/* clang-format on */
