/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "error.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL function 'strerror' ******/
static const FeatureType Error_strerror_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod Error_strerror_member_method = {
    .func = { .callback = FFI_FN(Error_wrap_strerror) },
    .parameters = Error_strerror_parameters,
    .return_type = FT_STRING,
};


// members
static const Member Error_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "strerror",
        .method = Error_strerror_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks Error_callbacks {
    Error_onRegister,
    Error_onCreate,
    Error_onRequired,
    Error_onDetached,
    Error_onDestroy,
    Error_onUnregister
};

static const FeatureDescription Error_desc = {
    .version = 1,
    .name = "Error",
    .description = "Error",
    { .dynamic = false },
    .native_callbacks = &Error_callbacks,
    .member_count = countof(Error_members),
    .members = Error_members,
};

QAPPFEATURE_INIT(Error)
{
    return mgr->registerFeature(features, &Error_desc);
}
/* clang-format on */
