/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_EXCHANGE_H_
#define JSON_AST_GEN_MODULE_SYSTEM_EXCHANGE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_exchange_onRegister(const char* feature_name);
void system_exchange_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_exchange_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_exchange_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_exchange_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_exchange_onUnregister(const char* feature_name);

// Struct defines
typedef struct _GetInfo {
  FtString key;
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_exchange_GetInfo;

system_exchange_GetInfo* system_exchangeMallocGetInfo();

typedef struct _SetInfo {
  FtString key;
  FtString value;
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_exchange_SetInfo;

system_exchange_SetInfo* system_exchangeMallocSetInfo();

typedef struct _RemoveInfo {
  FtString key;
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_exchange_RemoveInfo;

system_exchange_RemoveInfo* system_exchangeMallocRemoveInfo();

typedef struct _ClearInfo {
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_exchange_ClearInfo;

system_exchange_ClearInfo* system_exchangeMallocClearInfo();


// Function wrappers to be implemented
void system_exchange_wrap_set(FeatureInstanceHandle feature, AppendData append_data, system_exchange_SetInfo * info);
void system_exchange_wrap_get(FeatureInstanceHandle feature, AppendData append_data, system_exchange_GetInfo * info);
void system_exchange_wrap_remove(FeatureInstanceHandle feature, AppendData append_data, system_exchange_RemoveInfo * info);
void system_exchange_wrap_clear(FeatureInstanceHandle feature, AppendData append_data, system_exchange_ClearInfo * info);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_EXCHANGE_H_
/* clang-format on */
