/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SERVICE_EXCHANGE_H_
#define JSON_AST_GEN_MODULE_SERVICE_EXCHANGE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void service_exchange_onRegister(const char* feature_name);
void service_exchange_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void service_exchange_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void service_exchange_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void service_exchange_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void service_exchange_onUnregister(const char* feature_name);

// Struct defines
typedef struct _GetInfo {
  FtString package;
  FtString sign;
  FtString key;
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} service_exchange_GetInfo;

service_exchange_GetInfo* service_exchangeMallocGetInfo();

typedef struct _SetInfo {
  FtString key;
  FtString value;
  FtString scope;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
  FtString package;
  FtString sign;
} service_exchange_SetInfo;

service_exchange_SetInfo* service_exchangeMallocSetInfo();

typedef struct _RemoveInfo {
  FtString key;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
  FtString package;
  FtString sign;
} service_exchange_RemoveInfo;

service_exchange_RemoveInfo* service_exchangeMallocRemoveInfo();

typedef struct _ClearInfo {
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} service_exchange_ClearInfo;

service_exchange_ClearInfo* service_exchangeMallocClearInfo();

typedef struct _GrantPermissionInfo {
  FtString package;
  FtString sign;
  FtString key;
  FtBool writable;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} service_exchange_GrantPermissionInfo;

service_exchange_GrantPermissionInfo* service_exchangeMallocGrantPermissionInfo();

typedef struct _RevokePermissionInfo {
  FtString package;
  FtString key;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} service_exchange_RevokePermissionInfo;

service_exchange_RevokePermissionInfo* service_exchangeMallocRevokePermissionInfo();


// Function wrappers to be implemented
void service_exchange_wrap_set(FeatureInstanceHandle feature, AppendData append_data, service_exchange_SetInfo * info);
void service_exchange_wrap_get(FeatureInstanceHandle feature, AppendData append_data, service_exchange_GetInfo * info);
void service_exchange_wrap_remove(FeatureInstanceHandle feature, AppendData append_data, service_exchange_RemoveInfo * info);
void service_exchange_wrap_clear(FeatureInstanceHandle feature, AppendData append_data, service_exchange_ClearInfo * info);
void service_exchange_wrap_grantPermission(FeatureInstanceHandle feature, AppendData append_data, service_exchange_GrantPermissionInfo * info);
void service_exchange_wrap_revokePermission(FeatureInstanceHandle feature, AppendData append_data, service_exchange_RevokePermissionInfo * info);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SERVICE_EXCHANGE_H_
/* clang-format on */
