/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_FETCH_H_
#define JSON_AST_GEN_MODULE_FETCH_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void fetch_onRegister(const char* feature_name);
void fetch_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void fetch_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void fetch_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void fetch_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void fetch_onUnregister(const char* feature_name);

// Struct defines
typedef struct _SuccessRes {
  FtInt _code;
  FtAny _data;
  FtAny _headers;
} fetch_SuccessRes;

fetch_SuccessRes* fetchMallocSuccessRes();

typedef struct _FetchPara {
  FtString _url;
  FtAny _data;
  FtAny _header;
  FtString _method;
  FtString _responseType;
  FtInt _timeout;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} fetch_FetchPara;

fetch_FetchPara* fetchMallocFetchPara();


// Function wrappers to be implemented
void fetch_wrap_fetch(FeatureInstanceHandle feature, AppendData append_data, fetch_FetchPara * obj);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_FETCH_H_
/* clang-format on */
