/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */
#include "file.h"
#include "feature_config.h"
#include <cstdlib>
#include <uv.h>
#include "jse_apppath.h"

static const char* file_tag = "[jidl_feature] file_impl";

#define FILE_INFO(fmt, ...) \
    FILE_INFO("[feature_file] " fmt, ##__VA_ARGS__)

#define FILE_ERROR(fmt, ...) \
    FEATURE_LOG_ERROR("[feature_file] " fmt, ##__VA_ARGS__)

typedef struct
{
    uv_loop_t* loop;
    const char* pkg_name;
} FileContext;

FileContext* fc = NULL;

void file_onRegister(const char* feature_name) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void file_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
    fc = static_cast<FileContext*>(malloc(sizeof(*fc)));
    FeatureManagerHandle manager = FeatureGetManagerHandleFromProto(handle);
    fc->loop = FeatureGetUVLoop(manager);
    fc->pkg_name = FeatureGetPackageName(handle);
}
void file_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void file_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void file_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
    free(fc);
}
void file_onUnregister(const char* feature_name) {
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

typedef struct
{
    uv_fs_t req;
    int magic;
    int success;
    int fail;
    int complete;
    FeatureInstanceHandle handle;
} FsReq;

static int __error_code_map(int error)
{
    int code = IOERROR;
    switch (error) {
    case -2:
        code = PATH_NOT_EXISTS;
        break;
    case -22:
        code = ARGSERROR;
        break;
    }
    return code;
}

static void __uv_fs_req_cb(uv_fs_t* req) {
    FILE_INFO("req->result = %d", req->result);
    FsReq* fr = static_cast<FsReq*>(req->data);
    if (!fr) {
        return;
    }
    if(req->result < 0) {
        FeatureInvokeCallback(fr->handle, fr->fail, uv_strerror(req->result), __error_code_map(req->result));
    } else {
        switch (req->fs_type)
        {
        case UV_FS_COPYFILE:
        case UV_FS_RENAME:
            FeatureInvokeCallback(fr->handle, fr->success, req->path);
            break;
        case UV_FS_UNLINK:
        case UV_FS_ACCESS:
            FeatureInvokeCallback(fr->handle, fr->success);
            break;
        default:
            break;
        }
    }
    FeatureInvokeCallback(fr->handle, fr->complete);
    uv_fs_req_cleanup(req);
    free(fr);
}


void file_copy_or_move(FeatureInstanceHandle feature, file_move_param_t * param, bool move = true) {
    char *temp_str, *path, *new_path;
    const char* msg;
    int code, result;
    FsReq* fr = static_cast<FsReq*>(malloc(sizeof(*fr)));
    if(!fr) {
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    fr->success = param->_success;
    fr->fail = param->_fail;
    fr->complete = param->_complete;
    fr->handle = feature;

    if(param->_srcUri == NULL || param->_dstUri == NULL) {
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
        return;
    }

    temp_str = strdup(param->_srcUri);
    path = AIOTJS::app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if(!path) {
        path = AIOTJS::app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    temp_str = strdup(param->_dstUri);
    new_path = AIOTJS::app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if(!new_path) {
        new_path = AIOTJS::app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    if(path == NULL || new_path == NULL) {
        FILE_ERROR("src path:%s, dest path:%s\n", path, new_path);
        free(path);
        free(new_path);
        msg = "invalid parameter";
        code = ARGSERROR;
        goto fail;
    }
    FILE_INFO("path = %s, new_path = %s", path, new_path);
    result = move ?
        uv_fs_rename(fc->loop, &fr->req, path, new_path, __uv_fs_req_cb) :
        uv_fs_copyfile(fc->loop, &fr->req, path, new_path, 0, __uv_fs_req_cb);
    if(result != 0) {
        FILE_ERROR("wrong result = %d", result);
    }
    fr->req.data = fr;
    return;
fail:
    FeatureInvokeCallback(feature, fr->fail, msg, code);
    FeatureInvokeCallback(feature, fr->complete);
    if(fr) free(fr);
}

void file_wrap_move(FeatureInstanceHandle feature, AppendData append_data, file_move_param_t * param) {
    file_copy_or_move(feature, param, true);
}
void file_wrap_copy(FeatureInstanceHandle feature, AppendData append_data, file_copy_param_t * param) {
    file_copy_or_move(feature, (file_move_param_t*)param, false);
}
void file_access_or_delete(FeatureInstanceHandle feature, file_access_param_t * param, bool access = true) {
    char *temp_str, *path;
    const char* msg;
    int code, result;
    // FILE_INFO("uri = %s", param->_uri);
    FsReq* fr = static_cast<FsReq*>(malloc(sizeof(*fr)));
        if(!fr) {
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    fr->success = param->_success;
    fr->fail = param->_fail;
    fr->complete = param->_complete;
    fr->handle = feature;

    if(!param->_uri) {
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
    }

    temp_str = strdup(param->_uri);
    path = AIOTJS::app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if(!path) {
        path = AIOTJS::app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    if(path == NULL) {
        FILE_ERROR("uri path: %s\n", path);
        free(path);
        msg = "invalid parameter";
        code = ARGSERROR;
        goto fail;
    }
    FILE_INFO("path = %s", path);
    result = access ?
        uv_fs_access(fc->loop, &fr->req, path, F_OK, __uv_fs_req_cb):
        uv_fs_unlink(fc->loop, &fr->req, path, __uv_fs_req_cb);
    if(result != 0) {
        FILE_ERROR("wrong result = %d", result);
    }
    fr->req.data = fr;
    return;
fail:
    FeatureInvokeCallback(feature, fr->fail, msg, code);
    FeatureInvokeCallback(feature, fr->complete);
    if(fr) free(fr);
}
void file_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, file_delete_param_t * param) {
    file_access_or_delete(feature, (file_access_param_t*)param, false);
}
void file_wrap_access(FeatureInstanceHandle feature, AppendData append_data, file_access_param_t * param) {
    file_access_or_delete(feature, param, true);
}

static void __load_dir_after_work_cb(uv_work_t* req, int status) {

}

void file_wrap_list(FeatureInstanceHandle feature, AppendData append_data, file_list_param_t * param) {

}
void file_wrap_get(FeatureInstanceHandle feature, AppendData append_data, file_get_param_t * param) {

}

void file_wrap_writeText(FeatureInstanceHandle feature, AppendData append_data, file_write_text_param_t * param) {

}
void file_wrap_writeArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, file_write_arr_buf_param_t * param) {

}
void file_wrap_readText(FeatureInstanceHandle feature, AppendData append_data, file_read_text_param_t * param) {

}
void file_wrap_readArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, file_ReadArrayBufferPara * param) {

}

void file_wrap_mkdir(FeatureInstanceHandle feature, AppendData append_data, file_mkdir_param_t * param) {

}
void file_wrap_rmdir(FeatureInstanceHandle feature, AppendData append_data, file_rmdir_param_t * param) {

}
