/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_FILE_H_
#define JSON_AST_GEN_MODULE_SYSTEM_FILE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_file_onRegister(const char* feature_name);
void system_file_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_file_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_file_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_file_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_file_onUnregister(const char* feature_name);

// Struct defines
typedef struct _move_param_t {
  FtString srcUri;
  FtString dstUri;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_move_param_t;

system_file_move_param_t* system_fileMallocmove_param_t();

typedef struct _copy_param_t {
  FtString srcUri;
  FtString dstUri;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_copy_param_t;

system_file_copy_param_t* system_fileMalloccopy_param_t();

typedef struct _file_info_t {
  FtString uri;
  FtInt length;
  FtString lastModifiedTime;
} system_file_file_info_t;

system_file_file_info_t* system_fileMallocfile_info_t();

typedef struct _list_succ_param {
  FtArray* fileList;
} system_file_list_succ_param;

system_file_list_succ_param* system_fileMalloclist_succ_param();

typedef struct _list_param_t {
  FtString uri;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_list_param_t;

system_file_list_param_t* system_fileMalloclist_param_t();

typedef struct _extended_file_info_t {
  FtString uri;
  FtInt length;
  FtString lastModifiedTime;
  FtString type;
  FtArray* subFiles;
} system_file_extended_file_info_t;

system_file_extended_file_info_t* system_fileMallocextended_file_info_t();

typedef struct _get_param_t {
  FtString uri;
  FtBool recursive;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_get_param_t;

system_file_get_param_t* system_fileMallocget_param_t();

typedef struct _delete_param_t {
  FtString uri;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_delete_param_t;

system_file_delete_param_t* system_fileMallocdelete_param_t();

typedef struct _write_text_param_t {
  FtString uri;
  FtString text;
  FtString encoding;
  FtBool append;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_write_text_param_t;

system_file_write_text_param_t* system_fileMallocwrite_text_param_t();

typedef struct _write_arr_buf_param_t {
  FtString uri;
  FtAny buffer;
  FtInt position;
  FtBool append;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_write_arr_buf_param_t;

system_file_write_arr_buf_param_t* system_fileMallocwrite_arr_buf_param_t();

typedef struct _read_txt_succ_t {
  FtString text;
} system_file_read_txt_succ_t;

system_file_read_txt_succ_t* system_fileMallocread_txt_succ_t();

typedef struct _read_text_param_t {
  FtString uri;
  FtString encoding;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_read_text_param_t;

system_file_read_text_param_t* system_fileMallocread_text_param_t();

typedef struct _read_arr_buf_succ_t {
  FtAny buffer;
} system_file_read_arr_buf_succ_t;

system_file_read_arr_buf_succ_t* system_fileMallocread_arr_buf_succ_t();

typedef struct _read_arr_buf_t {
  FtString uri;
  FtInt position;
  FtInt length;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_read_arr_buf_t;

system_file_read_arr_buf_t* system_fileMallocread_arr_buf_t();

typedef struct _access_param_t {
  FtString uri;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_access_param_t;

system_file_access_param_t* system_fileMallocaccess_param_t();

typedef struct _mkdir_param_t {
  FtString uri;
  FtBool recursive;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_mkdir_param_t;

system_file_mkdir_param_t* system_fileMallocmkdir_param_t();

typedef struct _rmdir_param_t {
  FtString uri;
  FtBool recursive;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_file_rmdir_param_t;

system_file_rmdir_param_t* system_fileMallocrmdir_param_t();


// Function wrappers to be implemented
void system_file_wrap_move(FeatureInstanceHandle feature, AppendData append_data, system_file_move_param_t * param);
void system_file_wrap_copy(FeatureInstanceHandle feature, AppendData append_data, system_file_copy_param_t * param);
void system_file_wrap_list(FeatureInstanceHandle feature, AppendData append_data, system_file_list_param_t * param);
void system_file_wrap_get(FeatureInstanceHandle feature, AppendData append_data, system_file_get_param_t * param);
void system_file_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, system_file_delete_param_t * param);
void system_file_wrap_writeText(FeatureInstanceHandle feature, AppendData append_data, system_file_write_text_param_t * param);
void system_file_wrap_writeArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, system_file_write_arr_buf_param_t * param);
void system_file_wrap_readText(FeatureInstanceHandle feature, AppendData append_data, system_file_read_text_param_t * param);
void system_file_wrap_readArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, system_file_read_arr_buf_t * param);
void system_file_wrap_access(FeatureInstanceHandle feature, AppendData append_data, system_file_access_param_t * param);
void system_file_wrap_mkdir(FeatureInstanceHandle feature, AppendData append_data, system_file_mkdir_param_t * param);
void system_file_wrap_rmdir(FeatureInstanceHandle feature, AppendData append_data, system_file_rmdir_param_t * param);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions
FtArray* system_file_malloc_file_info_t_struct_type_array();
FtArray* system_file_malloc_extended_file_info_t_struct_type_array();

#endif // JSON_AST_GEN_MODULE_SYSTEM_FILE_H_
/* clang-format on */
