/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_FILE_H_
#define JSON_AST_GEN_MODULE_FILE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void file_onRegister(const char* feature_name);
void file_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void file_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void file_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void file_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void file_onUnregister(const char* feature_name);

// Struct defines
typedef struct _move_param_t {
  FtString _srcUri;
  FtString _dstUri;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_move_param_t;

file_move_param_t* fileMallocmove_param_t();

typedef struct _copy_param_t {
  FtString _srcUri;
  FtString _dstUri;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_copy_param_t;

file_copy_param_t* fileMalloccopy_param_t();

typedef struct _file_info_t {
  FtString _uri;
  FtInt _length;
  FtInt _lastModifiedTime;
} file_file_info_t;

file_file_info_t* fileMallocfile_info_t();

typedef struct _list_succ_param {
  FtAny _fileList;
} file_list_succ_param;

file_list_succ_param* fileMalloclist_succ_param();

typedef struct _list_param_t {
  FtString _uri;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_list_param_t;

file_list_param_t* fileMalloclist_param_t();

typedef struct _extended_file_info_t {
  FtString _uri;
  FtInt _length;
  FtInt _lastModifiedTime;
  FtString _type;
  FtAny _subFiles;
} file_extended_file_info_t;

file_extended_file_info_t* fileMallocextended_file_info_t();

typedef struct _get_param_t {
  FtString _uri;
  FtBool _recursive;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_get_param_t;

file_get_param_t* fileMallocget_param_t();

typedef struct _delete_param_t {
  FtString _uri;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_delete_param_t;

file_delete_param_t* fileMallocdelete_param_t();

typedef struct _write_text_param_t {
  FtString _uri;
  FtString _text;
  FtString _encoding;
  FtBool _append;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_write_text_param_t;

file_write_text_param_t* fileMallocwrite_text_param_t();

typedef struct _write_arr_buf_param_t {
  FtString _uri;
  FtArray* _buffer;
  FtInt _position;
  FtBool _append;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_write_arr_buf_param_t;

file_write_arr_buf_param_t* fileMallocwrite_arr_buf_param_t();

typedef struct _read_txt_succ_t {
  FtString _text;
} file_read_txt_succ_t;

file_read_txt_succ_t* fileMallocread_txt_succ_t();

typedef struct _read_text_param_t {
  FtString _uri;
  FtString _encoding;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_read_text_param_t;

file_read_text_param_t* fileMallocread_text_param_t();

typedef struct _read_arr_buf_succ_t {
  FtArray* _buffer;
} file_read_arr_buf_succ_t;

file_read_arr_buf_succ_t* fileMallocread_arr_buf_succ_t();

typedef struct _ReadArrayBufferPara {
  FtString _uri;
  FtInt _position;
  FtInt _length;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_ReadArrayBufferPara;

file_ReadArrayBufferPara* fileMallocReadArrayBufferPara();

typedef struct _access_param_t {
  FtString _uri;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_access_param_t;

file_access_param_t* fileMallocaccess_param_t();

typedef struct _mkdir_param_t {
  FtString _uri;
  FtBool _recursive;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_mkdir_param_t;

file_mkdir_param_t* fileMallocmkdir_param_t();

typedef struct _rmdir_param_t {
  FtString _uri;
  FtBool _recursive;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} file_rmdir_param_t;

file_rmdir_param_t* fileMallocrmdir_param_t();


// Function wrappers to be implemented
void file_wrap_move(FeatureInstanceHandle feature, AppendData append_data, file_move_param_t * param);
void file_wrap_copy(FeatureInstanceHandle feature, AppendData append_data, file_copy_param_t * param);
void file_wrap_list(FeatureInstanceHandle feature, AppendData append_data, file_list_param_t * param);
void file_wrap_get(FeatureInstanceHandle feature, AppendData append_data, file_get_param_t * param);
void file_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, file_delete_param_t * param);
void file_wrap_writeText(FeatureInstanceHandle feature, AppendData append_data, file_write_text_param_t * param);
void file_wrap_writeArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, file_write_arr_buf_param_t * param);
void file_wrap_readText(FeatureInstanceHandle feature, AppendData append_data, file_read_text_param_t * param);
void file_wrap_readArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, file_ReadArrayBufferPara * param);
void file_wrap_access(FeatureInstanceHandle feature, AppendData append_data, file_access_param_t * param);
void file_wrap_mkdir(FeatureInstanceHandle feature, AppendData append_data, file_mkdir_param_t * param);
void file_wrap_rmdir(FeatureInstanceHandle feature, AppendData append_data, file_rmdir_param_t * param);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions
FtArray* file_malloc_string_array();

#endif // JSON_AST_GEN_MODULE_FILE_H_
/* clang-format on */
