/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#include "app_path.h"
#include "feature_config.h"
#include "feature_utils.h"
#include "file.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <type_traits>
#include <uv.h>

#define INVOKE_SUCCESS_CB(cb, ...)                                 \
    do {                                                           \
        if (!FeatureInvokeCallback(feature, cb, ##__VA_ARGS__)) {  \
            FEATURE_LOG_ERROR("invoke success callback failed !"); \
        }                                                          \
        FeatureRemoveCallback(feature, cb);                        \
    } while (0)

#define INVOKE_FAIL_CB(cb, msg, code)                           \
    do {                                                        \
        if (!FeatureInvokeCallback(feature, cb, msg, code)) {   \
            FEATURE_LOG_ERROR("invoke fail callback failed !"); \
        }                                                       \
        FeatureRemoveCallback(feature, cb);                     \
    } while (0)

#define INVOKE_COMPLET_CB(cb)                                       \
    do {                                                            \
        if (!FeatureInvokeCallback(feature, cb)) {                  \
            FEATURE_LOG_ERROR("invoke complete callback failed !"); \
        }                                                           \
        FeatureRemoveCallback(feature, cb);                         \
    } while (0)

static const char* file_tag = "[jidl_feature] file_impl";

#define FILE_INFO(fmt, ...) \
    FEATURE_LOG_INFO("[feature_file] " fmt, ##__VA_ARGS__)

#define FILE_ERROR(fmt, ...) \
    FEATURE_LOG_ERROR("[feature_file] " fmt, ##__VA_ARGS__)

typedef struct
{
    uv_loop_t* loop;
    const char* pkg_name;
} FileContext;

FileContext* fc = NULL;

void system_file_onRegister(const char* feature_name)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_file_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
    fc = static_cast<FileContext*>(malloc(sizeof(*fc)));
    FeatureManagerHandle manager = FeatureGetManagerHandleFromProto(handle);
    fc->loop = FeatureGetUVLoop(manager);
    fc->pkg_name = FeatureGetPackageName(handle);
    if (!fc->pkg_name || strlen(fc->pkg_name) == 0) {
        FILE_ERROR("package name is null");
        fc->pkg_name = "file_test";
    }
    FILE_INFO("pkg name = %s", fc->pkg_name);
}
void system_file_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_file_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_file_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
    free(fc);
}
void system_file_onUnregister(const char* feature_name)
{
    FILE_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

typedef struct
{
    uv_fs_t req;
    int magic;
    int success;
    int fail;
    int complete;
    FeatureInstanceHandle handle;
} FsReq;

static int __error_code_map(int error)
{
    int code = IOERROR;
    switch (error) {
    case -2:
        code = PATH_NOT_EXISTS;
        break;
    case -22:
        code = ARGSERROR;
        break;
    }
    return code;
}

static void __uv_fs_req_cb(uv_fs_t* req)
{
    FILE_INFO("req->result = %d", req->result);
    FsReq* fr = static_cast<FsReq*>(req->data);
    if (!fr) {
        return;
    }
    FeatureInstanceHandle feature = fr->handle;
    if (req->result < 0) {
        INVOKE_FAIL_CB(fr->fail, uv_strerror(req->result), __error_code_map(req->result));
    } else {
        switch (req->fs_type) {
        case UV_FS_COPYFILE:
        case UV_FS_RENAME:
            INVOKE_SUCCESS_CB(fr->success, req->path);
            break;
        case UV_FS_UNLINK:
        case UV_FS_ACCESS:
            INVOKE_SUCCESS_CB(fr->success);
            break;
        default:
            break;
        }
    }
    INVOKE_COMPLET_CB(fr->complete);
    uv_fs_req_cleanup(req);
    free(fr);
}

void file_copy_or_move(FeatureInstanceHandle feature, system_file_move_param_t* param, bool move = true)
{
    char *temp_str, *path, *new_path;
    const char* msg;
    int code, result;
    FsReq* fr = static_cast<FsReq*>(malloc(sizeof(*fr)));
    if (!fr) {
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    fr->success = param->success;
    fr->fail = param->fail;
    fr->complete = param->complete;
    fr->handle = feature;

    if (param->srcUri == NULL || param->dstUri == NULL) {
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
        return;
    }

    temp_str = strdup(param->srcUri);
    path = app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if (!path) {
        path = app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    temp_str = strdup(param->dstUri);
    new_path = app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if (!new_path) {
        new_path = app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    if (path == NULL || new_path == NULL) {
        FILE_ERROR("src path:%s, dest path:%s\n", path, new_path);
        free(path);
        free(new_path);
        msg = "invalid parameter";
        code = ARGSERROR;
        goto fail;
    }
    FILE_INFO("path = %s, new_path = %s", path, new_path);
    result = move ? uv_fs_rename(fc->loop, &fr->req, path, new_path, __uv_fs_req_cb) : uv_fs_copyfile(fc->loop, &fr->req, path, new_path, 0, __uv_fs_req_cb);
    if (result != 0) {
        FILE_ERROR("wrong result = %d", result);
    }
    fr->req.data = fr;
    return;
fail:
    INVOKE_FAIL_CB(fr->fail, msg, code);
    INVOKE_COMPLET_CB(fr->complete);
    if (fr)
        free(fr);
}

void system_file_wrap_move(FeatureInstanceHandle feature, AppendData append_data, system_file_move_param_t* param)
{
    file_copy_or_move(feature, param, true);
}
void system_file_wrap_copy(FeatureInstanceHandle feature, AppendData append_data, system_file_copy_param_t* param)
{
    file_copy_or_move(feature, (system_file_move_param_t*)param, false);
}
void file_access_or_delete(FeatureInstanceHandle feature, system_file_access_param_t* param, bool access = true)
{
    char *temp_str, *path;
    const char* msg;
    int code, result;
    FsReq* fr = static_cast<FsReq*>(malloc(sizeof(*fr)));
    if (!fr) {
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    fr->success = param->success;
    fr->fail = param->fail;
    fr->complete = param->complete;
    fr->handle = feature;

    if (!param->uri) {
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
    }

    temp_str = strdup(param->uri);
    path = app_relative_to_absolute_path(fc->pkg_name, temp_str);
    if (!path) {
        path = app_absolute_path_generator(fc->pkg_name, "files", temp_str);
    }
    free(temp_str);
    if (path == NULL) {
        FILE_ERROR("uri path: %s\n", path);
        free(path);
        msg = "invalid parameter";
        code = ARGSERROR;
        goto fail;
    }
    FILE_INFO("path = %s", path);
    result = access ? uv_fs_access(fc->loop, &fr->req, path, F_OK, __uv_fs_req_cb) : uv_fs_unlink(fc->loop, &fr->req, path, __uv_fs_req_cb);
    if (result != 0) {
        FILE_ERROR("wrong result = %d", result);
    }
    fr->req.data = fr;
    return;
fail:
    INVOKE_FAIL_CB(fr->fail, msg, code);
    INVOKE_COMPLET_CB(fr->complete);
    if (fr)
        free(fr);
}
void system_file_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, system_file_delete_param_t* param)
{
    file_access_or_delete(feature, (system_file_access_param_t*)param, false);
}
void system_file_wrap_access(FeatureInstanceHandle feature, AppendData append_data, system_file_access_param_t* param)
{
    file_access_or_delete(feature, param, true);
}

enum {
    FILE_WRITEARRBUF,
    FILE_WRITETEXT,
    FILE_READARRBUF,
    FILE_READTEXT,
    FILE_GET,
    FILE_LIST,
    FILE_MKDIR,
    FILE_RMDIR,
};

typedef struct
{
    int8_t type; // 0:file 1:dir
    char* uri;
    uint64_t length;
    uint64_t last_modified_time;
    int dir_num;
    int file_num;
    struct weakref_list_node file_node;
    struct weakref_list_node dir_list;
} FileInfo;

typedef struct
{
    uv_work_t req;
    int r; // 保存连续嵌套函数错误码
    size_t len; // 文件读写数据长度
    size_t offset; // 文件读写偏移
    char* filename; // 文件路径
    uint8_t* buf; // 文件读写缓冲区
    FileInfo* root_file;
    int flags;
    int success;
    int fail;
    int complete;
    int type;
    FeatureInstanceHandle handle;
} FileReq;

void freeRootFile(FileInfo* root_file)
{
    FileInfo *item, *temp;
    weakref_list_for_every_entry_safe(&root_file->dir_list, item, temp, FileInfo, file_node)
    {
        freeRootFile(item);
    }

    free(root_file->uri);
    free(root_file);
}
void freeFileReq(FileReq* fr)
{
    if (fr) {
        if (fr->filename)
            free(fr->filename);
        if (fr->buf)
            FeatureFreeValue(fr->buf);
        if (fr->root_file) {
            freeRootFile(fr->root_file);
        }
        free(fr);
    }
}

void initFileReq(FileReq* fr)
{
    if (!fr)
        return;
    fr->r = -1;
    fr->filename = NULL;
    fr->buf = NULL;
    fr->root_file = NULL;
}

/**
 * @brief 递归创建文件夹，
 */
static void __create_dir(char* path, FileReq* fr)
{
    FILE_INFO("__create_dir, path = %s", path);
    char data[CONFIG_PATH_MAX];
    char* ret;

    if ((strcmp(path, ".") == 0) || (strcmp(path, "/") == 0))
        return;

    if (access(path, F_OK) == 0) {
        return;
    }

    else if (fr->flags == 1) { // 递归模式
        strncpy(data, path, sizeof(data) - 1);
        ret = strrchr(data, '/');
        if (ret == 0) {
            return;
        }
        *ret = 0;
        __create_dir(data, fr);
    }

    if (mkdir(path, 0777) != 0) {
        FILE_ERROR("file mkdir failed, path:%s,%d\n", path, errno);
        fr->r = -errno;
    }
    return;
}

/**
 * @brief 递归删除文件夹，
 */
static void __remove_dir(char* dirname, FileReq* fr)
{
    DIR* dir;
    struct dirent* entry;
    char path[CONFIG_PATH_MAX];

    dir = opendir(dirname);
    if (dir == NULL) {
        fr->r = -errno;
        FILE_ERROR("file opendir failed, path:%s\n", path);
        return;
    }

    while ((entry = readdir(dir)) != NULL) {
        if (strcmp(entry->d_name, ".") && strcmp(entry->d_name, "..")) {
            snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
            if (entry->d_type == DT_DIR && fr->flags == 1) {
                __remove_dir(path, fr);
            } else {
                unlink(path);
            }
        }
    }
    closedir(dir);
    rmdir(dirname);
}

/**
 * @brief 文件读写处理, uv_work 处理回调
 */
static void __load_file_work_cb(uv_work_t* wk)
{
    FileReq* fr = static_cast<FileReq*>(wk->data);
    if (!fr)
        return;

    uv_file fd;
    int r = 0, oflags = fr->flags;

    // 获取文件读取长度
    if ((int)fr->len == -1) {
        struct stat statbuf;
        r = stat(fr->filename, &statbuf);
        fr->len = statbuf.st_size;
        if (r < 0) {
            FILE_ERROR("file stat: file: %s, %s", fr->filename, strerror(errno));
            fr->r = -errno;
            return;
        }
    }

    fr->offset = ((int)fr->offset == -1) ? 0 : fr->offset;

    FILE_INFO("file open file: %s, %d, %d", fr->filename, fr->flags, fr->offset);
    if (oflags != O_RDONLY && !check_disk_limit()) {
        fr->r = -ENOSPC;
        FILE_ERROR("file write failed: No space left on device");
        return;
    }

    fd = open(fr->filename, fr->flags, 0777);
    if (fd < 0) {
        char path[PATH_MAX], *path_end;
        fr->flags = 1;
        strncpy(path, fr->filename, sizeof(path) - 1);
        path_end = strrchr(path, '/');
        assert(path_end != NULL);
        *path_end = '\0';
        __create_dir(path, fr);
        fd = open(fr->filename, oflags, 0777);
        if (fd < 0) {
            fr->r = -errno;
            FILE_ERROR("file open failed: file: %s, %s", fr->filename, strerror(errno));
            return;
        }
    }

    if (oflags == O_RDONLY) {
        fr->r = lseek(fd, fr->offset, SEEK_SET);
        if (fr->r < 0) {
            r = -errno;
            FILE_ERROR("file open failed: file: %s, %s", fr->filename, strerror(errno));
        } else {
            fr->buf = (uint8_t*)FeatureMalloc(fr->len, FT_UINT8);
            r = read(fd, fr->buf, fr->len);
            // char read_str[fr->len + 1];
            // for(int i = 0; i< fr->len; i++) {
            //     read_str[i] = fr->buf[i];
            // }
            // read_str[fr->len] = '\0';
            // FILE_INFO("read_str = %s", read_str);
            fr->len = r;
            if (r < 0) {
                r = -errno;
                FILE_ERROR("file read failed: file: %s, %s", fr->filename, strerror(errno));
            }
        }
    } else {
        if (!check_disk_limit()) {
            r = -ENOSPC;
            FILE_ERROR("file write failed: No space left on device");
        } else if (fr->buf != NULL && fr->len != 0) {
            fr->r = lseek(fd, fr->offset, SEEK_SET);
            if (fr->r < 0) {
                r = -errno;
                FILE_ERROR("file open failed: file: %s, %s", fr->filename, strerror(errno));
            } else {
                r = write(fd, (char*)fr->buf, fr->len);
                // char write_str[fr->len + 1];
                // for(int i = 0; i< fr->len; i++) {
                //     write_str[i] = fr->buf[i];
                // }
                // write_str[fr->len] = '\0';
                // FILE_INFO("write_str = %s", write_str);
                if (r < 0) {
                    r = -errno;
                    FILE_ERROR("file open failed: file: %s, %s", fr->filename, strerror(errno));
                }
            }
        }
    }
    close(fd);

    fr->r = r;
}

/**
 * @brief uv_work 处理完成回调，返回执行结果，释放内存
 */
static void __load_after_work_cb(uv_work_t* req, int status)
{
    FileReq* fr = static_cast<FileReq*>(req->data);
    if (!fr)
        return;

    FeatureInstanceHandle feature = fr->handle;
    // 0 表示成功完成
    if (status != 0) {
        INVOKE_FAIL_CB(fr->fail, uv_strerror(status), __error_code_map(status));
    } else if (fr->r < 0) {
        INVOKE_FAIL_CB(fr->fail, uv_strerror(fr->r), __error_code_map(fr->r));
    } else if (fr->type == FILE_READTEXT) {
        // 将读取的文件内容写入 String
        system_file_read_txt_succ_t* data = system_fileMallocread_txt_succ_t();
        data->text = (const char*)fr->buf;
        INVOKE_SUCCESS_CB(fr->success, data);
    } else if (fr->type == FILE_READARRBUF) {
        // 将读取的文件内容写入ArrayBuffer
        ft_value_t* buffer = (ft_value_t*)FeatureMalloc(sizeof(ft_value_t), FT_ANY);
        *buffer = ft_from_typed_buffer(FeatureGetContext(fr->handle), fr->buf, fr->len, 0);
        system_file_read_arr_buf_succ_t* data = system_fileMallocread_arr_buf_succ_t();
        data->buffer = buffer;
        INVOKE_SUCCESS_CB(fr->success, data);
        FeatureFreeValue(buffer);
    } else if (fr->type == FILE_WRITETEXT || fr->type == FILE_WRITEARRBUF) {
        INVOKE_SUCCESS_CB(fr->success);
    }

    INVOKE_COMPLET_CB(fr->complete);
    freeFileReq(fr);
}

template <typename T>
void __file_load(FeatureInstanceHandle feature, T* param, int type)
{
    const char* msg;
    int code, r;
    char *app_path, *temp_str;
    FileReq* fr = static_cast<FileReq*>(malloc(sizeof(*fr)));
    if (!fr) {
        FILE_ERROR("malloc fail");
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    initFileReq(fr);

    if (!param->uri) {
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
    }
    temp_str = strdup(param->uri);
    app_path = app_relative_to_absolute_path(fc->pkg_name, temp_str);
    free(temp_str);
    if (!app_path) {
        FILE_ERROR("invalid parameter :path");
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
    }

    fr->filename = app_path;
    fr->req.data = fr;
    fr->handle = feature;
    fr->success = param->success;
    fr->fail = param->fail;
    fr->complete = param->complete;
    fr->type = type;
    if constexpr (std::is_same_v<T, system_file_write_text_param_t>) {
        fr->offset = 0;
        if (param->append) {
            fr->flags = O_APPEND;
        } else {
            fr->flags = O_TRUNC;
        }
        fr->flags |= O_WRONLY | O_CREAT;
        fr->len = strlen(param->text) + 1;
        fr->buf = (uint8_t*)FeatureMalloc(fr->len, FT_UINT8);
        memcpy(fr->buf, param->text, fr->len);
    } else if constexpr (std::is_same_v<T, system_file_write_arr_buf_param_t>) {
        fr->offset = param->position;
        if (param->append) {
            fr->flags = O_APPEND;
            fr->offset = 0;
        } else {
            fr->flags = O_TRUNC;
        }
        fr->flags |= O_WRONLY | O_CREAT;
        // FILE_INFO("buf type = %d", ft_get_type(FeatureGetContext(feature), *(param->buffer)));
        uint8_t* buffer = ft_to_buffer(FeatureGetContext(feature), &(fr->len), *(param->buffer));
        fr->buf = (uint8_t*)FeatureMalloc(fr->len, FT_UINT8);
        memcpy(fr->buf, buffer, fr->len);
    } else if constexpr (std::is_same_v<T, system_file_read_text_param_t>) {
        fr->offset = 0;
        fr->len = -1;
        fr->flags = O_RDONLY;
    } else if constexpr (std::is_same_v<T, system_file_read_arr_buf_t>) {
        fr->offset = param->position;
        fr->flags = O_RDONLY;
        fr->len = param->length;
    }
    // 使用 libuv 线程池，处理需要多次回调的接口
    r = uv_queue_work(fc->loop, &fr->req, __load_file_work_cb,
        __load_after_work_cb);
    if (r != 0) {
        FILE_ERROR("execute uv_queue_work fail");
    }
    return;
fail:
    INVOKE_FAIL_CB(param->fail, msg, code);
    INVOKE_COMPLET_CB(param->complete);
    freeFileReq(fr);
}

void system_file_wrap_writeText(FeatureInstanceHandle feature, AppendData append_data, system_file_write_text_param_t* param)
{
    __file_load(feature, param, FILE_WRITETEXT);
}

void system_file_wrap_writeArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, system_file_write_arr_buf_param_t* param)
{
    __file_load(feature, param, FILE_WRITEARRBUF);
}

void system_file_wrap_readText(FeatureInstanceHandle feature, AppendData append_data, system_file_read_text_param_t* param)
{
    __file_load(feature, param, FILE_READTEXT);
}
void system_file_wrap_readArrayBuffer(FeatureInstanceHandle feature, AppendData append_data, system_file_read_arr_buf_t* param)
{
    __file_load(feature, param, FILE_READARRBUF);
}

/**
 * @brief 获取文件信息，返回FileInfo数据结构
 */
static FileInfo* __get_info_c(char* path, FileReq* fr)
{
    struct stat statbuf;
    char* app_path = NULL;
    FileInfo* file_info = (FileInfo*)malloc(sizeof(FileInfo));
    if (file_info == NULL || fc->pkg_name == NULL) {
        FILE_ERROR("fc->pkg_name=%p\n", fc->pkg_name);
        goto error;
    }

    fr->r = stat(path, &statbuf);
    if (fr->r != 0) {
        fr->r = -errno;
        FILE_ERROR("file doesn't exist, path: %s\n", path);
        goto error;
    }

    app_path = app_absolute_to_relative_path(fc->pkg_name, path);
    if (app_path == NULL) {
        FILE_ERROR("src path:%s, pkg:%s\n", path, fc->pkg_name);
        goto error;
    }

    weakref_list_initialize(&file_info->dir_list);
    weakref_list_initialize(&file_info->file_node);
    if (S_ISDIR(statbuf.st_mode)) {
        file_info->type = 1;
        file_info->length = 0;
    } else {
        file_info->type = 0;
        file_info->length = statbuf.st_size;
    }
    file_info->uri = app_path;
    file_info->last_modified_time = statbuf.st_mtim.tv_sec;
    file_info->file_num = 0;
    file_info->dir_num = 0;

    return file_info;
error:
    if (file_info) {
        free(file_info);
    }
    return NULL;
}
/**
 * @brief 递归读取文件夹信息，添加到list中
 */
static void __read_dir_c(char* dirname, FileReq* fr, weakref_list_node* dir_list)
{
    DIR* dir;
    struct dirent* entry;
    char path[CONFIG_PATH_MAX];
    FileInfo* file_info = NULL;
    FileInfo* root_file_ptr = weakref_container_of(dir_list, FileInfo, dir_list);
    root_file_ptr->file_num = 0;
    root_file_ptr->dir_num = 0;
    FILE_INFO("in __read_dir_c, cur dir = %s", root_file_ptr->uri);

    dir = opendir(dirname);
    if (dir == NULL) {
        fr->r = -errno;
        FILE_ERROR("file opendir failed, error: %d:%s path:%s", errno, uv_strerror(errno), dirname);
        return;
    }

    while ((entry = readdir(dir)) != NULL) {
        if (!strcmp(entry->d_name, ".") || !strcmp(entry->d_name, "..")) {
            continue;
        }

        snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);

        file_info = __get_info_c(path, fr);
        if (file_info == NULL) {
            continue;
        }
        if (fr->type == FILE_GET) {
            if (entry->d_type == DT_DIR) {
                __read_dir_c(path, fr, &file_info->dir_list);
            }
        }
        weakref_list_add_tail(dir_list, &file_info->file_node);

        if (file_info->type == 0) {
            root_file_ptr->file_num++;
        } else {
            root_file_ptr->dir_num++;
        }
        FILE_INFO("add child num, file = %s", file_info->uri);
    }
    closedir(dir);
}

/**
 * @brief 文件夹处理 uv_work 回调
 */
static void __load_dir_work_cb(uv_work_t* wk)
{
    FileReq* fr = static_cast<FileReq*>(wk->data);
    if (!fr)
        return;

    fr->r = 0;
    fr->offset = 0;

    switch (fr->type) {
    case FILE_MKDIR:
        __create_dir(fr->filename, fr);
        break;
    case FILE_RMDIR:
        __remove_dir(fr->filename, fr);
        break;
    case FILE_GET:
    case FILE_LIST:
        fr->flags = -1;
        fr->offset = 0;
        fr->root_file = __get_info_c(fr->filename, fr);
        if (fr->root_file && fr->root_file->type == 1) {
            __read_dir_c(fr->filename, fr, &fr->root_file->dir_list);
        }
        break;
    }
}
static FtArray* __get_dir_list(FileReq* fr, weakref_list_node* dir_list);

system_file_file_info_t* get_file_info(FileInfo* info)
{
    system_file_file_info_t* file_info = system_fileMallocfile_info_t();
    char* uri = static_cast<char*>(FeatureMalloc(strlen(info->uri) + 1, FT_CHAR));
    strncpy(uri, info->uri, strlen(info->uri));
    file_info->uri = uri;
    file_info->length = info->length;
    unsigned long long int num = static_cast<unsigned long long>(info->last_modified_time) * 1000;
    std::string time = std::to_string(num);
    char* lastModifiedTime = static_cast<char*>(FeatureMalloc(time.length() + 1, FT_CHAR));
    memcpy(lastModifiedTime, time.c_str(), time.length());
    file_info->lastModifiedTime = lastModifiedTime;
    return file_info;
}

system_file_extended_file_info_t* get_extended_file_info(FileReq* fr, FileInfo* info)
{
    if (!fr || !info)
        return NULL;
    system_file_extended_file_info_t* file_info = system_fileMallocextended_file_info_t();
    char* type = static_cast<char*>(FeatureMalloc(strlen(info->type == 0 ? "file" : "dir") + 1, FT_CHAR));
    sprintf(type, info->type == 0 ? "file" : "dir");
    file_info->type = type;
    char* uri = static_cast<char*>(FeatureMalloc(strlen(info->uri) + 1, FT_CHAR));
    strncpy(uri, info->uri, strlen(info->uri));
    file_info->uri = uri;
    file_info->length = info->length;
    unsigned long long int num = static_cast<unsigned long long>(info->last_modified_time) * 1000;
    std::string time = std::to_string(num);
    char* lastModifiedTime = static_cast<char*>(FeatureMalloc(time.length() + 1, FT_CHAR));
    memcpy(lastModifiedTime, time.c_str(), time.length());
    file_info->lastModifiedTime = lastModifiedTime;
    file_info->subFiles = __get_dir_list(fr, &info->dir_list);

    return file_info;
}

/**
 * @brief 获取FileList
 */
FtArray* __get_dir_list(FileReq* fr, weakref_list_node* dir_list)
{
    if (!dir_list) {
        FILE_ERROR("__get_dir_list failed, path:%s\n", fr->filename);
        return NULL;
    }

    FtArray* array;
    FileInfo* root_file_ptr = weakref_container_of(dir_list, FileInfo, dir_list);
    FILE_INFO("=====> __get_dir_list, root_file_ptr->uri = %s, dir_num = %d, file_num = %d", root_file_ptr->uri, root_file_ptr->dir_num, root_file_ptr->file_num);
    if (fr->type == FILE_GET) {
        array = system_file_malloc_extended_file_info_t_struct_type_array();
        array->_size = root_file_ptr->dir_num + root_file_ptr->file_num;
        array->_element = malloc(sizeof(system_file_extended_file_info_t*) * array->_size);
    } else {
        array = system_file_malloc_file_info_t_struct_type_array();
        array->_size = root_file_ptr->file_num;
        array->_element = malloc(sizeof(system_file_file_info_t*) * array->_size);
    }
    FILE_INFO("array.size = %d", array->_size);

    int index = 0;
    FileInfo *item, *temp;
    weakref_list_for_every_entry_safe(dir_list, item, temp, FileInfo, file_node)
    {
        if (fr->type == FILE_LIST) {
            if (item->type == 0) {
                system_file_file_info_t* file_info = get_file_info(item);
                FILE_INFO("index = %d, get file_info->uri = %s", index, file_info->uri);
                ((system_file_file_info_t**)array->_element)[index++] = file_info;
            }
        } else {
            ((system_file_extended_file_info_t**)array->_element)[index++] = get_extended_file_info(fr, item);
            FILE_INFO("index = %d, get file_info->uri: %s", index, ((system_file_extended_file_info_t**)array->_element)[index - 1]->uri);
        }
    }
    return array;
}

/**
 * @brief uv_work 处理完成回调，返回执行结果，释放内存
 */
static void __load_dir_after_work_cb(uv_work_t* req, int status)
{
    FileReq* fr = static_cast<FileReq*>(req->data);
    if (!fr)
        return;
    FeatureInstanceHandle feature = fr->handle;

    // 0 表示成功完成
    if (status != 0) {
        FILE_ERROR("file failed: file:%s, errno = %d", fr->filename, fr->r);
        INVOKE_FAIL_CB(fr->fail, uv_strerror(status), __error_code_map(status));
    } else if (fr->r < 0) {
        FILE_ERROR("file failed: file:%s, errno = %d", fr->filename, fr->r);
        INVOKE_FAIL_CB(fr->fail, uv_strerror(fr->r), __error_code_map(fr->r));
    } else if (fr->type == FILE_GET) {
        system_file_extended_file_info_t* file_info = get_extended_file_info(fr, fr->root_file);
        INVOKE_SUCCESS_CB(fr->success, file_info);
    } else if (fr->type == FILE_LIST) {
        system_file_list_succ_param* data = system_fileMalloclist_succ_param();
        if (fr->root_file) {
            data->fileList = __get_dir_list(fr, &fr->root_file->dir_list);
        }
        INVOKE_SUCCESS_CB(fr->success, data);
    } else {
        INVOKE_SUCCESS_CB(fr->success);
    }
    INVOKE_COMPLET_CB(fr->complete);
    // 释放相关资源
    freeFileReq(fr);
}

/**
 * @brief 文件夹处理函数
 */
template <typename T>
static void __dir_load(FeatureInstanceHandle feature, T* param, int type)
{
    const char* msg;
    int code, r;
    char *app_path, *temp_str;
    FileReq* fr = static_cast<FileReq*>(malloc(sizeof(*fr)));
    if (!fr) {
        FILE_ERROR("malloc fail");
        msg = "malloc fail";
        code = GENERAL;
        goto fail;
    }
    initFileReq(fr);

    if (!param->uri) {
        msg = "invalid path";
        code = ARGSERROR;
        goto fail;
    }
    temp_str = strdup(param->uri);
    app_path = app_relative_to_absolute_path(fc->pkg_name, temp_str);
    free(temp_str);
    if (!app_path) {
        FILE_ERROR("invalid parameter :path");
        msg = "invalid file path";
        code = ARGSERROR;
        goto fail;
    }

    fr->filename = app_path;
    fr->req.data = fr;
    fr->handle = feature;
    fr->success = param->success;
    fr->fail = param->fail;
    fr->complete = param->complete;
    fr->type = type;
    if constexpr (std::is_same_v<T, system_file_list_param_t>) {
        fr->flags = -1;
    } else {
        fr->flags = param->recursive;
    }
    // 使用 libuv 线程池，处理需要多次回调的接口
    r = uv_queue_work(fc->loop, &fr->req, __load_dir_work_cb,
        __load_dir_after_work_cb);
    if (r != 0) {
        FILE_ERROR("execute uv_queue_work fail");
    }
    return;
fail:
    INVOKE_FAIL_CB(param->fail, msg, code);
    INVOKE_COMPLET_CB(param->complete);
    freeFileReq(fr);
}

void system_file_wrap_mkdir(FeatureInstanceHandle feature, AppendData append_data, system_file_mkdir_param_t* param)
{
    __dir_load(feature, param, FILE_MKDIR);
}
void system_file_wrap_rmdir(FeatureInstanceHandle feature, AppendData append_data, system_file_rmdir_param_t* param)
{
    __dir_load(feature, param, FILE_RMDIR);
}
void system_file_wrap_list(FeatureInstanceHandle feature, AppendData append_data, system_file_list_param_t* param)
{
    __dir_load(feature, param, FILE_LIST);
}
void system_file_wrap_get(FeatureInstanceHandle feature, AppendData append_data, system_file_get_param_t* param)
{
    __dir_load(feature, param, FILE_GET);
}
