/* clang-format off */

/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#include "folme.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL callback 'onupdate_cb' ******/
static const FeatureType system_folme_onupdate_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_folme_onupdate_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_folme_onupdate_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'oncomplete_cb' ******/
static const FeatureType system_folme_oncomplete_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_folme_oncomplete_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_folme_oncomplete_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'config_t' ******/
static ObjectMember system_folme_config_t_struct_members[] = {
    { "delay", FT_ANY_REF, offsetof(system_folme_config_t, _delay), sizeof(FtAny) },
    { "ease", FT_ANY_REF, offsetof(system_folme_config_t, _ease), sizeof(FtAny) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_config_t) },
    .members = system_folme_config_t_struct_members
};

system_folme_config_t* system_folmeMallocconfig_t () {
    return (system_folme_config_t*)FeatureMalloc(
        sizeof(system_folme_config_t), FT_MK_COMPLEX_REF(&system_folme_config_t_struct_type));
}


/****** for JIDL struct 'to_config_t' ******/
static ObjectMember system_folme_to_config_t_struct_members[] = {
    { "id", FT_STRING, offsetof(system_folme_to_config_t, _id), sizeof(FtString) },
    { "toState", FT_ANY_REF, offsetof(system_folme_to_config_t, _toState), sizeof(FtAny) },
    { "config", FT_ANY_REF, offsetof(system_folme_to_config_t, _config), sizeof(FtAny) },
    { "onUpdate", FT_MK_COMPLEX(&system_folme_onupdate_cb_callback_type), offsetof(system_folme_to_config_t, _onUpdate), sizeof(FtCallbackId) },
    { "onComplete", FT_MK_COMPLEX(&system_folme_oncomplete_cb_callback_type), offsetof(system_folme_to_config_t, _onComplete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_to_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_to_config_t) },
    .members = system_folme_to_config_t_struct_members
};

system_folme_to_config_t* system_folmeMallocto_config_t () {
    return (system_folme_to_config_t*)FeatureMalloc(
        sizeof(system_folme_to_config_t), FT_MK_COMPLEX_REF(&system_folme_to_config_t_struct_type));
}


/****** for JIDL struct 'setto_config_t' ******/
static ObjectMember system_folme_setto_config_t_struct_members[] = {
    { "id", FT_STRING, offsetof(system_folme_setto_config_t, _id), sizeof(FtString) },
    { "toState", FT_ANY_REF, offsetof(system_folme_setto_config_t, _toState), sizeof(FtAny) },
    { "config", FT_ANY_REF, offsetof(system_folme_setto_config_t, _config), sizeof(FtAny) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_setto_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_setto_config_t) },
    .members = system_folme_setto_config_t_struct_members
};

system_folme_setto_config_t* system_folmeMallocsetto_config_t () {
    return (system_folme_setto_config_t*)FeatureMalloc(
        sizeof(system_folme_setto_config_t), FT_MK_COMPLEX_REF(&system_folme_setto_config_t_struct_type));
}


/****** for JIDL struct 'fromto_config_t' ******/
static ObjectMember system_folme_fromto_config_t_struct_members[] = {
    { "id", FT_STRING, offsetof(system_folme_fromto_config_t, _id), sizeof(FtString) },
    { "fromState", FT_ANY_REF, offsetof(system_folme_fromto_config_t, _fromState), sizeof(FtAny) },
    { "toState", FT_ANY_REF, offsetof(system_folme_fromto_config_t, _toState), sizeof(FtAny) },
    { "config", FT_ANY_REF, offsetof(system_folme_fromto_config_t, _config), sizeof(FtAny) },
    { "onUpdate", FT_MK_COMPLEX(&system_folme_onupdate_cb_callback_type), offsetof(system_folme_fromto_config_t, _onUpdate), sizeof(FtCallbackId) },
    { "onComplete", FT_MK_COMPLEX(&system_folme_oncomplete_cb_callback_type), offsetof(system_folme_fromto_config_t, _onComplete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_fromto_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_fromto_config_t) },
    .members = system_folme_fromto_config_t_struct_members
};

system_folme_fromto_config_t* system_folmeMallocfromto_config_t () {
    return (system_folme_fromto_config_t*)FeatureMalloc(
        sizeof(system_folme_fromto_config_t), FT_MK_COMPLEX_REF(&system_folme_fromto_config_t_struct_type));
}


/****** for JIDL struct 'cancel_config_t' ******/
static ObjectMember system_folme_cancel_config_t_struct_members[] = {
    { "id", FT_STRING, offsetof(system_folme_cancel_config_t, _id), sizeof(FtString) },
    { "attrs", FT_ANY_REF, offsetof(system_folme_cancel_config_t, _attrs), sizeof(FtAny) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_cancel_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_cancel_config_t) },
    .members = system_folme_cancel_config_t_struct_members
};

system_folme_cancel_config_t* system_folmeMalloccancel_config_t () {
    return (system_folme_cancel_config_t*)FeatureMalloc(
        sizeof(system_folme_cancel_config_t), FT_MK_COMPLEX_REF(&system_folme_cancel_config_t_struct_type));
}


/****** for JIDL struct 'getstate_config_t' ******/
static ObjectMember system_folme_getstate_config_t_struct_members[] = {
    { "id", FT_STRING, offsetof(system_folme_getstate_config_t, _id), sizeof(FtString) },
    { "attr", FT_STRING, offsetof(system_folme_getstate_config_t, _attr), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_getstate_config_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_getstate_config_t) },
    .members = system_folme_getstate_config_t_struct_members
};

system_folme_getstate_config_t* system_folmeMallocgetstate_config_t () {
    return (system_folme_getstate_config_t*)FeatureMalloc(
        sizeof(system_folme_getstate_config_t), FT_MK_COMPLEX_REF(&system_folme_getstate_config_t_struct_type));
}


/****** for JIDL struct 'animstate_t' ******/
static ObjectMember system_folme_animstate_t_struct_members[] = {
    { "value", FT_STRING, offsetof(system_folme_animstate_t, _value), sizeof(FtString) },
    { "isFinished", FT_BOOLEAN, offsetof(system_folme_animstate_t, _isFinished), sizeof(FtBool) },
    { "speed", FT_FLOAT, offsetof(system_folme_animstate_t, _speed), sizeof(FtFloat) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_folme_animstate_t_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_folme_animstate_t) },
    .members = system_folme_animstate_t_struct_members
};

system_folme_animstate_t* system_folmeMallocanimstate_t () {
    return (system_folme_animstate_t*)FeatureMalloc(
        sizeof(system_folme_animstate_t), FT_MK_COMPLEX_REF(&system_folme_animstate_t_struct_type));
}


/****** for JIDL function 'to' ******/
static const FeatureType system_folme_to_parameters[] = {
    FT_MK_COMPLEX(&system_folme_to_config_t_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_folme_to_member_method = {
    .func = { .callback = FFI_FN(system_folme_wrap_to) },
    .parameters = system_folme_to_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'setTo' ******/
static const FeatureType system_folme_setTo_parameters[] = {
    FT_MK_COMPLEX(&system_folme_setto_config_t_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_folme_setTo_member_method = {
    .func = { .callback = FFI_FN(system_folme_wrap_setTo) },
    .parameters = system_folme_setTo_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'fromTo' ******/
static const FeatureType system_folme_fromTo_parameters[] = {
    FT_MK_COMPLEX(&system_folme_fromto_config_t_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_folme_fromTo_member_method = {
    .func = { .callback = FFI_FN(system_folme_wrap_fromTo) },
    .parameters = system_folme_fromTo_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'cancel' ******/
static const FeatureType system_folme_cancel_parameters[] = {
    FT_MK_COMPLEX(&system_folme_cancel_config_t_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_folme_cancel_member_method = {
    .func = { .callback = FFI_FN(system_folme_wrap_cancel) },
    .parameters = system_folme_cancel_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'getState' ******/
static const FeatureType system_folme_getState_parameters[] = {
    FT_MK_COMPLEX(&system_folme_getstate_config_t_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_folme_getState_member_method = {
    .func = { .callback = FFI_FN(system_folme_wrap_getState) },
    .parameters = system_folme_getState_parameters,
    .return_type = FT_MK_COMPLEX(&system_folme_animstate_t_struct_type),
};


// members
static const Member system_folme_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "to",
        .method = &system_folme_to_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setTo",
        .method = &system_folme_setTo_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "fromTo",
        .method = &system_folme_fromTo_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "cancel",
        .method = &system_folme_cancel_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getState",
        .method = &system_folme_getState_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_folme_callbacks {
    system_folme_onRegister,
    system_folme_onCreate,
    system_folme_onRequired,
    system_folme_onDetached,
    system_folme_onDestroy,
    system_folme_onUnregister
};

static const FeatureDescription system_folme_desc = {
    .version = 1,
    .name = "system.folme",
    .description = "system.folme",
    { .dynamic = false },
    .native_callbacks = &system_folme_callbacks,
    .member_count = countof(system_folme_members),
    .members = system_folme_members,
};

QAPPFEATURE_INIT(system_folme)
{
    return FeatureRegisterFeature(handle, &system_folme_desc);
}
/* clang-format on */
