/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "jumpapp.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL function 'jumpApp' ******/
static const FeatureType jumpApp_jumpApp_parameters[] = {
    FT_STRING,
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod jumpApp_jumpApp_member_method = {
    .func = { .callback = FFI_FN(jumpApp_wrap_jumpApp) },
    .parameters = jumpApp_jumpApp_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'launchQuickApp' ******/
static const FeatureType jumpApp_launchQuickApp_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod jumpApp_launchQuickApp_member_method = {
    .func = { .callback = FFI_FN(jumpApp_wrap_launchQuickApp) },
    .parameters = jumpApp_launchQuickApp_parameters,
    .return_type = FT_VOID,
};


// members
static const Member jumpApp_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "jumpApp",
        .method = jumpApp_jumpApp_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "launchQuickApp",
        .method = jumpApp_launchQuickApp_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks jumpApp_callbacks {
    jumpApp_onRegister,
    jumpApp_onCreate,
    jumpApp_onRequired,
    jumpApp_onDetached,
    jumpApp_onDestroy,
    jumpApp_onUnregister
};

static const FeatureDescription jumpApp_desc = {
    .version = 1,
    .name = "jumpApp",
    .description = "jumpApp",
    { .dynamic = false },
    .native_callbacks = &jumpApp_callbacks,
    .member_count = countof(jumpApp_members),
    .members = jumpApp_members,
};

QAPPFEATURE_INIT(jumpApp)
{
    return mgr->registerFeature(features, &jumpApp_desc);
}
/* clang-format on */
