/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "message_channel.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL function 'sendMessage' ******/
static const FeatureType system_messageChannel_sendMessage_parameters[] = {
    FT_STRING,
    FT_STRING,
    FT_PARAM_END
};

static const PromiseType system_messageChannel_promise_FT_STRING_FT_STRING_type = {
    .header = { .type = COMPLEX_PROMISE, .size = sizeof(FtPromiseId) },
    .resolveTypes = { FT_STRING, FT_STRING }
};

static const MemberMethod system_messageChannel_sendMessage_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sendMessage) },
    .parameters = system_messageChannel_sendMessage_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_messageChannel_promise_FT_STRING_FT_STRING_type),
};


/****** for JIDL function 'reply' ******/
static const FeatureType system_messageChannel_reply_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_reply_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_reply) },
    .parameters = system_messageChannel_reply_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'cb_receive_request' ******/
static const FeatureType system_messageChannel_cb_receive_request_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_cb_receive_request_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_cb_receive_request_parameters,
    .return_type = FT_VOID
};


/****** for JIDL function 'setReceiveRequestCallback' ******/
static const FeatureType system_messageChannel_setReceiveRequestCallback_parameters[] = {
    FT_STRING,
    FT_MK_COMPLEX(&system_messageChannel_cb_receive_request_callback_type),
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_setReceiveRequestCallback_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_setReceiveRequestCallback) },
    .parameters = system_messageChannel_setReceiveRequestCallback_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'notifyMessage' ******/
static const FeatureType system_messageChannel_notifyMessage_parameters[] = {
    FT_STRING,
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_notifyMessage_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_notifyMessage) },
    .parameters = system_messageChannel_notifyMessage_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'onTopicMessage' ******/
static const FeatureType system_messageChannel_onTopicMessage_parameters[] = {
    FT_STRING,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_onTopicMessage_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_onTopicMessage_parameters,
    .return_type = FT_VOID
};


/****** for JIDL function 'setTopicListener' ******/
static const FeatureType system_messageChannel_setTopicListener_parameters[] = {
    FT_STRING,
    FT_MK_COMPLEX(&system_messageChannel_onTopicMessage_callback_type),
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_setTopicListener_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_setTopicListener) },
    .parameters = system_messageChannel_setTopicListener_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'unsetTopicListener' ******/
static const FeatureType system_messageChannel_unsetTopicListener_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_unsetTopicListener_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_unsetTopicListener) },
    .parameters = system_messageChannel_unsetTopicListener_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'cb_ondata' ******/
static const FeatureType system_messageChannel_cb_ondata_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_cb_ondata_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_cb_ondata_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'cb_onclose' ******/
static const FeatureType system_messageChannel_cb_onclose_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_cb_onclose_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_cb_onclose_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'cb_onerror' ******/
static const FeatureType system_messageChannel_cb_onerror_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_cb_onerror_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_cb_onerror_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'cb_onreceive' ******/
static const FeatureType system_messageChannel_cb_onreceive_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_messageChannel_cb_onreceive_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_messageChannel_cb_onreceive_parameters,
    .return_type = FT_VOID
};


/****** for JIDL function 'createSession' ******/
static const FeatureType system_messageChannel_createSession_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const PromiseType system_messageChannel_promise_FT_INT_FT_STRING_type = {
    .header = { .type = COMPLEX_PROMISE, .size = sizeof(FtPromiseId) },
    .resolveTypes = { FT_INT, FT_STRING }
};

static const MemberMethod system_messageChannel_createSession_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_createSession) },
    .parameters = system_messageChannel_createSession_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_messageChannel_promise_FT_INT_FT_STRING_type),
};


/****** for JIDL function 'sessionSend' ******/
static const FeatureType system_messageChannel_sessionSend_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_sessionSend_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sessionSend) },
    .parameters = system_messageChannel_sessionSend_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'sessionClose' ******/
static const FeatureType system_messageChannel_sessionClose_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_sessionClose_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sessionClose) },
    .parameters = system_messageChannel_sessionClose_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'acceptSession' ******/
static const FeatureType system_messageChannel_acceptSession_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_acceptSession_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_acceptSession) },
    .parameters = system_messageChannel_acceptSession_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'sessionOnData' ******/
static const FeatureType system_messageChannel_sessionOnData_parameters[] = {
    FT_INT,
    FT_MK_COMPLEX(&system_messageChannel_cb_ondata_callback_type),
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_sessionOnData_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sessionOnData) },
    .parameters = system_messageChannel_sessionOnData_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL const 'SESSION_REASON_CLOSE' ******/
const FtInt system_messageChannel_g_const_SESSION_REASON_CLOSE = 0;
const FtInt system_messageChannel_init_const_SESSION_REASON_CLOSE(FeatureInstanceHandle feature, AppendData append_data) { return system_messageChannel_g_const_SESSION_REASON_CLOSE; };

static const MemberConst system_messageChannel_SESSION_REASON_CLOSE_member_const = {
    .type = FT_INT,
    //.func = { .callback = FFI_FN(system_messageChannel_init_const_SESSION_REASON_CLOSE) },
    .func = { .callback = nullptr },
    .data = { .i32 = system_messageChannel_g_const_SESSION_REASON_CLOSE }
};

/****** for JIDL const 'SESSION_REASON_CLOSE_PEER' ******/
const FtInt system_messageChannel_g_const_SESSION_REASON_CLOSE_PEER = 1;
const FtInt system_messageChannel_init_const_SESSION_REASON_CLOSE_PEER(FeatureInstanceHandle feature, AppendData append_data) { return system_messageChannel_g_const_SESSION_REASON_CLOSE_PEER; };

static const MemberConst system_messageChannel_SESSION_REASON_CLOSE_PEER_member_const = {
    .type = FT_INT,
    //.func = { .callback = FFI_FN(system_messageChannel_init_const_SESSION_REASON_CLOSE_PEER) },
    .func = { .callback = nullptr },
    .data = { .i32 = system_messageChannel_g_const_SESSION_REASON_CLOSE_PEER }
};

/****** for JIDL const 'SESSION_REASON_PEER_SHUTDOWN' ******/
const FtInt system_messageChannel_g_const_SESSION_REASON_PEER_SHUTDOWN = 2;
const FtInt system_messageChannel_init_const_SESSION_REASON_PEER_SHUTDOWN(FeatureInstanceHandle feature, AppendData append_data) { return system_messageChannel_g_const_SESSION_REASON_PEER_SHUTDOWN; };

static const MemberConst system_messageChannel_SESSION_REASON_PEER_SHUTDOWN_member_const = {
    .type = FT_INT,
    //.func = { .callback = FFI_FN(system_messageChannel_init_const_SESSION_REASON_PEER_SHUTDOWN) },
    .func = { .callback = nullptr },
    .data = { .i32 = system_messageChannel_g_const_SESSION_REASON_PEER_SHUTDOWN }
};

/****** for JIDL function 'sessionOnClose' ******/
static const FeatureType system_messageChannel_sessionOnClose_parameters[] = {
    FT_INT,
    FT_MK_COMPLEX(&system_messageChannel_cb_onclose_callback_type),
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_sessionOnClose_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sessionOnClose) },
    .parameters = system_messageChannel_sessionOnClose_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'sessionOnReceive' ******/
static const FeatureType system_messageChannel_sessionOnReceive_parameters[] = {
    FT_STRING,
    FT_MK_COMPLEX(&system_messageChannel_cb_onreceive_callback_type),
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_sessionOnReceive_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_sessionOnReceive) },
    .parameters = system_messageChannel_sessionOnReceive_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'print' ******/
static const FeatureType system_messageChannel_print_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_messageChannel_print_member_method = {
    .func = { .callback = FFI_FN(system_messageChannel_wrap_print) },
    .parameters = system_messageChannel_print_parameters,
    .return_type = FT_VOID,
};


// members
static const Member system_messageChannel_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "sendMessage",
        .method = system_messageChannel_sendMessage_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "reply",
        .method = system_messageChannel_reply_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setReceiveRequestCallback",
        .method = system_messageChannel_setReceiveRequestCallback_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "notifyMessage",
        .method = system_messageChannel_notifyMessage_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setTopicListener",
        .method = system_messageChannel_setTopicListener_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "unsetTopicListener",
        .method = system_messageChannel_unsetTopicListener_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "createSession",
        .method = system_messageChannel_createSession_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sessionSend",
        .method = system_messageChannel_sessionSend_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sessionClose",
        .method = system_messageChannel_sessionClose_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "acceptSession",
        .method = system_messageChannel_acceptSession_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sessionOnData",
        .method = system_messageChannel_sessionOnData_member_method,
    },
    {
        .type = MEMBER_CONST,
        .name = "SESSION_REASON_CLOSE",
        .value = system_messageChannel_SESSION_REASON_CLOSE_member_const,
    },
    {
        .type = MEMBER_CONST,
        .name = "SESSION_REASON_CLOSE_PEER",
        .value = system_messageChannel_SESSION_REASON_CLOSE_PEER_member_const,
    },
    {
        .type = MEMBER_CONST,
        .name = "SESSION_REASON_PEER_SHUTDOWN",
        .value = system_messageChannel_SESSION_REASON_PEER_SHUTDOWN_member_const,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sessionOnClose",
        .method = system_messageChannel_sessionOnClose_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sessionOnReceive",
        .method = system_messageChannel_sessionOnReceive_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "print",
        .method = system_messageChannel_print_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_messageChannel_callbacks {
    system_messageChannel_onRegister,
    system_messageChannel_onCreate,
    system_messageChannel_onRequired,
    system_messageChannel_onDetached,
    system_messageChannel_onDestroy,
    system_messageChannel_onUnregister
};

static const FeatureDescription system_messageChannel_desc = {
    .version = 1,
    .name = "system.messageChannel",
    .description = "system.messageChannel",
    { .dynamic = false },
    .native_callbacks = &system_messageChannel_callbacks,
    .member_count = countof(system_messageChannel_members),
    .members = system_messageChannel_members,
};

QAPPFEATURE_INIT(system_messageChannel)
{
    return mgr->registerFeature(features, &system_messageChannel_desc);
}
/* clang-format on */
