/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "miplay.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL callback 'setMediainfoCb' ******/
static const FeatureType service_miplay_setMediainfoCb_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_STRING,
    FT_INT,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType service_miplay_setMediainfoCb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = service_miplay_setMediainfoCb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL function 'init' ******/
static const FeatureType service_miplay_init_parameters[] = {
    FT_MK_COMPLEX(&service_miplay_setMediainfoCb_callback_type),
    FT_PARAM_END
};

static const MemberMethod service_miplay_init_member_method = {
    .func = { .callback = FFI_FN(service_miplay_wrap_init) },
    .parameters = service_miplay_init_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'uninit' ******/
static const FeatureType service_miplay_uninit_parameters[] = {
    FT_PARAM_END
};

static const MemberMethod service_miplay_uninit_member_method = {
    .func = { .callback = FFI_FN(service_miplay_wrap_uninit) },
    .parameters = service_miplay_uninit_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'ctrlcmd' ******/
static const FeatureType service_miplay_ctrlcmd_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod service_miplay_ctrlcmd_member_method = {
    .func = { .callback = FFI_FN(service_miplay_wrap_ctrlcmd) },
    .parameters = service_miplay_ctrlcmd_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'volumeCtrl' ******/
static const FeatureType service_miplay_volumeCtrl_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod service_miplay_volumeCtrl_member_method = {
    .func = { .callback = FFI_FN(service_miplay_wrap_volumeCtrl) },
    .parameters = service_miplay_volumeCtrl_parameters,
    .return_type = FT_VOID,
};


// members
static const Member service_miplay_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "init",
        .method = service_miplay_init_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "uninit",
        .method = service_miplay_uninit_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "ctrlcmd",
        .method = service_miplay_ctrlcmd_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "volumeCtrl",
        .method = service_miplay_volumeCtrl_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks service_miplay_callbacks {
    service_miplay_onRegister,
    service_miplay_onCreate,
    service_miplay_onRequired,
    service_miplay_onDetached,
    service_miplay_onDestroy,
    service_miplay_onUnregister
};

static const FeatureDescription service_miplay_desc = {
    .version = 1,
    .name = "service.miplay",
    .description = "service.miplay",
    { .dynamic = false },
    .native_callbacks = &service_miplay_callbacks,
    .member_count = countof(service_miplay_members),
    .members = service_miplay_members,
};

QAPPFEATURE_INIT(service_miplay)
{
    return mgr->registerFeature(features, &service_miplay_desc);
}
/* clang-format on */
