/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "package.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'PackageInfo' ******/
static ObjectMember system_internal_package_PackageInfo_struct_members[] = {
    { "packageName", FT_STRING, offsetof(system_internal_package_PackageInfo, packageName), sizeof(FtString) },
    { "name", FT_STRING, offsetof(system_internal_package_PackageInfo, name), sizeof(FtString) },
    { "icon", FT_STRING, offsetof(system_internal_package_PackageInfo, icon), sizeof(FtString) },
    { "installedPath", FT_STRING, offsetof(system_internal_package_PackageInfo, installedPath), sizeof(FtString) },
    { "manifest", FT_STRING, offsetof(system_internal_package_PackageInfo, manifest), sizeof(FtString) },
    { "appType", FT_STRING, offsetof(system_internal_package_PackageInfo, appType), sizeof(FtString) },
    { "version", FT_STRING, offsetof(system_internal_package_PackageInfo, version), sizeof(FtString) },
    { "installTime", FT_STRING, offsetof(system_internal_package_PackageInfo, installTime), sizeof(FtString) },
    { "appSize", FT_INT, offsetof(system_internal_package_PackageInfo, appSize), sizeof(FtInt) },
    { "extra", FT_STRING, offsetof(system_internal_package_PackageInfo, extra), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_internal_package_PackageInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_internal_package_PackageInfo) },
    .members = system_internal_package_PackageInfo_struct_members
};

system_internal_package_PackageInfo* system_internal_packageMallocPackageInfo () {
    return (system_internal_package_PackageInfo*)FeatureMalloc(
        sizeof(system_internal_package_PackageInfo), FT_MK_COMPLEX(&system_internal_package_PackageInfo_struct_type));
}


/****** for JIDL callback 'installProgress_cb' ******/
static const FeatureType system_internal_package_installProgress_cb_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_internal_package_installProgress_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_internal_package_installProgress_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'installResult_cb' ******/
static const FeatureType system_internal_package_installResult_cb_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_internal_package_installResult_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_internal_package_installResult_cb_parameters,
    .return_type = FT_VOID
};


static OptionalType system_internal_package_InstallInfo_member_isForce_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_BOOLEAN,
    .ival = false
};

/****** for JIDL struct 'InstallInfo' ******/
static ObjectMember system_internal_package_InstallInfo_struct_members[] = {
    { "path", FT_STRING, offsetof(system_internal_package_InstallInfo, path), sizeof(FtString) },
    { "isForce", FT_MK_OPTIONAL(&system_internal_package_InstallInfo_member_isForce_opt_type), offsetof(system_internal_package_InstallInfo, isForce), sizeof(FtBool) },
    { "progress", FT_MK_COMPLEX(&system_internal_package_installProgress_cb_callback_type), offsetof(system_internal_package_InstallInfo, progress), sizeof(FtCallbackId) },
    { "result", FT_MK_COMPLEX(&system_internal_package_installResult_cb_callback_type), offsetof(system_internal_package_InstallInfo, result), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_internal_package_InstallInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_internal_package_InstallInfo) },
    .members = system_internal_package_InstallInfo_struct_members
};

system_internal_package_InstallInfo* system_internal_packageMallocInstallInfo () {
    return (system_internal_package_InstallInfo*)FeatureMalloc(
        sizeof(system_internal_package_InstallInfo), FT_MK_COMPLEX(&system_internal_package_InstallInfo_struct_type));
}


/****** for JIDL callback 'uninstallResult_cb' ******/
static const FeatureType system_internal_package_uninstallResult_cb_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_internal_package_uninstallResult_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_internal_package_uninstallResult_cb_parameters,
    .return_type = FT_VOID
};


static OptionalType system_internal_package_UninstallInfo_member_isClearCache_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_BOOLEAN,
    .ival = false
};

/****** for JIDL struct 'UninstallInfo' ******/
static ObjectMember system_internal_package_UninstallInfo_struct_members[] = {
    { "packageName", FT_STRING, offsetof(system_internal_package_UninstallInfo, packageName), sizeof(FtString) },
    { "isClearCache", FT_MK_OPTIONAL(&system_internal_package_UninstallInfo_member_isClearCache_opt_type), offsetof(system_internal_package_UninstallInfo, isClearCache), sizeof(FtBool) },
    { "result", FT_MK_COMPLEX(&system_internal_package_uninstallResult_cb_callback_type), offsetof(system_internal_package_UninstallInfo, result), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_internal_package_UninstallInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_internal_package_UninstallInfo) },
    .members = system_internal_package_UninstallInfo_struct_members
};

system_internal_package_UninstallInfo* system_internal_packageMallocUninstallInfo () {
    return (system_internal_package_UninstallInfo*)FeatureMalloc(
        sizeof(system_internal_package_UninstallInfo), FT_MK_COMPLEX(&system_internal_package_UninstallInfo_struct_type));
}


/****** for JIDL function 'getAllPackageInfo' ******/
static const FeatureType system_internal_package_getAllPackageInfo_parameters[] = {
    FT_PARAM_END
};

static const ArrayType system_internal_package_string_array = {
    .header = { .type = COMPLEX_ARRAY, .size = sizeof(FtArray) },
    .element_type = FT_STRING
};

FtArray* system_internal_package_malloc_string_array() {
    return (FtArray*)FeatureMalloc(
        sizeof(FtArray), FT_MK_COMPLEX(&system_internal_package_string_array));
}

static const MemberMethod system_internal_package_getAllPackageInfo_member_method = {
    .func = { .callback = FFI_FN(system_internal_package_wrap_getAllPackageInfo) },
    .parameters = system_internal_package_getAllPackageInfo_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_internal_package_string_array),
};


/****** for JIDL function 'getPackageInfo' ******/
static const FeatureType system_internal_package_getPackageInfo_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_internal_package_getPackageInfo_member_method = {
    .func = { .callback = FFI_FN(system_internal_package_wrap_getPackageInfo) },
    .parameters = system_internal_package_getPackageInfo_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_internal_package_PackageInfo_struct_type),
};


/****** for JIDL function 'clearAppCache' ******/
static const FeatureType system_internal_package_clearAppCache_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_internal_package_clearAppCache_member_method = {
    .func = { .callback = FFI_FN(system_internal_package_wrap_clearAppCache) },
    .parameters = system_internal_package_clearAppCache_parameters,
    .return_type = FT_INT,
};


/****** for JIDL function 'installPackage' ******/
static const FeatureType system_internal_package_installPackage_parameters[] = {
    FT_MK_COMPLEX_REF(&system_internal_package_InstallInfo_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_internal_package_installPackage_member_method = {
    .func = { .callback = FFI_FN(system_internal_package_wrap_installPackage) },
    .parameters = system_internal_package_installPackage_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'uninstallPackage' ******/
static const FeatureType system_internal_package_uninstallPackage_parameters[] = {
    FT_MK_COMPLEX_REF(&system_internal_package_UninstallInfo_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_internal_package_uninstallPackage_member_method = {
    .func = { .callback = FFI_FN(system_internal_package_wrap_uninstallPackage) },
    .parameters = system_internal_package_uninstallPackage_parameters,
    .return_type = FT_VOID,
};


// members
static const Member system_internal_package_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "getAllPackageInfo",
        .method = system_internal_package_getAllPackageInfo_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getPackageInfo",
        .method = system_internal_package_getPackageInfo_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "clearAppCache",
        .method = system_internal_package_clearAppCache_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "installPackage",
        .method = system_internal_package_installPackage_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "uninstallPackage",
        .method = system_internal_package_uninstallPackage_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_internal_package_callbacks {
    system_internal_package_onRegister,
    system_internal_package_onCreate,
    system_internal_package_onRequired,
    system_internal_package_onDetached,
    system_internal_package_onDestroy,
    system_internal_package_onUnregister
};

static const FeatureDescription system_internal_package_desc = {
    .version = 1,
    .name = "system.internal.package",
    .description = "system.internal.package",
    { .dynamic = false },
    .native_callbacks = &system_internal_package_callbacks,
    .member_count = countof(system_internal_package_members),
    .members = system_internal_package_members,
};

QAPPFEATURE_INIT(system_internal_package)
{
    return mgr->registerFeature(features, &system_internal_package_desc);
}
/* clang-format on */
