/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#include "power.h"
#include "sys/boardctl.h"

static const char* file_tag = "[jidl_feature] power_impl";

void system_internal_power_onRegister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_onUnregister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_internal_power_wrap_shutDown(FeatureInstanceHandle feature, AppendData append_data, system_internal_power_RetStatus* status)
{
    int ret = boardctl(BOARDIOC_POWEROFF, 0);
    if (!status) {
        FEATURE_LOG_ERROR("no status arg!\n");
        return;
    }
    if (!ret) {
        if (FeatureCheckCallbackId(feature, status->success)) {
            FeatureInvokeCallback(feature, status->success, "0");
        }
    } else {
        if (FeatureCheckCallbackId(feature, status->fail)) {
            FeatureInvokeCallback(feature, status->fail, "fail", ret);
        }
    }
    if (FeatureCheckCallbackId(feature, status->complete)) {
        FeatureInvokeCallback(feature, status->complete, (ret == 0) ? "success" : "fail");
    }

    FeatureRemoveCallback(feature, status->success);
    FeatureRemoveCallback(feature, status->fail);
    FeatureRemoveCallback(feature, status->complete);
}

void system_internal_power_wrap_reboot(FeatureInstanceHandle feature, AppendData append_data, system_internal_power_RetStatus* status)
{
    int ret = boardctl(BOARDIOC_RESET, 0);
    if (!status) {
        FEATURE_LOG_ERROR("no status arg!\n");
        return;
    }
    if (!ret) {
        if (FeatureCheckCallbackId(feature, status->success)) {
            FeatureInvokeCallback(feature, status->success, "0");
        }
    } else {
        if (FeatureCheckCallbackId(feature, status->fail)) {
            FeatureInvokeCallback(feature, status->fail, "fail", ret);
        }
    }
    if (FeatureCheckCallbackId(feature, status->complete)) {
        FeatureInvokeCallback(feature, status->complete, (ret == 0) ? "success" : "fail");
    }

    FeatureRemoveCallback(feature, status->success);
    FeatureRemoveCallback(feature, status->fail);
    FeatureRemoveCallback(feature, status->complete);
}