/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_PROMPT_H_
#define JSON_AST_GEN_MODULE_SYSTEM_PROMPT_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_prompt_onRegister(const char* feature_name);
void system_prompt_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_prompt_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_prompt_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_prompt_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_prompt_onUnregister(const char* feature_name);

// Struct defines
typedef struct _SuccessInfo {
  FtInt index;
} system_prompt_SuccessInfo;

system_prompt_SuccessInfo* system_promptMallocSuccessInfo();

typedef struct _ToastInfo {
  FtString message;
  FtInt duration;
} system_prompt_ToastInfo;

system_prompt_ToastInfo* system_promptMallocToastInfo();

typedef struct _button {
  FtString text;
  FtString color;
} system_prompt_button;

system_prompt_button* system_promptMallocbutton();

typedef struct _DialogInfo {
  FtString title;
  FtString message;
  FtArray* buttons;
  FtBool autocancel;
  FtCallbackId success;
  FtCallbackId cancel;
  FtCallbackId complete;
} system_prompt_DialogInfo;

system_prompt_DialogInfo* system_promptMallocDialogInfo();


// Function wrappers to be implemented
void system_prompt_wrap_showToast(FeatureInstanceHandle feature, AppendData append_data, system_prompt_ToastInfo * info);
void system_prompt_wrap_showDialog(FeatureInstanceHandle feature, AppendData append_data, system_prompt_DialogInfo * info);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions
FtArray* system_prompt_malloc_button_struct_type_array();

#endif // JSON_AST_GEN_MODULE_SYSTEM_PROMPT_H_
/* clang-format on */
