/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "prompt.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'SuccessInfo' ******/
static ObjectMember system_prompt_SuccessInfo_struct_members[] = {
    { "index", FT_INT, offsetof(system_prompt_SuccessInfo, index), sizeof(FtInt) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_prompt_SuccessInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_prompt_SuccessInfo) },
    .members = system_prompt_SuccessInfo_struct_members
};

system_prompt_SuccessInfo* system_promptMallocSuccessInfo () {
    return (system_prompt_SuccessInfo*)FeatureMalloc(
        sizeof(system_prompt_SuccessInfo), FT_MK_COMPLEX(&system_prompt_SuccessInfo_struct_type));
}


/****** for JIDL callback 'success_cb' ******/
static const FeatureType system_prompt_success_cb_parameters[] = {
    FT_MK_COMPLEX_REF(&system_prompt_SuccessInfo_struct_type),
    FT_PARAM_END
};

static const CallbackType system_prompt_success_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_prompt_success_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'cancel_cb' ******/
static const FeatureType system_prompt_cancel_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_prompt_cancel_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_prompt_cancel_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_prompt_complete_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_prompt_complete_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_prompt_complete_cb_parameters,
    .return_type = FT_VOID
};


static OptionalType system_prompt_ToastInfo_member_duration_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 0
};

/****** for JIDL struct 'ToastInfo' ******/
static ObjectMember system_prompt_ToastInfo_struct_members[] = {
    { "message", FT_STRING, offsetof(system_prompt_ToastInfo, message), sizeof(FtString) },
    { "duration", FT_MK_OPTIONAL(&system_prompt_ToastInfo_member_duration_opt_type), offsetof(system_prompt_ToastInfo, duration), sizeof(FtInt) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_prompt_ToastInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_prompt_ToastInfo) },
    .members = system_prompt_ToastInfo_struct_members
};

system_prompt_ToastInfo* system_promptMallocToastInfo () {
    return (system_prompt_ToastInfo*)FeatureMalloc(
        sizeof(system_prompt_ToastInfo), FT_MK_COMPLEX(&system_prompt_ToastInfo_struct_type));
}


/****** for JIDL struct 'button' ******/
static ObjectMember system_prompt_button_struct_members[] = {
    { "text", FT_STRING, offsetof(system_prompt_button, text), sizeof(FtString) },
    { "color", FT_STRING, offsetof(system_prompt_button, color), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_prompt_button_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_prompt_button) },
    .members = system_prompt_button_struct_members
};

system_prompt_button* system_promptMallocbutton () {
    return (system_prompt_button*)FeatureMalloc(
        sizeof(system_prompt_button), FT_MK_COMPLEX(&system_prompt_button_struct_type));
}


static const ArrayType system_prompt_button_struct_type_array = {
    .header = { .type = COMPLEX_ARRAY, .size = sizeof(FtArray) },
    .element_type = FT_MK_COMPLEX_REF(&system_prompt_button_struct_type)
};

FtArray* system_prompt_malloc_button_struct_type_array() {
    return (FtArray*)FeatureMalloc(
        sizeof(FtArray), FT_MK_COMPLEX(&system_prompt_button_struct_type_array));
}

static OptionalType system_prompt_DialogInfo_member_autocancel_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_BOOLEAN,
    .ival = true
};

/****** for JIDL struct 'DialogInfo' ******/
static ObjectMember system_prompt_DialogInfo_struct_members[] = {
    { "title", FT_STRING, offsetof(system_prompt_DialogInfo, title), sizeof(FtString) },
    { "message", FT_STRING, offsetof(system_prompt_DialogInfo, message), sizeof(FtString) },
    { "buttons", FT_MK_COMPLEX_REF(&system_prompt_button_struct_type_array), offsetof(system_prompt_DialogInfo, buttons), sizeof(FtArray*) },
    { "autocancel", FT_MK_OPTIONAL(&system_prompt_DialogInfo_member_autocancel_opt_type), offsetof(system_prompt_DialogInfo, autocancel), sizeof(FtBool) },
    { "success", FT_MK_COMPLEX(&system_prompt_success_cb_callback_type), offsetof(system_prompt_DialogInfo, success), sizeof(FtCallbackId) },
    { "cancel", FT_MK_COMPLEX(&system_prompt_cancel_cb_callback_type), offsetof(system_prompt_DialogInfo, cancel), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_prompt_complete_cb_callback_type), offsetof(system_prompt_DialogInfo, complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_prompt_DialogInfo_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_prompt_DialogInfo) },
    .members = system_prompt_DialogInfo_struct_members
};

system_prompt_DialogInfo* system_promptMallocDialogInfo () {
    return (system_prompt_DialogInfo*)FeatureMalloc(
        sizeof(system_prompt_DialogInfo), FT_MK_COMPLEX(&system_prompt_DialogInfo_struct_type));
}


/****** for JIDL function 'showToast' ******/
static const FeatureType system_prompt_showToast_parameters[] = {
    FT_MK_COMPLEX_REF(&system_prompt_ToastInfo_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_prompt_showToast_member_method = {
    .func = { .callback = FFI_FN(system_prompt_wrap_showToast) },
    .parameters = system_prompt_showToast_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'showDialog' ******/
static const FeatureType system_prompt_showDialog_parameters[] = {
    FT_MK_COMPLEX_REF(&system_prompt_DialogInfo_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_prompt_showDialog_member_method = {
    .func = { .callback = FFI_FN(system_prompt_wrap_showDialog) },
    .parameters = system_prompt_showDialog_parameters,
    .return_type = FT_VOID,
};


// members
static const Member system_prompt_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "showToast",
        .method = system_prompt_showToast_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "showDialog",
        .method = system_prompt_showDialog_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_prompt_callbacks {
    system_prompt_onRegister,
    system_prompt_onCreate,
    system_prompt_onRequired,
    system_prompt_onDetached,
    system_prompt_onDestroy,
    system_prompt_onUnregister
};

static const FeatureDescription system_prompt_desc = {
    .version = 1,
    .name = "system.prompt",
    .description = "system.prompt",
    { .dynamic = false },
    .native_callbacks = &system_prompt_callbacks,
    .member_count = countof(system_prompt_members),
    .members = system_prompt_members,
};

QAPPFEATURE_INIT(system_prompt)
{
    return mgr->registerFeature(features, &system_prompt_desc);
}
/* clang-format on */
