/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_REQUEST_H_
#define JSON_AST_GEN_MODULE_SYSTEM_REQUEST_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_request_onRegister(const char* feature_name);
void system_request_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_request_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_request_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_request_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_request_onUnregister(const char* feature_name);

// Struct defines
typedef struct _notify_data_t {
  FtInt result;
  FtInt percent;
} system_request_notify_data_t;

system_request_notify_data_t* system_requestMallocnotify_data_t();

typedef struct _download_succ_t {
  FtString token;
} system_request_download_succ_t;

system_request_download_succ_t* system_requestMallocdownload_succ_t();

typedef struct _download_t {
  FtString url;
  FtAny header;
  FtAny filename;
  FtBool share;
  FtCallbackId onDownLoadNotify;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_request_download_t;

system_request_download_t* system_requestMallocdownload_t();

typedef struct _dl_cmpl_succ_t {
  FtString uri;
} system_request_dl_cmpl_succ_t;

system_request_dl_cmpl_succ_t* system_requestMallocdl_cmpl_succ_t();

typedef struct _dl_cmpl_t {
  FtString token;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_request_dl_cmpl_t;

system_request_dl_cmpl_t* system_requestMallocdl_cmpl_t();


// Function wrappers to be implemented
void system_request_wrap_download(FeatureInstanceHandle feature, AppendData append_data, system_request_download_t * param);
void system_request_wrap_onDownloadComplete(FeatureInstanceHandle feature, AppendData append_data, system_request_dl_cmpl_t * param);
void system_request_wrap_print(FeatureInstanceHandle feature, AppendData append_data, FtVariParams vari_params);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_REQUEST_H_
/* clang-format on */
