/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_STORAGE_H_
#define JSON_AST_GEN_MODULE_SYSTEM_STORAGE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_storage_onRegister(const char* feature_name);
void system_storage_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_storage_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_storage_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_storage_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_storage_onUnregister(const char* feature_name);

// Struct defines
typedef struct _GetInfo {
  FtString key;
  FtString _default;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_storage_GetInfo;

system_storage_GetInfo* system_storageMallocGetInfo();

typedef struct _SetInfo {
  FtString key;
  FtString value;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_storage_SetInfo;

system_storage_SetInfo* system_storageMallocSetInfo();

typedef struct _ClearInfo {
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_storage_ClearInfo;

system_storage_ClearInfo* system_storageMallocClearInfo();

typedef struct _DeleteInfo {
  FtString key;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_storage_DeleteInfo;

system_storage_DeleteInfo* system_storageMallocDeleteInfo();

typedef struct _KeyInfo {
  FtInt index;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_storage_KeyInfo;

system_storage_KeyInfo* system_storageMallocKeyInfo();


// Function wrappers to be implemented
void system_storage_wrap_get(FeatureInstanceHandle feature, AppendData append_data, system_storage_GetInfo * info);
void system_storage_wrap_set(FeatureInstanceHandle feature, AppendData append_data, system_storage_SetInfo * info);
void system_storage_wrap_clear(FeatureInstanceHandle feature, AppendData append_data, system_storage_ClearInfo * info);
void system_storage_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, system_storage_DeleteInfo * info);
void system_storage_wrap_key(FeatureInstanceHandle feature, AppendData append_data, system_storage_KeyInfo * info);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented
FtInt system_storage_get_length(void* feature, AppendData append_data);
void system_storage_set_length(void* feature, AppendData append_data, FtInt length);

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_STORAGE_H_
/* clang-format on */
