/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_STORAGE_H_
#define JSON_AST_GEN_MODULE_STORAGE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void storage_onRegister(const char* feature_name);
void storage_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void storage_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void storage_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void storage_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void storage_onUnregister(const char* feature_name);

// Struct defines
typedef struct _GetInfo {
  FtString _key;
  FtString _default;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} storage_GetInfo;

storage_GetInfo* storageMallocGetInfo();

typedef struct _SetInfo {
  FtString _key;
  FtString _value;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} storage_SetInfo;

storage_SetInfo* storageMallocSetInfo();

typedef struct _ClearInfo {
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} storage_ClearInfo;

storage_ClearInfo* storageMallocClearInfo();

typedef struct _DeleteInfo {
  FtString _key;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} storage_DeleteInfo;

storage_DeleteInfo* storageMallocDeleteInfo();

typedef struct _KeyInfo {
  FtInt _index;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} storage_KeyInfo;

storage_KeyInfo* storageMallocKeyInfo();


// Function wrappers to be implemented
void storage_wrap_get(FeatureInstanceHandle feature, AppendData append_data, storage_GetInfo * info);
void storage_wrap_set(FeatureInstanceHandle feature, AppendData append_data, storage_SetInfo * info);
void storage_wrap_clear(FeatureInstanceHandle feature, AppendData append_data, storage_ClearInfo * info);
void storage_wrap_delete(FeatureInstanceHandle feature, AppendData append_data, storage_DeleteInfo * info);
void storage_wrap_key(FeatureInstanceHandle feature, AppendData append_data, storage_KeyInfo * info);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented
FtInt storage_get_length(void* feature, AppendData append_data);
void storage_set_length(void* feature, AppendData append_data, FtInt length);

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_STORAGE_H_
/* clang-format on */