cargo-features = ["path-bases"]

[package]
name = "system_network"
version.workspace = true
edition.workspace = true

[lib]
name = "system_network"

[dependencies]
libc = { workspace = true }
feature_macros = { workspace = true }
feature_frm = { workspace = true }
async-trait = { workspace = true }
vdk = { workspace = true }
futures = { workspace = true }
