[workspace]
resolver = "2"
members = [
    "feature_sys",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 'z'

[workspace.dependencies]
feature_sys = { path = "feature_sys" }
libc = "0.2"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
tokio = "1"
once_cell = "1.18"
