[workspace]
resolver = "2"
members = [
    "macros",
    "feature_frm",
    "feature_frm/sys",
    "modules/simple",
    "modules/system_exchange",
    "modules/system_schedule",
    "modules/system_network",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 'z'

[workspace.dependencies]
feature_sys = { path = "feature_frm/sys" }
feature_macros = { path = "macros" }
feature_frm = { path = "feature_frm" }
vdk = { base = "runtime", path = "vdk-rs/vdk" }
libc = {version = "0.2", default-features = false}
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
async-trait = "0.1"
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
