/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "./examples/system_network.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
/* clang-format off */

use alloc::boxed::Box;
use alloc::sync::Arc;
use async_trait::async_trait;
use core::ffi::{c_void, CStr};
use core::ptr;
use feature_frm::*;
use feature_macros::feature_struct;
use vdk::async_runtime::runtime;

use crate::system_network_impl::{
    system_network_on_create, system_network_on_destroy, system_network_on_detached,
    system_network_on_register, system_network_on_required, system_network_on_unregister,
    SystemNetworkImpl, SystemNetworkPrototype,
};

// extern c functions imported to rust side
unsafe extern "C" {
    // complex types functions
    // for JIDL struct 'param'
    pub(crate) fn system_network_param_struct_get_type() -> FeatureType;
    // for JIDL struct 'typeResult'
    pub(crate) fn system_network_typeResult_struct_get_type() -> FeatureType;
    // for JIDL callback 'network_subscribe_cb'
    pub(crate) fn system_network_network_subscribe_cb_invoke(
        handle: FeatureInstanceHandle,
        cid: FtCallbackId,
        _type: *mut system_network_typeResult,
    ) -> FtBool;
    // for JIDL promise resolve type 'typeResult'
    pub(crate) fn system_network_typeResult_ptr_promise_resolve(
        handle: FeatureInstanceHandle,
        id: FtPromiseId,
        val: *mut system_network_typeResult,
    ) -> FtBool;

    // event emit functions

    // interface creation functions
}

// safe interface creation functions

// extern c data types imported to rust side
// for JIDL struct 'param'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "Param", with_instance = "true")]
pub struct system_network_param {
    callback: FtCallbackId,
}

impl Param {
    #[allow(dead_code)]
    pub fn new(inner: FeaturePtr<system_network_param>, instance: FeatureInstance) -> Self {
        Self { inner, instance }
    }

    #[allow(dead_code)]
    pub fn set_instance(&mut self, instance: FeatureInstance) {
        self.instance = instance
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_network_param {
        self.inner.as_ptr()
    }

    // member getters and setters
    // once the callback is taken out, the callback id will be invalid.
    pub(crate) fn take_callback(&mut self) -> Option<NetworkSubscribeCbCallback> {
        if FeatureCallback::is_valid_id(self.callback) {
            let ret = NetworkSubscribeCbCallback::new(self.callback, self.instance.clone());
            self.callback = FeatureCallback::invalid_id();
            Some(ret)
        } else {
            None
        }
    }
}

// for JIDL struct 'typeResult'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "TypeResult")]
pub struct system_network_typeResult {
    _type: FtString,
}

impl TypeResult {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_network_typeResult {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_type(&self) -> Option<FeatureString> {
        unsafe { FeatureString::from_raw(self._type) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_type(&mut self, _type: FeatureString) {
        if !self._type.is_null() {
            unsafe {
                FeatureFreeValue(self._type as *mut c_void);
            }
            self._type = ptr::null_mut();
        }
        self._type = _type.into_raw();
    }
}

// for JIDL callback 'network_subscribe_cb'
#[derive(Clone)]
pub(crate) struct NetworkSubscribeCbCallback {
    cb: Arc<FeatureCallback>,
}

impl NetworkSubscribeCbCallback {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtCallbackId, instance: FeatureInstance) -> Self {
        Self {
            cb: Arc::new(FeatureCallback::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn invoke(&self, result: TypeResult) {
        // must clone the Arc<FeatureCallback> and move it to the closure
        // to prevent the FeatureCallback from being dropped before the closure is called.
        let cb = self.cb.clone();

        unsafe {
            self.cb.post(move || {
                let _ = system_network_network_subscribe_cb_invoke(
                    cb.handle(),
                    cb.id(),
                    result.as_ptr(),
                );
            });
        }
    }
}

// for JIDL promise 'typeResult'
#[derive(Clone, Default)]
pub(crate) struct TypeResultPromise;
impl Promise for TypeResultPromise {
    type Output = TypeResult;

    fn resolve(&self, id: FtPromiseId, instance: &FeatureInstance, value: Self::Output) {
        unsafe {
            system_network_typeResult_ptr_promise_resolve(instance.as_handle(), id, value.as_ptr());
        }
    }
}

// feature trait

#[async_trait]
pub(crate) trait SystemNetwork: FeatureInstanceTrait + Send + Sync {
    async fn get_type(&mut self) -> Result<TypeResult, PromiseError>;
    async fn subscribe(&mut self, p: Option<Param>) -> Result<(), PromiseError>;
    fn unsubscribe(&mut self) -> ();
}

// interface traits

// rust functions exported to c side
// feature lifecycle functions
#[no_mangle]
pub(crate) extern "C" fn system_network_onRegister(feature_name: FtString) {
    let name = unsafe { CStr::from_ptr(feature_name) };
    let fname = FeatureString::new(name.to_str().unwrap_or(""));
    system_network_on_register(&fname);
}

#[no_mangle]
pub(crate) extern "C" fn system_network_onCreate(
    ctx: FeatureRuntimeContextHandle,
    handle: FeatureProtoHandle,
) {
    let proto = FeaturePrototype::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    let boxed = Box::new(SystemNetworkPrototype::new(proto.clone()));
    proto.attach(boxed);
    system_network_on_create(ctx, proto);
}

#[no_mangle]
pub(crate) extern "C" fn system_network_onRequired(
    ctx: FeatureRuntimeContextHandle,
    handle: FeatureInstanceHandle,
) {
    let instance = FeatureInstance::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    let boxed = Box::new(SystemNetworkImpl::new(instance.clone())) as Box<dyn SystemNetwork>;
    instance.attach(boxed);
    system_network_on_required(ctx, instance);
}

#[no_mangle]
pub(crate) extern "C" fn system_network_onDetached(
    ctx: FeatureRuntimeContextHandle,
    handle: FeatureInstanceHandle,
) {
    let instance = FeatureInstance::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    system_network_on_detached(ctx, instance.clone());
    let _: Option<Box<dyn SystemNetwork>> = instance.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_network_onDestroy(
    ctx: FeatureRuntimeContextHandle,
    handle: FeatureProtoHandle,
) {
    let proto = FeaturePrototype::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    system_network_on_destroy(ctx, proto.clone());
    let _: Option<Box<SystemNetworkPrototype>> = proto.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_network_onUnregister(feature_name: FtString) {
    let name = unsafe { CStr::from_ptr(feature_name) };
    let fname = FeatureString::new(name.to_str().unwrap_or(""));
    system_network_on_unregister(&fname);
}

// feature member functions

// for JIDL method 'getType'
#[no_mangle]
pub(crate) extern "C" fn system_network_wrap_getType(
    handle: FeatureInstanceHandle,
    _adata: AppendData,
    promise_id: FtPromiseId,
) {
    let system_network = unsafe {
        feature_glue::get_instance_data::<dyn SystemNetwork>(handle)
            .expect("Failed to get impl for 'SystemNetwork' trait")
    };
    let system_network = unsafe { &mut *system_network };

    let promise = unsafe { FeaturePromise::<TypeResultPromise>::new(promise_id, handle) };
    runtime::spawn(async move {
        match system_network.get_type().await {
            Ok(v) => promise.resolve(v),
            Err(e) => promise.reject(e),
        }
    });
}

// for JIDL method 'subscribe'
#[no_mangle]
pub(crate) extern "C" fn system_network_wrap_subscribe(
    handle: FeatureInstanceHandle,
    _adata: AppendData,
    promise_id: FtPromiseId,
    p: *mut system_network_param,
) {
    let system_network = unsafe {
        feature_glue::get_instance_data::<dyn SystemNetwork>(handle)
            .expect("Failed to get impl for 'SystemNetwork' trait")
    };
    let system_network = unsafe { &mut *system_network };
    let p =
        unsafe { FeaturePtr::from_raw(p) }.map(|ptr| Param::new(ptr, FeatureInstance::new(handle)));
    let promise = unsafe { FeaturePromise::<FtVoidPromise>::new(promise_id, handle) };
    runtime::spawn(async move {
        match system_network.subscribe(p).await {
            Ok(()) => promise.resolve(()),
            Err(e) => promise.reject(e),
        }
    });
}

// for JIDL method 'unsubscribe'
#[no_mangle]
pub(crate) extern "C" fn system_network_wrap_unsubscribe(
    handle: FeatureInstanceHandle,
    _adata: AppendData,
) {
    let system_network = unsafe {
        feature_glue::get_instance_data::<dyn SystemNetwork>(handle)
            .expect("Failed to get impl for 'SystemNetwork' trait")
    };
    let system_network = unsafe { &mut *system_network };

    system_network.unsubscribe();
}

/* clang-format on */
