/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
<%
  module = render.module
  module_name = render.GetModuleName()
  header_define = render.GenHeaderDefine()
  imports_head_list = render.GetImportsHeadList()
%>\
<%def name="GenInterfaceTargetVTableDefines(func_node, ctor_info)">\
<%
  identifier = func_node['identifier']
  func_def = render.GenerateFunctionDefine(func_node)
  ctor_target = ctor_info['target']
  ctor_interface = ctor_info['interface']
  final_vtable = render.GetFinalVTable(ctor_interface)
  parent_prefix = f"{ctor_interface}_interface_"
  item_prefix = f"{module_name}_{parent_prefix}{ctor_target}"
  dtor_def = f"void {item_prefix}_finalize(FeatureInterfaceHandle handle)"
%>\
// vtable functions for interface constructor function '${identifier}'
${dtor_def};
%for vtable_item in final_vtable:
<%
  item_name = vtable_item['name']
  item_type = vtable_item['type']
  item_params = vtable_item['params']
  item_ret_type = vtable_item['return_type']
  params = "FeatureInterfaceHandle handle, AppendData append_data"
  if item_params != '':
    params = f"{params}, {item_params}"
  func_def = f"{item_ret_type} {item_prefix}"
  if item_type == 0:
    func_def = f"{func_def}_{item_name}({params})"
  elif item_type == 1:
    func_def = f"{func_def}_get_{item_name}({params})"
  elif item_type == 2:
    func_def = f"{func_def}_set_{item_name}({params})"
%>\
${func_def};
%endfor

</%def>\
<%def name="GenFunctionDefine(func_node)">\
${render.GenerateFunctionDefine(func_node)};
</%def>\
<%def name="GenInterfaceCtorDefine(func_node)">\
${render.GenerateInterfaceCtorDefine(func_node)};
</%def>\
<%def name="GenInterfaceVTableDefines(inode)">\
<%
  iname = inode['name']
  final_vtable = render.GetFinalVTable(iname)
  vtable_struct = f"{module_name}_{iname}_interface_vtable"
%>\
// VTable defines for interface '${iname}'
typedef struct ${vtable_struct} {
    VTable base; // vtable base
%for vtable_item in final_vtable:
<%
  item_name = vtable_item['name']
  item_type = vtable_item['type']
  item_params = vtable_item['params']
  item_ret_type = vtable_item['return_type']
  params = "FeatureInterfaceHandle handle, AppendData append_data"
  if item_params != '':
    params = f"{params}, {item_params}"
  if item_type == 0:
    func_ptr = f"{item_ret_type} (*{item_name})({params})"
  elif item_type == 1:
    func_ptr = f"{item_ret_type} (*get_{item_name})({params})"
  elif item_type == 2:
    func_ptr = f"{item_ret_type} (*set_{item_name})({params})"
%>\
    ${func_ptr};
%endfor
} ${vtable_struct};

FeatureInterfaceHandle ${module_name}_${iname}_create(
        FeatureInstanceHandle handle, ${vtable_struct}* vtable, void* data);

</%def>\
<%def name="GenPropertyDefines(prop_node)">\
<%
  prop_name = prop_node["name"]
  prop_type = prop_node["value_type"]
  has_getter = render.PropertyHasGetter(prop_node)
  has_setter = render.PropertyHasSetter(prop_node)
  cpp_type = render.GenerateCppType(prop_type)
  if has_getter:
    getter_def = f"{cpp_type} {module_name}_get_{prop_name}(FeatureInstanceHandle feature, AppendData append_data)"
  if has_setter:
    setter_def = f"void {module_name}_set_{prop_name}(FeatureInstanceHandle feature, AppendData append_data, {cpp_type} {prop_name})"
%>\
%if has_getter:
${getter_def};
%endif
%if has_setter:
${setter_def};
%endif
</%def>\
<%def name="GenStructMember(member_node)">\
<%
  member_name = render.toMemberName(member_node['name'])
  member_type = member_node['type']
  cpp_type = render.GenerateCppType(member_type)
  member_def = f"{cpp_type} {member_name}"
%>\
${member_def};
</%def>\
<%def name="GenStructDefine(struct_node)">\
<%
  struct_name = struct_node['name']
  for member in struct_node['members']:
    if render.IsStruct(member['type']):
      GenStructDefine(member['type'])
%>\
typedef struct _${module_name}_${struct_name} ${module_name}_${struct_name};

struct _${module_name}_${struct_name} {
%for member in struct_node['members']:
  ${GenStructMember(member)}\
%endfor
};

${module_name}_${struct_name}* ${module_name}Malloc${struct_name}(void);

</%def>\
<%def name="GenArrayMallocFuncDefines()">\
<%
  malloc_defines = render.GetArrayMallocFuncDefines()
%>\
%for malloc_def in malloc_defines:
${malloc_def};
%endfor
</%def>\
<%def name="GenCallbackHelper(cb_node)">\
<%
  identifier = cb_node['identifier']
  success = render.HasCallbackId(identifier)
  has_params = 'params' in cb_node
  has_ellipse = False
  if has_params:
    params_str = render.GenerateParamsStr(cb_node["params"])
    has_ellipse = render.HasEllipseParam(cb_node["params"])
    if not has_ellipse:
      param_values = render.GenerateParamValuesStr(cb_node["params"])
  success = success and not has_ellipse
%>\
%if success:
// for JIDL callback '${identifier}'
static inline int ${module_name}_${identifier}_invoke(FeatureInstanceHandle handle, FtCallbackId callback_id
%if has_params:
        , ${params_str}
%endif
        )
{
    return FeatureInvokeCallback(handle, callback_id
%if has_params:
        , ${param_values}
%endif
    );
}

%endif
</%def>\
#ifndef ${header_define}
#define ${header_define}

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

%if imports_head_list:
%for h in imports_head_list:
#include "${h}"
%endfor
%endif

// FeatureCallbacks to be implemented
void ${module_name}_onRegister(const char* feature_name);
void ${module_name}_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void ${module_name}_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void ${module_name}_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void ${module_name}_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void ${module_name}_onUnregister(const char* feature_name);

// message defines
%if 'imports' in module:
%for imp in module['imports']:
%if 'type' in imp and imp['type'] == 'import_message':
%for msg in imp['message_list']:
typedef ${render.GetPbTypeName(msg['protobuf_name'])}* ${module_name}_${msg['message_name']}_p;
%endfor
%endif
%endfor
%endif

// Struct defines
%for block in module['members']:
%if block['type'] == 'struct':
${GenStructDefine(block)}\
%endif
%endfor

// Function wrappers to be implemented
%for block in module['members']:
%if block['type'] == 'function':
${GenFunctionDefine(block)}\
%endif
%endfor

// Interface constructors
%for block in module['members']:
<%
  ctor_info = render.GetInterfaceCtorInfo(block)
%>\
%if block['type'] == 'function' and ctor_info:
${GenInterfaceCtorDefine(block)}\
%endif
%endfor

// interface vtable functions to be implemented
%for block in module['members']:
<%
  ctor_info = render.GetInterfaceCtorInfo(block)
%>\
%if ctor_info:
${GenInterfaceTargetVTableDefines(block, ctor_info)}\
%endif
%endfor

// Property getters and setters to be implemented
%for block in module['members']:
%if block['type'] == 'property':
${GenPropertyDefines(block)}\
%endif
%endfor

// Array malloc functions
${GenArrayMallocFuncDefines()}

%for block in module['members']:
%if block['type'] == 'interface':
${GenInterfaceVTableDefines(block)}\
%endif
%endfor

// Callback helpers
%for block in module['members']:
%if block['type'] == 'callback':
${GenCallbackHelper(block)}\
%endif
%endfor

/*********** begin get the user defined type ************/
%for name,tp in render.user_types_map.items():
%if tp['type'] in ['struct', 'array', 'callback', 'interface']:
const FeatureType ${module_name}_get_${name}(void);
%endif
%endfor
/*********** end get the user defined type *************/



#endif // ${header_define}
/* clang-format on */
