/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2024 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
<%
  module = render.module
  module_name = render.GetModuleName()
  header_define = render.GenHeaderDefine()
  imports_head_list = render.GetImportsHeadList()
  module_namespace = 'ft_wrap'
  if 'namespace' in render.configs:
    module_namespace = render.configs['namespace']
%>\
<%def name="GenFunctionDefine(func)">\
<%
  name = func['identifier']
  ret_type = render.GenerateReturnType(func['return_type'])
  if 'params' in func:
    params = render.GenerateParamListData(func['params'])
  else:
    params = []
  has_promise = False
  if ret_type == 'FtPromiseId':
      ret_type = 'void'
      has_promise = True
      params.insert(0, "FtPromiseId promise_id")

%>
  virtual ${ret_type} ${name}(${','.join(params)}) = 0;
</%def>\
<%def name="GenPropertyDefines(prop_node)">\
<%
  prop_name = prop_node["name"]
  prop_type = prop_node["value_type"]
  has_getter = render.PropertyHasGetter(prop_node)
  has_setter = render.PropertyHasSetter(prop_node)
  cpp_type = render.GenerateCppType(prop_type)
%>
%if has_getter:
  virtual ${cpp_type} get_${prop_name}() = 0;
%endif
%if has_setter:
  virtual void set_${prop_name}(${cpp_type} ${prop_name}) = 0;
%endif
</%def>\
<%def name="GenStructMemberGetSet(cpp_type, name, is_ref)">\
    inline ${cpp_type} get_${name}() { return ${name}; }
    inline void set_${name}(${cpp_type} val) {
%if is_ref:
       if (this->${name} != val)
          FeatureFreeValue(this->${name});
%endif
       this->${name} = val;
    }
%if is_ref:
    inline void set_${name}(const ft_utils::RefPtr<${cpp_type}>& val) {
       set_${name}(val.dup().drop());
    }
    inline void set_${name}(ft_utils::RefPtr<${cpp_type}>&& val) {
       set_${name}(val.drop());
   }
%endif
</%def>\
<%def name="GenStructMember(member_node)">\
<%
  member_name = member_node['name']
  member_type = member_node['type']
  cpp_type = render.GenerateCppType(member_type)
  is_ref = render.IsRefType(member_type)
%>\
  private: ${cpp_type} ${member_name}; 
  public: 
${GenStructMemberGetSet(cpp_type, member_name, is_ref)}
</%def>\
\
<%def name="GenStructDefine(struct_node)">\
<%
  struct_name = render.ToClassName(struct_node['name'])
%>\
class ${struct_name} {
  public: static ft_utils::RefPtr<${struct_name}> Create();
  public: static FeatureType GetFeatureType();
%for member in struct_node['members']:
${GenStructMember(member)}\
%endfor
  public: ~${struct_name}() {
    FeatureFreeValue(this);
  }
};

</%def>\
<%def name="GenEventDefine(event)">\
<%
   event_name = event['identifier']
   params = None
   param_names = None
   has_ellipse = False
   if 'params' in event:
       params_type = event['params']
       if len(params_type) > 0 and params_type[-1]['type'] == 'ellipse':
           has_ellipse = True
           params_type = params_type[:-1]
       params = render.GenerateParamListData(params_type)
       param_names = [p['name'] for p in params_type]
   if not params: params = []
   if not param_names : param_names = []
   if has_ellipse:
       params.append("const FtVariParams& __var_values__")
       param_names.append("__var_values__")
   param_names.insert(0, 'EVENT_%s_ID' % (event_name.upper()))
   param_names.insert(0, "getHandle()")
%>
#if 0
    void emit${render.ToClassName(event_name)}(${','.join(params)}) {
         FeatureEmitEvent(${','.join(param_names)});
    }
#endif
</%def>\
<%def name="GenArrayMallocFuncDefines()">\
<%
  malloc_defines = render.GetArrayMallocFuncDefines()
%>\
%for malloc_def in malloc_defines:
${malloc_def};
%endfor
</%def>\
\
<%def name="GenInterfaceClass(clazz, is_module)">\
<%
  base_name = render.ToClassName(clazz['name'])
  intf_name = is_module and base_name or 'I' + base_name
  members = clazz['members']
  extends = ''

  if is_module:
    extends = ': public ft_utils::FeatureInstance'
  elif 'extends' in clazz and len(clazz['extends']) > 0:
    extends = ': ' + ', '.join(['public I' + e for e in clazz['extends']])


%>
class ${intf_name} ${extends}
{
  public:
    virtual ~${intf_name}() {}
%if is_module:
    static ${intf_name}* Create(FeatureRuntimeContext ctx, FeatureInstanceHandle hInst);
%else:
    static FeatureInterfaceHandle Create(FeatureInstanceHandle hInst, ${intf_name}* intf);
%endif
    static ${intf_name}* From(FeatureInstanceHandle hInst);

  protected:
%for member in members:
%if member['type'] == 'function':
${GenFunctionDefine(member)}
%endif
%if member['type'] == 'property':
${GenPropertyDefines(member)}
%endif
%if member['type'] == 'event':
${GenEventDefine(member)}
%endif
%endfor
};
%if not is_module:
using ${base_name} = ft_utils::TFeatureInterface<${intf_name}>;
%endif
</%def>\
\
#ifndef ${header_define}
#define ${header_define}

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ft_utils.h"

%if imports_head_list:
%for h in imports_head_list:
#include "${h}"
%endfor
%endif

namespace ${module_namespace} {

// FeatureCallbacks to be implemented
void ${module_name}_onRegister(const char* feature_name);
void ${module_name}_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void ${module_name}_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void ${module_name}_onUnregister(const char* feature_name);

// message defines
%if 'imports' in module:
%for imp in module['imports']:
%if 'type' in imp and imp['type'] == 'import_message':
%for msg in imp['message_list']:
typedef ${render.GetPbTypeName(msg['protobuf_name'])}* ${module_name}_${msg['message_name']}_p;
%endfor
%endif
%endfor
%endif

// Struct defines
%for block in module['members']:
%if block['type'] == 'struct':
${GenStructDefine(block)}\
%endif
%endfor

// interface vtable functions to be implemented
%for block in module['members']:
%if block['type'] == 'interface':
${GenInterfaceClass(block, False)}
%endif
%endfor

${GenInterfaceClass(module, True)}

// Array malloc functions
${GenArrayMallocFuncDefines()}

} // namespace ${module_namespace}

#endif // ${header_define}
/* clang-format on */
