/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
<%
  module = render.module
  module_name = render.GetModuleName()
  raw_mod_name = render.GetRawModuleName()
  header_name = render.GetHeaderFileName()
%>\
<%def name="GenOptionalType(name, feature_type, ft_expr, value)">\
<%
  if value == 'null':
    value = 'NULL'
  val_name = render.GetOptValName(feature_type)
  value = render.GetOptVal(feature_type, value)
%>\
static OptionalType ${module_name}_${name}_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = ${ft_expr},
    .${val_name} = ${value}
};

</%def>\
<%def name="GenStructMemberItems(members, struct_name, member_items)">\
<%
  for member in members:
    member_item = {}
    member_item['name'] = render.toMemberName(member['name'])
    member_type = member['type']
    cpp_type = render.GenerateCppType(member_type)
    member_item['cpp_type'] = cpp_type

    m_info = render.GenerateFeatureInfo(member_type)
    ft_expr = render.GenerateFtExpression(m_info)
    if 'default' in member and 'name' in member:
      m_default = member['default']
      if m_info['is_complex'] and m_default != 'null':
        raise Exception('wrong default struct member type: {}'.format(m_info['type']))
      m_name = struct_name + '_member_' + member['name']
      GenOptionalType(m_name, m_info['type'], ft_expr, m_default)
      ft_expr = f"FT_MK_OPTIONAL(&{module_name}_{m_name}_opt_type)"
    member_item['ft_expr'] = ft_expr
    member_items.append(member_item)
%>\
</%def>\
<%def name="GenStruct(struct_node)">\
<%
  struct_name = struct_node['name']
  render.CacheStructName(struct_name)
%>\
/****** for JIDL struct '${struct_name}' ******/
extern const ObjectMapType ${module_name}_${struct_name}_struct_type;

<%
  for member in struct_node['members']:
    if render.IsStruct(member['type']):
      GenStruct(member['type'])
  member_items = []
  GenStructMemberItems(struct_node['members'], struct_name, member_items)
%>\
static ObjectMember ${module_name}_${struct_name}_struct_members[] = {
%for member_item in member_items:
<%
  member_name = member_item['name']
  member_ft = member_item['ft_expr']
  cpp_type = member_item['cpp_type']
%>\
    { "${member_name}", ${member_ft}, offsetof(${module_name}_${struct_name}, ${member_name}), sizeof(${cpp_type}) },
%endfor
    { NULL },
};

// complex defination
const ObjectMapType ${module_name}_${struct_name}_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(${module_name}_${struct_name}) },
    .members = ${module_name}_${struct_name}_struct_members
};

${module_name}_${struct_name}* ${module_name}Malloc${struct_name} () {
    return (${module_name}_${struct_name}*)FeatureMalloc(
        sizeof(${module_name}_${struct_name}), FT_MK_COMPLEX(&${module_name}_${struct_name}_struct_type));
}

</%def>\
<%def name="GenInterfaceMemberMethod(func_node, iname, index)">\
<%
  identifier = func_node['identifier']
  ret_type_node = func_node['return_type']
  iname_prefix = f"{iname}_interface_"
  ret_ft_info = render.GenerateReturnFtInfo(ret_type_node)
  ret_ft_expr = render.GenerateFtExpression(ret_ft_info)
  if isinstance(ret_type_node, dict) and ret_type_node['type'] == 'promise':
    GenPromiseFeatureType(ret_type_node, ret_ft_info['type'])

  ret_params = render.GenerateReturnParamsDefine(func_node, ret_type_node)
  ret_type = ret_params['ret_type']
  has_promise = False
  if ret_type == 'FtPromiseId':
    ret_type = 'void'
    has_promise = True
  params_def = ret_params['params_def']
  func_id = f"{module_name}_{iname_prefix}{identifier}"
  func_type = f"{func_id}_wrap_type"
  func_typedef = f"typedef {ret_type} (*{func_type})"
  func_typedef += f"(\n        {params_def})"
  call_args = render.GenerateWrapFuncCallArgs(func_node, ret_type_node)
  func_call = ''
  if not (has_promise or ret_type == 'void'):
    func_call += f"*(({ret_type}*)ret) = "
  func_call += "func"

  params_ft = f"{func_id}_parameters"
  member_info = render.GetMemberInfo(func_node)
  member_type = member_info['type']
  member_name = member_info['name']
  member_suffix = member_info['suffix']
  member_val_type = member_info['val_type']
  member_val = f"{iname_prefix}{member_name}{member_suffix}"
  member_info = {
    'iname': iname,
    'type': 0, # 0 for MemberMethod, 1 for MemberAccessor, 2 for MemberEvent
    'member_type': member_type,
    'member_name': member_name,
    'member_val_type': member_val_type,
    'member_val': member_val,
    'params_ft': params_ft,
    'ret_ft': ret_ft_expr,
    'func_type': func_type,
    'func_call': func_call,
    'call_args': call_args
  }
  render.CacheInterfaceMember(iname, member_info)
%>\
${func_typedef};

static void ${func_id}_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${func_type} func =
            (${func_type})FeatureGetInterfaceMember(handle, ${index});
    ${func_call}(handle, adata
%for call_arg in call_args:
        , ${call_arg}
%endfor
    );
}

static const MemberMethod ${module_name}_${member_val} = {
    .func_stub = ${func_id}_stub,
    .parameters = ${params_ft},
    .return_type = ${ret_ft_expr},
};
</%def>\
<%def name="GenInterfaceFunction(func_node, iname)">\
<%
  # for interface member method
  identifier = func_node['identifier']
  ret_type_node = func_node['return_type']
  iname_prefix = f"{iname}_interface_"

  index_offset = 0
  extends = render.GetInterfaceExtends(iname)
  for extend in extends:
    index_offset += render.GetFinalVTableSize(extend)
  index = render.CacheVTableItem(iname, func_node, 0)
  index += index_offset
%>\
// for member method '${identifier}'
${GenParamsFeatureType(func_node, iname_prefix)}
${GenInterfaceMemberMethod(func_node, iname, index)}
</%def>\
<%def name="GenInterfaceProperty(prop_node, iname)">\
<%
  prop_name = prop_node['name']
  value_type = prop_node['value_type']
  prop_info = render.GenerateFeatureInfo(value_type)
  prop_ft = render.GenerateFtExpression(prop_info)
  cpp_type = render.GenerateCppType(value_type)
  has_getter = render.PropertyHasGetter(prop_node)
  has_setter = render.PropertyHasSetter(prop_node)
  iname_prefix = f"{iname}_interface_"
  head_params = "void* feature, AppendData append_data"

  index_offset = 0
  extends = render.GetInterfaceExtends(iname)
  for extend in extends:
    index_offset += render.GetFinalVTableSize(extend)

  getter_idx = ''
  setter_idx = ''
  if has_getter:
    index = render.CacheVTableItem(iname, prop_node, 1)
    index += index_offset
    getter_idx = f"{index}"
    getter_name = f"{module_name}_{iname_prefix}get_{prop_name}"
    getter_stub_name = f"{getter_name}_stub"
    getter_type = f"{getter_name}_type"
    getter_typedef = f"typedef {cpp_type} (*{getter_type})"
    getter_typedef += f"(\n        {head_params})"
  if has_setter:
    index = render.CacheVTableItem(iname, prop_node, 2)
    index += index_offset
    setter_idx = f"{index}"
    setter_name = f"{module_name}_{iname_prefix}set_{prop_name}"
    setter_stub_name = f"{setter_name}_stub"
    setter_type = f"{setter_name}_type"
    setter_typedef = f"typedef void (*{setter_type})"
    setter_typedef += f"(\n        {head_params}, {cpp_type} {prop_name})"

  member_info = render.GetMemberInfo(prop_node)
  member_type = member_info['type']
  member_name = member_info['name']
  member_suffix = member_info['suffix']
  member_val_type = member_info['val_type']
  member_val = f"{iname_prefix}{member_name}{member_suffix}"
  member_info = {
    'iname': iname,
    'type': 1, # 0 for MemberMethod, 1 for MemberAccessor, 2 for MemberEvent
    'member_type': member_type,
    'member_name': member_name,
    'member_val_type': member_val_type,
    'member_val': member_val,
    'has_getter': has_getter,
    'has_setter': has_setter,
    'prop_ft': prop_ft,
    'prop_type': cpp_type
  }
  if has_getter:
    member_info['getter_type'] = getter_type
  if has_setter:
    member_info['setter_type'] = setter_type
  render.CacheInterfaceMember(iname, member_info)
%>\
// for member property '${prop_name}'
%if has_getter:
${getter_typedef};

static void ${getter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${getter_type} func =
            (${getter_type})FeatureGetInterfaceMember(handle, ${getter_idx});
    *((${cpp_type}*)ret) = func(handle, adata);
}

%endif
%if has_setter:
${setter_typedef};

static void ${setter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${setter_type} func =
            (${setter_type})FeatureGetInterfaceMember(handle, ${setter_idx});
    func(handle, adata, *(${cpp_type}*)(argv[0]));
}

%endif
static const MemberAccessor ${module_name}_${member_val} = {
%if has_getter:
    .getter_stub = ${getter_stub_name},
%endif
%if has_setter:
    .setter_stub = ${setter_stub_name},
%endif
    .type = ${prop_ft},
};

</%def>\
<%def name="GenInterfaceEvent(event_node, iname)">\
<%
  iname_prefix = f"{iname}_interface_"
  id = event_node['identifier']
  success = render.CheckInterfaceEventId(iname, id)
  if success:
    index_offset = 0
    extends = render.GetInterfaceExtends(iname)
    for extend in extends:
      index_offset += render.GetInterfaceFinalEventSize(extend)
    event_idx = render.CacheInterfaceEventId(iname, id)
    event_idx += index_offset
    member_event_val = f"{module_name}_{iname_prefix}{id}_member_event"
    member_event_prefix = f"{iname_prefix}event_"
    params_ft = f"{module_name}_{member_event_prefix}{id}_parameters"
    member_info = render.GetMemberInfo(event_node)
    member_type = member_info['type']
    member_name = member_info['name']
    member_suffix = member_info['suffix']
    member_val_type = member_info['val_type']
    member_val = f"{iname_prefix}{member_name}{member_suffix}"
    member_info = {
      'iname': iname,
      'type': 2, # 0 for MemberMethod, 1 for MemberAccessor, 2 for MemberEvent
      'member_type': member_type,
      'member_name': member_name,
      'member_val_type': member_val_type,
      'member_val': member_val,
      'params_ft': params_ft,
    }
    render.CacheInterfaceMember(iname, member_info)
%>\
%if success:
// for member event '${id}'
${GenParamsFeatureType(event_node, member_event_prefix)}
static const MemberEvent ${member_event_val} = {
    .parameters = ${params_ft},
    .id = ${event_idx},
    .name = "${id}",
};
%endif

</%def>\
<%def name="GenParentInterFaceMemberDefs(iname, parent_members)">\
<%
  vtable_idx = 0
  event_idx = 0
%>\
// Overrided parent member defines
%for member in parent_members:
<%
  parent_iname = member['iname']
  parent_iname_prefix = f"{parent_iname}_interface_"
  type = member['type']
  member_type = member['member_type']
  member_name = member['member_name']
  member_val_type = member['member_val_type']
  member_val = member['member_val']
  stub_name_prefix = f"{module_name}_{parent_iname_prefix}"
  if type == 0:
    # 0 for MemberMethod
    params_ft = member['params_ft']
    ret_ft = member['ret_ft']
    func_idx = vtable_idx
    vtable_idx += 1
    func_stub_name = f"{stub_name_prefix}{iname}_{member_name}_stub"
    func_type = member['func_type']
    func_call = member['func_call']
    call_args = member['call_args']
  elif type == 1:
    # 1 for MemberAccessor
    has_getter = member['has_getter']
    has_setter = member['has_setter']
    prop_ft = member['prop_ft']
    prop_type = member['prop_type']
    if has_getter:
      getter_idx = vtable_idx
      if has_setter:
        vtable_idx += 1
        setter_idx = vtable_idx
      vtable_idx += 1
    elif has_setter:
      setter_idx = vtable_idx
      vtable_idx += 1

    if has_getter:
      getter_type = member['getter_type']
      getter_stub_name = f"{stub_name_prefix}{iname}_get_{member_name}_stub"
    if has_setter:
      setter_type = member['setter_type']
      setter_stub_name = f"{stub_name_prefix}{iname}_set_{member_name}_stub"
  elif type == 2:
    # 2 for MemberEvent
    params_ft = member['params_ft']
    event_idx += 1
%>\
%if type == 0:
static void ${func_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${func_type} func =
            (${func_type})FeatureGetInterfaceMember(handle, ${func_idx});
    ${func_call}(handle, adata
%for call_arg in call_args:
        , ${call_arg}
%endfor
    );
}

static const MemberMethod ${module_name}_${iname}_${member_val} = {
    .func_stub = ${func_stub_name},
    .parameters = ${params_ft},
    .return_type = ${ret_ft},
};
%elif type == 1:
%if has_getter:
static void ${getter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${getter_type} func =
            (${getter_type})FeatureGetInterfaceMember(handle, ${getter_idx});
    *((${prop_type}*)ret) = func(handle, adata);
}
%endif
%if has_setter:
static void ${setter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${setter_type} func =
            (${setter_type})FeatureGetInterfaceMember(handle, ${setter_idx});
    func(handle, adata, *(${prop_type}*)(argv[0]));
}
%endif

static const MemberAccessor ${module_name}_${iname}_${member_val} = {
%if has_getter:
    .getter_stub = ${getter_stub_name},
%endif
%if has_setter:
    .setter_stub = ${setter_stub_name},
%endif
    .type = ${prop_ft},
};
%elif type == 2:
static const MemberEvent ${module_name}_${iname}_${member_val} = {
    .parameters = ${params_ft},
    .id = ${event_idx},
    .name = "${member_name}",
};
%endif

%endfor
</%def>\
<%def name="GenParentInterFaceMembers(iname, members)">\
  // overrided parent members
%for member in members:
<%
  type = member['type'] # 0 for MemberMethod, 1 for MemberAccessor
  member_type = member['member_type']
  member_name = member['member_name']
  member_val_type = member['member_val_type']
  member_val = member['member_val']
  member_val = f"&{module_name}_{iname}_{member_val}"
%>\
  {
      .type = ${member_type},
      .name = "${member_name}",
      .${member_val_type} = ${member_val},
  },
%endfor
</%def>\
<%def name="GenInterFaceMembers(iname, members)">\
%for member in members:
<%
  member_info = render.GetMemberInfo(member)
  member_type = member_info['type']
  member_name = member_info['name']
  member_suffix = member_info['suffix']
  member_val_type = member_info['val_type']
  iname_prefix = f"{iname}_interface_"
  member_val = f"&{module_name}_{iname_prefix}{member_name}{member_suffix}"
%>\
  {
      .type = ${member_type},
      .name = "${member_name}",
      .${member_val_type} = ${member_val},
  },
%endfor
</%def>\
<%def name="GenInterface(inode)">\
<%
  iname = inode['name']
  render.TryCacheInterface(iname)
  members = inode['members']
  for extend in inode['extends']:
    render.CacheInterfaceExtend(iname, extend)
  iname_prefix = f"{iname}_interface_"
  vtable_struct = f"{module_name}_{iname}_interface_vtable"
  parent_members = render.GetFinalInterfaceMembers(iname)
%>\
/****** JIDL interface '${iname}' glue code begin ******/
extern const InterfaceType ${module_name}_${iname_prefix}type;

%if parent_members:
${GenParentInterFaceMemberDefs(iname, parent_members)}\
%endif
<%
  for member in members:
    if member['type'] == 'function':
      GenInterfaceFunction(member, iname)
    elif member['type'] == 'property':
      GenInterfaceProperty(member, iname)
    elif member['type'] == 'event':
      GenInterfaceEvent(member, iname)
    else:
      raise Exception('wrong interface member type: {}'.format(member))
  endfor
%>\
// Interface members
static const Member ${module_name}_${iname_prefix}members[] = {
%if parent_members:
${GenParentInterFaceMembers(iname, parent_members)}\
%endif
  // ${iname} interface members
${GenInterFaceMembers(iname, members)}\
};

// Interface description
static const FeatureDescription ${module_name}_${iname_prefix}desc = {
    .version = 1,
    .name = "${iname}",
    .description = "${iname} description",
    .dynamic = true,
    .native_callbacks = NULL,
    .member_count = countof(${module_name}_${iname_prefix}members),
    .members = ${module_name}_${iname_prefix}members,
};

// InterfaceType
const InterfaceType ${module_name}_${iname_prefix}type = {
    .header = { .type = COMPLEX_INTERFACE, .size = 0 },
    .desc = &${module_name}_${iname_prefix}desc
};

// Interface creation
FeatureInterfaceHandle ${module_name}_${iname}_create(
        FeatureInstanceHandle handle, ${vtable_struct}* vtable, void* data) {
    if (vtable == NULL) {
        return NULL;
    }
    vtable->base.size = (sizeof(*vtable) - (sizeof(VTable))) / sizeof(void*);
    vtable->base.members = (const NativeFunc*)(&vtable->base + 1);
    FeatureInterfaceHandle hInterface = FeatureCreateInterface(handle, &(vtable->base));
    if (data) {
        FeatureSetObjectData(hInterface, data);
    }
    return hInterface;
}
/****** JIDL interface '${iname}' glue code end ******/
</%def>\

<%def name="GenerateArrayType(elem_type, is_complex)">\
static const ArrayType ${module_name}_${elem_type}_array = {
    .header = { .type = COMPLEX_ARRAY, .size = sizeof(FtArray) },
%if is_complex:
<% ft_expr = f"FT_MK_COMPLEX(&{module_name}_{elem_type})" %>\
    .element_type = ${ft_expr}
%else:
<% ft_type = render.ToBaseFeatureType(elem_type) %>\
    .element_type = ${ft_type}
%endif
};

FtArray* ${module_name}_malloc_${elem_type}_array() {
    return (FtArray*)FeatureMalloc(
        sizeof(FtArray), FT_MK_COMPLEX(&${module_name}_${elem_type}_array));
}

</%def>\
<%!
  class ArrayTypeGenerator:
    def __init__(self, gen_func):
      self.gen_func = gen_func

    def Generate(self, elem_type, is_complex):
      self.gen_func(elem_type, is_complex)
%>\
<%
  render.SetArrayTypeGenerator(ArrayTypeGenerator(GenerateArrayType))
%>\
<%def name="GenParamsFeatureType(node, iname_prefix)">\
<%
  if not iname_prefix: iname_prefix = ''
  identifier = node['identifier']
  has_ellipse = False
  ft_expr_list = []
  if 'params' in node:
    has_ellipse = render.HasEllipseParam(node['params'])
    for param in node['params']:
      p_info = render.GenerateFeatureInfo(param['type'])
      ft_expr = render.GenerateFtExpression(p_info)
      if 'name' in param and 'default' in param:
        p_default = param["default"]
        if p_info['is_complex'] and p_default != 'null':
          raise Exception('wrong default param type: {}'.format(p_info['type']))
        p_name = identifier + '_param_' + param["name"]
        GenOptionalType(p_name, p_info['type'], ft_expr, p_default)
        ft_expr = f"FT_MK_OPTIONAL(&{module_name}_{p_name}_opt_type)"
      ft_expr_list.append(ft_expr)
%>\
static const FeatureType ${module_name}_${iname_prefix}${identifier}_parameters[] = {
%for ft_expr in ft_expr_list:
    ${ft_expr},
%endfor
%if not has_ellipse:
    FT_PARAM_END
%endif
};
</%def>\
<%def name="GenPromiseFeatureType(promise_node, promise_ft)">\
<%
  resolve_type = promise_node['resolve_type']
  resolve_info = render.GenerateFeatureInfo(resolve_type)
  resolve_ft_expr = render.GenerateFtExpression(resolve_info)
  success = render.TryCachePromiseType(promise_ft)
%>\
%if success:
static const PromiseType ${module_name}_${promise_ft} = {
    .header = { .type = COMPLEX_PROMISE, .size = sizeof(FtPromiseId) },
    .resolveType = ${resolve_ft_expr}
};

%endif
</%def>\
<%def name="GenMemberMethod(func_node, ret_type_node)">\
<%
  identifier = func_node['identifier']
  ret_params = render.GenerateReturnParamsDefine(func_node, ret_type_node)
  ret_type = ret_params['ret_type']
  has_promise = False
  if ret_type == 'FtPromiseId':
    ret_type = 'void'
    has_promise = True
  params_def = ret_params['params_def']
  func_id = f"{module_name}_{identifier}"
  wrap_func = f"{module_name}_wrap_{identifier}"
  call_args = render.GenerateWrapFuncCallArgs(func_node, ret_type_node)
  func_call = ''
  if not (has_promise or ret_type == 'void'):
    func_call += f"*(({ret_type}*)ret) = "
  func_call += f"{wrap_func}"

  ret_ft_info = render.GenerateReturnFtInfo(ret_type_node)
  ret_ft_expr = render.GenerateFtExpression(ret_ft_info)
  if has_promise:
    GenPromiseFeatureType(ret_type_node, ret_ft_info['type'])

  permissions = None
  if 'meta' in func_node:
    meta = func_node['meta']
    if 'permissions' in meta:
      permissions = meta['permissions']
  if permissions:
    perm_bits = render.GetPermissionIds(permissions)
    low_bits = perm_bits['low_bits']
    high_bits = perm_bits['high_bits']
%>\
static void ${func_id}_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod ${func_id}_member_method = {
    .func_stub = ${func_id}_stub,
    .parameters = ${func_id}_parameters,
    .return_type = ${ret_ft_expr},
};

%if permissions:
static void ${func_id}_permissions_cb(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${func_call}(handle, adata
%for call_arg in call_args:
        , ${call_arg}
%endfor
    );
}
%endif

static void ${func_id}_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
%if permissions:
    static const FeaturePermissions ${func_id}_permissions = {
        ${low_bits},
        ${high_bits},
    };
    FeaturePermissionsRequestInfo request_info = {
      .adata = adata,
      .api_name = "${identifier}",
      .argv = argv,
      .argc = argc,
      .method = &${func_id}_member_method,
      .permissions = &${func_id}_permissions,
      .cb = ${func_id}_permissions_cb,
    };
    if (FeatureRequestPermissions(handle, &request_info))
        return;
%endif
    ${func_call}(handle, adata
%for call_arg in call_args:
        , ${call_arg}
%endfor
    );
}
</%def>\
<%def name="GenInterfaceCtorFunction(func_node, ctor_info)">\
<%
  identifier = func_node['identifier']
  func_def = render.GenerateInterfaceCtorDefine(func_node)
  ctor_target = ctor_info['target']
  ctor_interface = ctor_info['interface']
  iname_prefix = f"{module_name}_{ctor_interface}_interface"
  final_vtable = render.GetFinalVTable(ctor_interface)
  vtable_size = len(final_vtable)
  item_prefix = f"{iname_prefix}_{ctor_target}"
  finalizer = f"(NativeFunc){item_prefix}_finalize"
%>\
${func_def} {
    static ${iname_prefix}_vtable ${ctor_target}_vtable = {
        .base = { .finalizer = ${finalizer} },
%for vtable_item in final_vtable:
<%
  item_name = vtable_item['name']
  item_type = vtable_item['type']
  item_content = ''
  if item_type == 0:
    item_content = f".{item_name} = {item_prefix}_{item_name}"
  elif item_type == 1:
    item_content = f".get_{item_name} = {item_prefix}_get_{item_name}"
  elif item_type == 2:
    item_content = f".set_{item_name} = {item_prefix}_set_{item_name}"
%>\
%if item_content != '':
        ${item_content},
%endif
%endfor
    };

    return ${module_name}_${ctor_interface}_create(feature, &${ctor_target}_vtable, NULL);
}
</%def>\
<%def name="GenFunction(func_node)">\
<%
  identifier = func_node['identifier']
  ret_type_node = func_node['return_type']
  render.CacheFuncReturnNode(identifier, ret_type_node)
  # for interface constructor function
  ctor_info = render.GetInterfaceCtorInfo(func_node)
%>\
%if ctor_info:
/****** for JIDL Interface constructor function '${identifier}' ******/
${GenInterfaceCtorFunction(func_node, ctor_info)}
%endif
/****** for JIDL function '${identifier}' ******/
${GenParamsFeatureType(func_node, '')}
${GenMemberMethod(func_node, ret_type_node)}
</%def>\
<%def name="GenUse(use_node)">\
<%
  func_node = use_node['function']
  identifier = func_node['identifier']
  func_call_node = use_node['function_call']
  func_call_id = func_call_node['identifier']
  ret_type_node = render.GetUseReturnTypeNode(use_node)
  ret_type = render.GenerateReturnType(ret_type_node)
  is_promise = (ret_type == 'FtPromiseId')
  params = 'FeatureInstanceHandle feature, AppendData append_data'
  if is_promise:
    params += ', FtPromiseId pid'
    ret_type = 'void'
  if 'params' in func_node:
    params_str = render.GenerateParamsStr(func_node["params"])
    params += f", {params_str}"

  func_call = ''
  if ret_type != 'void':
    func_call += 'return '
  func_call += f"{module_name}_wrap_{func_call_id} (feature, append_data"
  if is_promise:
    func_call += ', pid'

  if 'param_calls' in func_call_node:
    params_call_list = render.GenerateParamCallList(func_call_node["param_calls"])
    func_call += f", {params_call_list}"
  func_call += ")"
%>\
/****** for JIDL use '${identifier}' ******/
static ${ret_type} ${module_name}_wrap_${identifier} (${params}) {
    ${func_call};
}

${GenParamsFeatureType(func_node, '')}
${GenMemberMethod(func_node, ret_type_node)}
</%def>\
<%def name="GenCallback(cb_node)">\
<%
  identifier = cb_node['identifier']
  success = render.TryCacheCallbackId(identifier)
%>\
%if success:
/****** for JIDL callback '${identifier}' ******/
${GenParamsFeatureType(cb_node, 'callback_')}
static const CallbackType ${module_name}_${identifier}_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = ${module_name}_callback_${identifier}_parameters,
    .return_type = FT_VOID
};

%endif
</%def>\
<%def name="GenEvent(ev_node)">\
<%
  identifier = ev_node['identifier']
  event_idx = render.TryCacheEventId(identifier)
  event_type = f"{module_name}_{identifier}_event_type"
%>\
%if event_idx > 0:
/****** for JIDL event '${identifier}' ******/
${GenParamsFeatureType(ev_node, 'event_')}

static const MemberEvent ${module_name}_${identifier}_member_event = {
    .parameters = ${module_name}_event_${identifier}_parameters,
    .id = ${event_idx},
    .name = "${identifier}",
};
%endif
</%def>\
<%def name="GenProperty(prop_node)">\
<%
  prop_name = prop_node['name']
  value_type = prop_node['value_type']
  prop_info = render.GenerateFeatureInfo(value_type)
  prop_ft = render.GenerateFtExpression(prop_info)
  has_getter = render.PropertyHasGetter(prop_node)
  has_setter = render.PropertyHasSetter(prop_node)
  cpp_type = render.GenerateCppType(value_type)
  head_params = "FeatureInstanceHandle feature, AppendData append_data"

  if has_getter:
    getter_name = f"{module_name}_get_{prop_name}"
    getter_idx = f".callback = (NativeFunc)({getter_name})"
    getter_stub_name = f"{getter_name}_stub"
  if has_setter:
    setter_name = f"{module_name}_set_{prop_name}"
    setter_stub_name = f"{setter_name}_stub"
%>\
/****** for JIDL property '${prop_name}' ******/
%if has_getter:
static void ${getter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    *((${cpp_type}*)ret) = ${getter_name}(handle, adata);
}

%endif
%if has_setter:
static void ${setter_stub_name}(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    ${setter_name}(handle, adata, *(${cpp_type}*)(argv[0]));
}

%endif
static const MemberAccessor ${module_name}_${prop_name}_member_accessor = {
%if has_getter:
    .getter_stub = ${getter_stub_name},
%endif
%if has_setter:
    .setter_stub = ${setter_stub_name},
%endif
    .type = ${prop_ft},
};

</%def>\
<%def name="GenConst(const_node, name_prefix)">\
<%
  if not name_prefix: name_prefix = ''
  const_name = const_node['name']
  const_value = const_node['value']
  const_type = const_node['value_type']
  const_info = render.GenerateFeatureInfo(const_type)
  if const_info['is_complex']:
    raise Exception('wrong const type: {}'.format(const_info['type']))
  val_name = render.GetAppendDataName(const_info['type'])
%>\
// for JIDL const '${name_prefix}${const_name}'
static const MemberConst ${module_name}_${name_prefix}${const_name}_member_const = {
    .type = ${const_info['type']},
    .func = { .callback = NULL },
    .data = { .${val_name} = ${const_value} }
};
</%def>\
<%def name="GenConstObject(co_node, name_prefix)">\
<%
  name = co_node['name']
  members = co_node['members']
  member_count = len(members)
  if not name_prefix:
    name_prefix = ''
  co_name = f"{name_prefix}{name}"
  name_prefix = f"{name_prefix}{name}_"
%>\
/****** begin JIDL const object '${co_name}' ******/
%for member in members:
%if member['type'] == 'const_object':
${GenConstObject(member, name_prefix)}\
%else:
${GenConst(member, name_prefix)}
%endif
%endfor
// const object members
static Member ${module_name}_${co_name}_const_object_members[] = {
${GenMembers(members, name_prefix)}\
    {
        .type = MEMBER_CONST,
        .name = NULL,
        .value = NULL,
    }
};

// const object
static const MemberConst ${module_name}_${co_name}_member_const_object = {
    .type = FT_ANY_REF,
    .func = { .callback = NULL },
    .data = { .ptr = ${module_name}_${co_name}_const_object_members }
};
/****** end JIDL const object '${co_name}' ******/

</%def>\
<%def name="GenMembers(members, name_prefix)">\
<%
  if not name_prefix: name_prefix = ''
%>\
%for member in members:
%if render.IsValidMemberType(member):
<%
  member_info = render.GetMemberInfo(member)
  member_type = member_info['type']
  member_name = member_info['name']
  member_suffix = member_info['suffix']
  member_val_type = member_info['val_type']
%>\
    {
        .type = ${member_type},
        .name = "${member_name}",
        .${member_val_type} = &${module_name}_${name_prefix}${member_name}${member_suffix},
    },
%endif
%endfor
</%def>\
\
<%def name="GenImportMessageType(msg)">
static ProtobufMessageType  ${module_name}_${msg['message_name']}_message_type = {
  .header = {
     .type = COMPLEX_PROTOBUF,
     .size = sizeof(ProtobufMessageType)
  },
  .desc = (const ProtobufCMessageDescriptor*)(&${render.GetPbVarName(msg['protobuf_name'])}__descriptor),
};
</%def>\
#include "${header_name}"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))
%if 'imports' in module:
%for imp in module['imports']:
%if 'type' in imp and imp['type'] == 'import_message':
%for msg in imp['message_list']:
${GenImportMessageType(msg)}
%endfor
%endif
%endfor
%endif

%for block in module['members']:
%if block['type'] == 'function':
${GenFunction(block)}
%elif block['type'] == 'use':
${GenUse(block)}
%elif block['type'] == 'callback':
${GenCallback(block)}
%elif block['type'] == 'event':
${GenEvent(block)}
%elif block['type'] == 'property':
${GenProperty(block)}
%elif block['type'] == 'const':
${GenConst(block, '')}
%elif block['type'] == 'const_object':
${GenConstObject(block, '')}
%elif block['type'] == 'struct':
${GenStruct(block)}
%elif block['type'] == 'interface':
${GenInterface(block)}
%endif
%endfor
// members
static const Member ${module_name}_members[] = {
${GenMembers(module['members'], '')}\
};

/*********** begin get the user defined type ************/
%for name,tp in render.user_types_map.items():
%if tp['type'] in ['struct', 'array', 'callback', 'interface']:
const FeatureType ${module_name}_get_${name}(void) {
   return FT_MK_COMPLEX(&${module_name}_${name});
}
%endif
%endfor
/*********** end get the user defined type *************/

// callbacks
static const struct FeatureCallbacks ${module_name}_callbacks = {
    ${module_name}_onRegister,
    ${module_name}_onCreate,
    ${module_name}_onRequired,
    ${module_name}_onDetached,
    ${module_name}_onDestroy,
    ${module_name}_onUnregister
};

static const FeatureDescription ${module_name}_desc = {
    .version = 1,
    .name = "${raw_mod_name}",
    .description = "${raw_mod_name}",
    .dynamic = false,
    .native_callbacks = &${module_name}_callbacks,
    .member_count = countof(${module_name}_members),
    .members = ${module_name}_members,
};

QAPPFEATURE_INIT(${module_name})
{
    return FeatureRegisterFeature(handle, &${module_name}_desc);
}
/* clang-format on */
