/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2024 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
<%
  module = render.module
  module_name_l = render.GetModuleName()
  module_name = render.ToClassName(module_name_l)
  header_define = render.GenHeaderDefine()
  imports_head_list = render.GetImportsHeadList()
  module_namespace = 'Feature_' + module_name
  if 'namespace' in render.configs:
    module_namespace = render.configs['namespace']
%>\
<%def name="GenFunctionDefine(func)">\
<%
  name = func['identifier']
  ret_type = render.GenerateReturnType(func['return_type'])
  if 'params' in func:
    params = render.GenerateParamList(func['params'])
  else:
    params = []
  has_promise = False
  if ret_type == 'FtPromiseId':
      ret_type = 'void'
      has_promise = True
      params.insert(0, "FtPromiseId promise_id")

%>
  virtual ${ret_type} ${name}(${','.join(params)}) = 0;
</%def>\
<%def name="GenPropertyDefines(prop_node)">\
<%
  prop_name = prop_node["name"]
  prop_type = prop_node["value_type"]
  has_getter = render.PropertyHasGetter(prop_node)
  has_setter = render.PropertyHasSetter(prop_node)
  cpp_type = render.GenerateCppType(prop_type)
  is_ref = render.IsRefType(prop_type)
%>
%if has_getter:
  virtual ${cpp_type} ${prop_name}() const = 0;
%endif
%if has_setter:
%if is_ref:
  virtual void set_${prop_name}(const ${cpp_type}& ${prop_name}) = 0;
%else:
  virtual void set_${prop_name}(${cpp_type} ${prop_name}) = 0;
%endif
%endif
</%def>\
<%def name="GenStructMemberGetSet(cpp_type, name, is_ref)">\
    inline ${cpp_type} ${name}() const { return data._${name}; }
%if is_ref:
    inline void set_${name}(const ${cpp_type}& val) { data._${name} = val; }
%else:
    inline void set_${name}(${cpp_type} val) { data._${name} = val; }
%endif
</%def>\
<%def name="GenStructMemberData(member_node)">\
<%
  member_name = member_node['name']
  member_type = member_node['type']
  cpp_type = render.GenerateCppType(member_type)
%>\
  ${cpp_type} _${member_name}; 
</%def>\
\
<%def name="GenStructDefine(struct_node)">\
<%
  struct_name = render.ToClassName(struct_node['name'])
%>\
struct ${struct_name}_Internal {
%for member in struct_node['members']:
${GenStructMemberData(member)}\
%endfor
};

class ${struct_name} {
private:
  ${struct_name}_Internal data;
public:
  static FeatureType getFeatureType();
public:
%for member in struct_node['members']:
<%
  member_name = member['name']
  member_type = member['type']
  cpp_type = render.GenerateCppType(member_type)
  is_ref = render.IsRefType(member_type)
%>\
${GenStructMemberGetSet(cpp_type, member_name, is_ref)}
%endfor
};

</%def>\
<%def name="GenEventDefine(event)">\
<%
   event_name = event['identifier']
   params = None
   param_names = None
   has_ellipse = False
   if 'params' in event:
       params_type = event['params']
       if len(params_type) > 0 and params_type[-1]['type'] == 'ellipse':
           has_ellipse = True
           params_type = params_type[:-1]
       params = render.GenerateParamList(params_type)
       param_names = [p['name'] for p in params_type]
   if not params: params = []
   if not param_names : param_names = []
   if has_ellipse:
       params.append("const FtVariParams& __var_values__")
       param_names.append("__var_values__")
   param_names.insert(0, 'EVENT_%s_ID' % (event_name.upper()))
   param_names.insert(0, "getHandle()")
%>
#if 0
    void emit${render.ToClassName(event_name)}(${','.join(params)}) {
         FeatureEmitEvent(${','.join(param_names)});
    }
#endif
</%def>\
<%def name="GenArrayMallocFuncDefines()">\
<%
  malloc_defines = render.GetArrayMallocFuncDefines()
%>\
%for malloc_def in malloc_defines:
${malloc_def};
%endfor
</%def>\
\
<%def name="GenInterfaceMembers(members)">\
<%
  for member in members:
    if member['type'] == 'function':
      GenFunctionDefine(member)
    if member['type'] == 'property':
      GenPropertyDefines(member)
    if member['type'] == 'event':
      GenEventDefine(member)
%>
</%def>\
<%def name="GenInterfaceClass(clazz, is_module, extendNodes)">\
<%
  base_name = render.ToClassName(clazz['name'])
  intf_name = is_module and base_name + "Base" or 'I' + base_name
  members = clazz['members']
  extends = ''

  if is_module:
    extends = ': public ft_utils::FeatureInstance'
  else:
    if 'extends' in clazz and len(clazz['extends']) > 0:
      extends = '/*: ' + ', '.join(['public I' + e for e in clazz['extends']]) + '*/'
    extends += ': public ft_utils::FeatureInstance'
%>
class ${intf_name} ${extends}
{
  public:
  explicit ${intf_name}(FeatureInstanceHandle hInstance)
    : ft_utils::FeatureInstance(hInstance){}
  virtual ~${intf_name}() = default;
%if isinstance(extendNodes, list):
%for extNode in extendNodes:
%if extNode:
// I${extNode['name']} functions
${GenInterfaceMembers(extNode['members'])}
%endif
%endfor
%endif
// self functions
${GenInterfaceMembers(members)}
};
</%def>\
\
#ifndef ${header_define}
#define ${header_define}

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "utils/feature_utils.h"

%if imports_head_list:
%for h in imports_head_list:
#include "${h}"
%endfor
%endif

namespace ${module_namespace} {

// FeatureCallbacks to be implemented
void onRegister(const char* feature_name);
void onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void onUnregister(const char* feature_name);

// message defines
%if 'imports' in module:
%for imp in module['imports']:
%if 'type' in imp and imp['type'] == 'import_message':
%for msg in imp['message_list']:
typedef ${render.GetPbTypeName(msg['protobuf_name'])}* ${render.ToClassName(msg['message_name'])}_p;
%endfor
%endif
%endfor
%endif

// Struct defines
%for block in module['members']:
%if block['type'] == 'struct':
${GenStructDefine(block)}\
%endif
%endfor

// interface vtable functions to be implemented
<%
moduleMembers = module['members']
for block in module['members']:
  if block['type'] == 'interface':
    extendsNodes = []
    if len(block['extends']):
      for extend in block['extends']:
        extendFound = False
        for item in moduleMembers:
          if item['type'] == 'interface' and item['name'] == extend:
            extendsNodes.append(item)
            extendFound = True
        if not extendFound:
          print("extend: ", extend, " not found !")
    GenInterfaceClass(block, False, extendsNodes)
%>
${GenInterfaceClass(module, True, [])}
## // Array malloc functions
## ${GenArrayMallocFuncDefines()}
} // namespace ${module_namespace}

#endif // ${header_define}
/* clang-format on */
