/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "./examples/system_media_audio.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
/* clang-format off */

use alloc::boxed::Box;
use alloc::sync::Arc;
use async_trait::async_trait;
use core::ffi::{c_void, CStr};
use core::ptr;
use feature_frm::*;
use feature_macros::feature_struct;
use vdk::async_runtime::runtime;

use crate::system_media_audio_impl::{
    system_media_audio_on_create, system_media_audio_on_destroy, system_media_audio_on_detached, system_media_audio_on_register,
    system_media_audio_on_required, system_media_audio_on_unregister, SystemMediaAudioImpl, SystemMediaAudioPrototype,
};

// extern c functions imported to rust side
unsafe extern "C" {
    // complex types functions
    // for JIDL struct 'CreatePlayerParams'
    pub(crate) fn system_media_audio_CreatePlayerParams_struct_get_type () -> FeatureType;
    // for JIDL struct 'CreateTrackParams'
    pub(crate) fn system_media_audio_CreateTrackParams_struct_get_type () -> FeatureType;
    // for JIDL struct 'PlayerSeekParams'
    pub(crate) fn system_media_audio_PlayerSeekParams_struct_get_type () -> FeatureType;
    // for JIDL struct 'interruptAction'
    pub(crate) fn system_media_audio_interruptAction_struct_get_type () -> FeatureType;
    // for JIDL struct 'RecorderStartParams'
    pub(crate) fn system_media_audio_RecorderStartParams_struct_get_type () -> FeatureType;
    // for JIDL struct 'CreateRecorderParams'
    pub(crate) fn system_media_audio_CreateRecorderParams_struct_get_type () -> FeatureType;
    // for JIDL struct 'TrackWriteParams'
    pub(crate) fn system_media_audio_TrackWriteParams_struct_get_type () -> FeatureType;

    // event emit functions
    // for JIDL event 'onreaddata'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onreaddata(handle: FeatureInstanceHandle, buffer: FtArrayBuffer);
    // for JIDL event 'onerror'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onerror(handle: FeatureInstanceHandle, data: FtString, code: FtInt);
    // for JIDL event 'onstart'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onstart(handle: FeatureInstanceHandle);
    // for JIDL event 'onpause'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onpause(handle: FeatureInstanceHandle);
    // for JIDL event 'onresume'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onresume(handle: FeatureInstanceHandle);
    // for JIDL event 'onstop'
    pub(crate) fn system_media_audio_AudioRecorder_emit_onstop(handle: FeatureInstanceHandle);
    // for JIDL event 'oninterrupt'
    pub(crate) fn system_media_audio_AudioRecorder_emit_oninterrupt(handle: FeatureInstanceHandle, action: *mut system_media_audio_interruptAction);

    // for JIDL event 'onplay'
    pub(crate) fn system_media_audio_AudioTrack_emit_onplay(handle: FeatureInstanceHandle);
    // for JIDL event 'onpause'
    pub(crate) fn system_media_audio_AudioTrack_emit_onpause(handle: FeatureInstanceHandle);
    // for JIDL event 'onstop'
    pub(crate) fn system_media_audio_AudioTrack_emit_onstop(handle: FeatureInstanceHandle);
    // for JIDL event 'onerror'
    pub(crate) fn system_media_audio_AudioTrack_emit_onerror(handle: FeatureInstanceHandle, data: FtString, code: FtInt);
    // for JIDL event 'oninterrupt'
    pub(crate) fn system_media_audio_AudioTrack_emit_oninterrupt(handle: FeatureInstanceHandle, action: *mut system_media_audio_interruptAction);

    // for JIDL event 'onplay'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onplay(handle: FeatureInstanceHandle);
    // for JIDL event 'onpause'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onpause(handle: FeatureInstanceHandle);
    // for JIDL event 'onstop'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onstop(handle: FeatureInstanceHandle);
    // for JIDL event 'onended'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onended(handle: FeatureInstanceHandle);
    // for JIDL event 'onerror'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onerror(handle: FeatureInstanceHandle, data: FtString, code: FtInt);
    // for JIDL event 'ontimeupdate'
    pub(crate) fn system_media_audio_AudioPlayer_emit_ontimeupdate(handle: FeatureInstanceHandle);
    // for JIDL event 'ondurationchange'
    pub(crate) fn system_media_audio_AudioPlayer_emit_ondurationchange(handle: FeatureInstanceHandle);
    // for JIDL event 'onloadeddata'
    pub(crate) fn system_media_audio_AudioPlayer_emit_onloadeddata(handle: FeatureInstanceHandle);
    // for JIDL event 'oninterrupt'
    pub(crate) fn system_media_audio_AudioPlayer_emit_oninterrupt(handle: FeatureInstanceHandle, action: *mut system_media_audio_interruptAction);


    // interface creation functions
    pub(crate) fn system_media_audio_createAudioPlayer_instance(feature: FeatureInstanceHandle) -> FeatureInterfaceHandle;
    pub(crate) fn system_media_audio_createAudioTrack_instance(feature: FeatureInstanceHandle) -> FeatureInterfaceHandle;
    pub(crate) fn system_media_audio_createAudioRecorder_instance(feature: FeatureInstanceHandle) -> FeatureInterfaceHandle;
}

// safe interface creation functions
pub(crate) fn create_audio_player_instance(instance: &FeatureInstance) -> FeatureInstance {
    let handle = unsafe { system_media_audio_createAudioPlayer_instance(instance.as_handle()) };
    let ret = FeatureInstance::new(handle);
    unsafe { FeatureFreeInstanceHandle(handle) };
    ret
}
pub(crate) fn create_audio_track_instance(instance: &FeatureInstance) -> FeatureInstance {
    let handle = unsafe { system_media_audio_createAudioTrack_instance(instance.as_handle()) };
    let ret = FeatureInstance::new(handle);
    unsafe { FeatureFreeInstanceHandle(handle) };
    ret
}
pub(crate) fn create_audio_recorder_instance(instance: &FeatureInstance) -> FeatureInstance {
    let handle = unsafe { system_media_audio_createAudioRecorder_instance(instance.as_handle()) };
    let ret = FeatureInstance::new(handle);
    unsafe { FeatureFreeInstanceHandle(handle) };
    ret
}

// extern c data types imported to rust side
// for JIDL struct 'CreatePlayerParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "CreatePlayerParams")]
pub struct system_media_audio_CreatePlayerParams {
    stream_type: FtString,
}

impl CreatePlayerParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_CreatePlayerParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_stream_type(&self) -> Option<FeatureString> {
        unsafe { FeatureString::from_raw(self.stream_type) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_stream_type(&mut self, stream_type: FeatureString) {
        if !self.stream_type.is_null() {
            unsafe {
                FeatureFreeValue(self.stream_type as *mut c_void);
            }
            self.stream_type = ptr::null_mut();
        }
        self.stream_type = stream_type.into_raw();
    }
}

// for JIDL struct 'CreateTrackParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "CreateTrackParams")]
pub struct system_media_audio_CreateTrackParams {
    stream_type: FtString,
    sample_rate_in_hz: FtInt,
    channel_config: FtInt,
    audio_format: FtInt,
}

impl CreateTrackParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_CreateTrackParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_stream_type(&self) -> Option<FeatureString> {
        unsafe { FeatureString::from_raw(self.stream_type) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_stream_type(&mut self, stream_type: FeatureString) {
        if !self.stream_type.is_null() {
            unsafe {
                FeatureFreeValue(self.stream_type as *mut c_void);
            }
            self.stream_type = ptr::null_mut();
        }
        self.stream_type = stream_type.into_raw();
    }

    #[allow(dead_code)]
    pub(crate) fn get_sample_rate_in_hz(&self) -> FtInt {
        self.sample_rate_in_hz
    }

    #[allow(dead_code)]
    pub(crate) fn set_sample_rate_in_hz(&mut self, sample_rate_in_hz: FtInt) {
        self.sample_rate_in_hz = sample_rate_in_hz;
    }

    #[allow(dead_code)]
    pub(crate) fn get_channel_config(&self) -> FtInt {
        self.channel_config
    }

    #[allow(dead_code)]
    pub(crate) fn set_channel_config(&mut self, channel_config: FtInt) {
        self.channel_config = channel_config;
    }

    #[allow(dead_code)]
    pub(crate) fn get_audio_format(&self) -> FtInt {
        self.audio_format
    }

    #[allow(dead_code)]
    pub(crate) fn set_audio_format(&mut self, audio_format: FtInt) {
        self.audio_format = audio_format;
    }
}

// for JIDL struct 'PlayerSeekParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "PlayerSeekParams")]
pub struct system_media_audio_PlayerSeekParams {
    current_time: FtInt,
}

impl PlayerSeekParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_PlayerSeekParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_current_time(&self) -> FtInt {
        self.current_time
    }

    #[allow(dead_code)]
    pub(crate) fn set_current_time(&mut self, current_time: FtInt) {
        self.current_time = current_time;
    }
}

// for JIDL struct 'interruptAction'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "InterruptAction")]
pub struct system_media_audio_interruptAction {
    interrupt_hint: FtInt,
    action_type: FtInt,
}

impl InterruptAction {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_interruptAction {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_interrupt_hint(&self) -> FtInt {
        self.interrupt_hint
    }

    #[allow(dead_code)]
    pub(crate) fn set_interrupt_hint(&mut self, interrupt_hint: FtInt) {
        self.interrupt_hint = interrupt_hint;
    }

    #[allow(dead_code)]
    pub(crate) fn get_action_type(&self) -> FtInt {
        self.action_type
    }

    #[allow(dead_code)]
    pub(crate) fn set_action_type(&mut self, action_type: FtInt) {
        self.action_type = action_type;
    }
}

// for JIDL struct 'RecorderStartParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "RecorderStartParams")]
pub struct system_media_audio_RecorderStartParams {
    uri: FtString,
}

impl RecorderStartParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_RecorderStartParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_uri(&self) -> Option<FeatureString> {
        unsafe { FeatureString::from_raw(self.uri) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_uri(&mut self, uri: FeatureString) {
        if !self.uri.is_null() {
            unsafe {
                FeatureFreeValue(self.uri as *mut c_void);
            }
            self.uri = ptr::null_mut();
        }
        self.uri = uri.into_raw();
    }
}

// for JIDL struct 'CreateRecorderParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "CreateRecorderParams")]
pub struct system_media_audio_CreateRecorderParams {
    output_format: FtString,
    sample_rate_in_hz: FtInt,
    number_of_channels: FtInt,
    audio_format: FtInt,
}

impl CreateRecorderParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_CreateRecorderParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_output_format(&self) -> Option<FeatureString> {
        unsafe { FeatureString::from_raw(self.output_format) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_output_format(&mut self, output_format: FeatureString) {
        if !self.output_format.is_null() {
            unsafe {
                FeatureFreeValue(self.output_format as *mut c_void);
            }
            self.output_format = ptr::null_mut();
        }
        self.output_format = output_format.into_raw();
    }

    #[allow(dead_code)]
    pub(crate) fn get_sample_rate_in_hz(&self) -> FtInt {
        self.sample_rate_in_hz
    }

    #[allow(dead_code)]
    pub(crate) fn set_sample_rate_in_hz(&mut self, sample_rate_in_hz: FtInt) {
        self.sample_rate_in_hz = sample_rate_in_hz;
    }

    #[allow(dead_code)]
    pub(crate) fn get_number_of_channels(&self) -> FtInt {
        self.number_of_channels
    }

    #[allow(dead_code)]
    pub(crate) fn set_number_of_channels(&mut self, number_of_channels: FtInt) {
        self.number_of_channels = number_of_channels;
    }

    #[allow(dead_code)]
    pub(crate) fn get_audio_format(&self) -> FtInt {
        self.audio_format
    }

    #[allow(dead_code)]
    pub(crate) fn set_audio_format(&mut self, audio_format: FtInt) {
        self.audio_format = audio_format;
    }
}

// for JIDL struct 'TrackWriteParams'
#[repr(C)]
#[derive(Clone)]
#[feature_struct(wrapper_struct = "TrackWriteParams")]
pub struct system_media_audio_TrackWriteParams {
    buffer: FtArrayBuffer,
}

impl TrackWriteParams {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            inner: FeaturePtr::new(),
        }
    }

    #[allow(dead_code)]
    pub fn as_ptr(&self) -> *mut system_media_audio_TrackWriteParams {
        self.inner.as_ptr()
    }

    // member getters and setters
    #[allow(dead_code)]
    pub(crate) fn get_buffer(&self) -> Option<FeatureArrayBuffer> {
        unsafe { FeatureArrayBuffer::from_raw(self.buffer) }
    }

    #[allow(dead_code)]
    pub(crate) fn set_buffer(&mut self, buffer: FeatureArrayBuffer) {
        if !self.buffer.is_null() {
            unsafe {
                FeatureFreeValue(self.buffer as *mut c_void);
            }
            self.buffer = ptr::null_mut();
        }
        self.buffer = buffer.into_raw();
    }
}


// for JIDL event 'onreaddata'
pub(crate) struct AudioRecorderOnreaddataEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnreaddataEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, buffer: FeatureArrayBuffer) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onreaddata(ev.handle(), buffer.as_ptr());
            });
        }
    }
}

// for JIDL event 'onerror'
pub(crate) struct AudioRecorderOnerrorEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnerrorEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, data: FeatureString, code: FtInt) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onerror(ev.handle(), data.as_ptr(), code);
            });
        }
    }
}

// for JIDL event 'onstart'
pub(crate) struct AudioRecorderOnstartEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnstartEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onstart(ev.handle());
            });
        }
    }
}

// for JIDL event 'onpause'
pub(crate) struct AudioRecorderOnpauseEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnpauseEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onpause(ev.handle());
            });
        }
    }
}

// for JIDL event 'onresume'
pub(crate) struct AudioRecorderOnresumeEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnresumeEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onresume(ev.handle());
            });
        }
    }
}

// for JIDL event 'onstop'
pub(crate) struct AudioRecorderOnstopEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOnstopEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_onstop(ev.handle());
            });
        }
    }
}

// for JIDL event 'oninterrupt'
pub(crate) struct AudioRecorderOninterruptEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioRecorderOninterruptEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, action: InterruptAction) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        let action = action.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioRecorder_emit_oninterrupt(ev.handle(), action.as_ptr());
            });
        }
    }
}


// for JIDL event 'onplay'
pub(crate) struct AudioTrackOnplayEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioTrackOnplayEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioTrack_emit_onplay(ev.handle());
            });
        }
    }
}

// for JIDL event 'onpause'
pub(crate) struct AudioTrackOnpauseEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioTrackOnpauseEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioTrack_emit_onpause(ev.handle());
            });
        }
    }
}

// for JIDL event 'onstop'
pub(crate) struct AudioTrackOnstopEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioTrackOnstopEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioTrack_emit_onstop(ev.handle());
            });
        }
    }
}

// for JIDL event 'onerror'
pub(crate) struct AudioTrackOnerrorEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioTrackOnerrorEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, data: FeatureString, code: FtInt) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioTrack_emit_onerror(ev.handle(), data.as_ptr(), code);
            });
        }
    }
}

// for JIDL event 'oninterrupt'
pub(crate) struct AudioTrackOninterruptEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioTrackOninterruptEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, action: InterruptAction) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        let action = action.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioTrack_emit_oninterrupt(ev.handle(), action.as_ptr());
            });
        }
    }
}


// for JIDL event 'onplay'
pub(crate) struct AudioPlayerOnplayEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnplayEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onplay(ev.handle());
            });
        }
    }
}

// for JIDL event 'onpause'
pub(crate) struct AudioPlayerOnpauseEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnpauseEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onpause(ev.handle());
            });
        }
    }
}

// for JIDL event 'onstop'
pub(crate) struct AudioPlayerOnstopEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnstopEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onstop(ev.handle());
            });
        }
    }
}

// for JIDL event 'onended'
pub(crate) struct AudioPlayerOnendedEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnendedEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onended(ev.handle());
            });
        }
    }
}

// for JIDL event 'onerror'
pub(crate) struct AudioPlayerOnerrorEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnerrorEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, data: FeatureString, code: FtInt) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onerror(ev.handle(), data.as_ptr(), code);
            });
        }
    }
}

// for JIDL event 'ontimeupdate'
pub(crate) struct AudioPlayerOntimeupdateEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOntimeupdateEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_ontimeupdate(ev.handle());
            });
        }
    }
}

// for JIDL event 'ondurationchange'
pub(crate) struct AudioPlayerOndurationchangeEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOndurationchangeEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_ondurationchange(ev.handle());
            });
        }
    }
}

// for JIDL event 'onloadeddata'
pub(crate) struct AudioPlayerOnloadeddataEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOnloadeddataEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_onloadeddata(ev.handle());
            });
        }
    }
}

// for JIDL event 'oninterrupt'
pub(crate) struct AudioPlayerOninterruptEvent {
    ev: Arc<FeatureEvent>,
}

impl AudioPlayerOninterruptEvent {
    #[allow(dead_code)]
    pub(crate) fn new(id: FtEventId, instance: FeatureInstance) -> Self {
        Self {
            ev: Arc::new(FeatureEvent::new(id, instance)),
        }
    }

    #[allow(dead_code)]
    pub fn emit(&self, action: InterruptAction) {
        // must clone the Arc<FeatureEvent> and move it to the closure
        // to prevent the FeatureEvent from being dropped before the closure is called.
        let ev = self.ev.clone();
        let action = action.clone();
        unsafe {
            self.ev.post(move || {
                system_media_audio_AudioPlayer_emit_oninterrupt(ev.handle(), action.as_ptr());
            });
        }
    }
}


// feature trait

pub(crate) trait SystemMediaAudio: FeatureInstanceTrait {

    fn create_audio_player(&mut self, params: Option<CreatePlayerParams>) -> Option<FeatureInstance>;
    fn create_audio_track(&mut self, params: Option<CreateTrackParams>) -> Option<FeatureInstance>;
    fn create_audio_recorder(&mut self, params: Option<CreateRecorderParams>) -> Option<FeatureInstance>;
}


// interface traits
#[async_trait]
pub(crate) trait AudioRecorder: FeatureInstanceTrait + Send + Sync {
    async fn start(&mut self, params: Option<RecorderStartParams>) -> Result<FeatureString, PromiseError>;
    fn pause(&mut self) -> ();
    fn resume(&mut self) -> ();
    fn stop(&mut self) -> ();
    fn release(&mut self) -> ();
}

#[async_trait]
pub(crate) trait AudioTrack: FeatureInstanceTrait + Send + Sync {
    fn get_state(&mut self) -> Option<FeatureString>;
    fn set_state(&mut self, state: Option<FeatureString>);
    fn play(&mut self) -> ();
    async fn write(&mut self, params: Option<TrackWriteParams>) -> Result<FtInt64, PromiseError>;
    fn pause(&mut self) -> ();
    fn stop(&mut self) -> ();
    fn release(&mut self) -> ();
}

#[async_trait]
pub(crate) trait AudioPlayer: FeatureInstanceTrait + Send + Sync {
    fn get_src(&mut self) -> Option<FeatureString>;
    fn set_src(&mut self, src: Option<FeatureString>);
    fn get_duration(&mut self) -> FtDouble;
    fn get_state(&mut self) -> Option<FeatureString>;
    fn set_state(&mut self, state: Option<FeatureString>);
    fn get_current_time(&mut self) -> FtInt64;
    fn set_current_time(&mut self, current_time: FtInt64);
    fn get_playcount(&mut self) -> FtInt;
    fn set_playcount(&mut self, playcount: FtInt);
    fn play(&mut self) -> ();
    fn pause(&mut self) -> ();
    fn stop(&mut self) -> ();
    fn release(&mut self) -> ();
    async fn seek(&mut self, params: Option<PlayerSeekParams>) -> Result<(), PromiseError>;
}


// rust functions exported to c side
// feature lifecycle functions
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onRegister(feature_name: FtString) {
    let name = unsafe { CStr::from_ptr(feature_name) };
    let fname = FeatureString::new(name.to_str().unwrap_or(""));
    system_media_audio_on_register(&fname);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onCreate(ctx: FeatureRuntimeContextHandle, handle: FeatureProtoHandle,) {
    let proto = FeaturePrototype::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    let boxed = Box::new(SystemMediaAudioPrototype::new(proto.clone()));
    proto.attach(boxed);
    system_media_audio_on_create(ctx, proto);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onRequired(ctx: FeatureRuntimeContextHandle, handle: FeatureInstanceHandle,) {
    let instance = FeatureInstance::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    let boxed = Box::new(SystemMediaAudioImpl::new(instance.clone())) as Box<dyn SystemMediaAudio>;
    instance.attach(boxed);
    system_media_audio_on_required(ctx, instance);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onDetached(ctx: FeatureRuntimeContextHandle, handle: FeatureInstanceHandle,) {
    let instance = FeatureInstance::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    system_media_audio_on_detached(ctx, instance.clone());
    let _: Option<Box<dyn SystemMediaAudio>> = instance.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onDestroy(ctx: FeatureRuntimeContextHandle, handle: FeatureProtoHandle,) {
    let proto = FeaturePrototype::new(handle);
    let ctx = FeatureRuntimeContext::new(ctx);
    system_media_audio_on_destroy(ctx, proto.clone());
    let _: Option<Box<SystemMediaAudioPrototype>> = proto.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_onUnregister(feature_name: FtString) {
    let name = unsafe { CStr::from_ptr(feature_name) };
    let fname = FeatureString::new(name.to_str().unwrap_or(""));
    system_media_audio_on_unregister(&fname);
}

// feature member functions

// for JIDL method 'createAudioPlayer'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_wrap_createAudioPlayer(handle: FeatureInstanceHandle,
    _adata: AppendData, params: *mut system_media_audio_CreatePlayerParams) -> FeatureInterfaceHandle {
    let system_media_audio = unsafe {
        feature_glue::get_instance_data::<dyn SystemMediaAudio>(handle)
            .expect("Failed to get impl for 'SystemMediaAudio' trait")
    };
    let system_media_audio = unsafe {  &mut *system_media_audio };

    let params = unsafe { CreatePlayerParams::from_raw(params) };
    let ret = system_media_audio.create_audio_player(params,);
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

// vtable functions for interface target 'native_player'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_finalize(handle: FeatureInterfaceHandle) {
    let instance = FeatureInstance::new(handle);
    let _: Option<Box<dyn AudioPlayer>> = instance.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_get_src(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtString {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let ret = native_player.get_src();
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_set_src(
        handle: FeatureInstanceHandle, _adata: AppendData, src: FtString) {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let src = unsafe { FeatureString::from_raw(src) };
    native_player.set_src(src);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_get_duration(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtDouble {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let ret = native_player.get_duration();
    ret
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_get_state(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtString {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let ret = native_player.get_state();
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_set_state(
        handle: FeatureInstanceHandle, _adata: AppendData, state: FtString) {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let state = unsafe { FeatureString::from_raw(state) };
    native_player.set_state(state);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_get_currentTime(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtInt64 {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let ret = native_player.get_current_time();
    ret
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_set_currentTime(
        handle: FeatureInstanceHandle, _adata: AppendData, current_time: FtInt64) {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.set_current_time(current_time);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_get_playcount(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtInt {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let ret = native_player.get_playcount();
    ret
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_set_playcount(
        handle: FeatureInstanceHandle, _adata: AppendData, playcount: FtInt) {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.set_playcount(playcount);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_play(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.play();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_pause(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.pause();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_stop(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.stop();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_release(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    native_player.release();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioPlayer_interface_native_player_seek(
        handle: FeatureInterfaceHandle, _adata: AppendData, promise_id: FtPromiseId, params: *mut system_media_audio_PlayerSeekParams
) -> () {
    let native_player = unsafe {
        feature_glue::get_instance_data::<dyn AudioPlayer>(handle)
            .expect("Failed to get impl for 'AudioPlayer' trait")
    };
    let native_player = unsafe {  &mut *native_player };
    let params = unsafe { PlayerSeekParams::from_raw(params) };
    let promise = unsafe { FeaturePromise::<FtVoidPromise>::new(promise_id, handle) };

    runtime::spawn(async move {
        match native_player.seek(params,).await {
            Ok(v) => promise.resolve(v),
            Err(e) => promise.reject(e),
        }
    });
}

// for JIDL method 'createAudioTrack'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_wrap_createAudioTrack(handle: FeatureInstanceHandle,
    _adata: AppendData, params: *mut system_media_audio_CreateTrackParams) -> FeatureInterfaceHandle {
    let system_media_audio = unsafe {
        feature_glue::get_instance_data::<dyn SystemMediaAudio>(handle)
            .expect("Failed to get impl for 'SystemMediaAudio' trait")
    };
    let system_media_audio = unsafe {  &mut *system_media_audio };
    let params = unsafe { CreateTrackParams::from_raw(params) };
    let ret = system_media_audio.create_audio_track(params,);
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

// vtable functions for interface target 'native_track'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_finalize(handle: FeatureInterfaceHandle) {
    let instance = FeatureInstance::new(handle);
    let _: Option<Box<dyn AudioTrack>> = instance.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_get_state(
        handle: FeatureInstanceHandle, _adata: AppendData) -> FtString {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    let ret = native_track.get_state();
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_set_state(
        handle: FeatureInstanceHandle, _adata: AppendData, state: FtString) {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    let state = unsafe { FeatureString::from_raw(state) };
    native_track.set_state(state);
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_play(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    native_track.play();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_write(
        handle: FeatureInterfaceHandle, _adata: AppendData, promise_id: FtPromiseId, params: *mut system_media_audio_TrackWriteParams
) -> () {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    let params = unsafe { TrackWriteParams::from_raw(params) };
    let promise = unsafe { FeaturePromise::<FtInt64Promise>::new(promise_id, handle) };

    runtime::spawn(async move {
        match native_track.write(params,).await {
            Ok(v) => promise.resolve(v),
            Err(e) => promise.reject(e),
        }
    });
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_pause(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    native_track.pause();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_stop(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    native_track.stop();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioTrack_interface_native_track_release(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_track = unsafe {
        feature_glue::get_instance_data::<dyn AudioTrack>(handle)
            .expect("Failed to get impl for 'AudioTrack' trait")
    };
    let native_track = unsafe {  &mut *native_track };
    native_track.release();
}

// for JIDL method 'createAudioRecorder'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_wrap_createAudioRecorder(handle: FeatureInstanceHandle,
    _adata: AppendData, params: *mut system_media_audio_CreateRecorderParams) -> FeatureInterfaceHandle {
    let system_media_audio = unsafe {
        feature_glue::get_instance_data::<dyn SystemMediaAudio>(handle)
            .expect("Failed to get impl for 'SystemMediaAudio' trait")
    };
    let system_media_audio = unsafe {  &mut *system_media_audio };
    let params = unsafe { CreateRecorderParams::from_raw(params) };
    let ret = system_media_audio.create_audio_recorder(params,);
    if let Some(wrapper) = ret {
        wrapper.into_raw()
    } else {
        ptr::null_mut()
    }
}

// vtable functions for interface target 'native_recorder'
#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_finalize(handle: FeatureInterfaceHandle) {
    let instance = FeatureInstance::new(handle);
    let _: Option<Box<dyn AudioRecorder>> = instance.detach();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_start(
        handle: FeatureInterfaceHandle, _adata: AppendData, promise_id: FtPromiseId, params: *mut system_media_audio_RecorderStartParams
) -> () {
    let native_recorder = unsafe {
        feature_glue::get_instance_data::<dyn AudioRecorder>(handle)
            .expect("Failed to get impl for 'AudioRecorder' trait")
    };
    let native_recorder = unsafe {  &mut *native_recorder };
    let params = unsafe { RecorderStartParams::from_raw(params) };
    let promise = unsafe { FeaturePromise::<FtStringPromise>::new(promise_id, handle) };

    runtime::spawn(async move {
        match native_recorder.start(params).await {
            Ok(v) => promise.resolve(v),
            Err(e) => promise.reject(e),
        }
    });
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_pause(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_recorder = unsafe {
        feature_glue::get_instance_data::<dyn AudioRecorder>(handle)
            .expect("Failed to get impl for 'AudioRecorder' trait")
    };
    let native_recorder = unsafe {  &mut *native_recorder };
    native_recorder.pause();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_resume(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_recorder = unsafe {
        feature_glue::get_instance_data::<dyn AudioRecorder>(handle)
            .expect("Failed to get impl for 'AudioRecorder' trait")
    };
    let native_recorder = unsafe {  &mut *native_recorder };
    native_recorder.resume();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_stop(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_recorder = unsafe {
        feature_glue::get_instance_data::<dyn AudioRecorder>(handle)
            .expect("Failed to get impl for 'AudioRecorder' trait")
    };
    let native_recorder = unsafe {  &mut *native_recorder };
    native_recorder.stop();
}

#[no_mangle]
pub(crate) extern "C" fn system_media_audio_AudioRecorder_interface_native_recorder_release(
        handle: FeatureInterfaceHandle, _adata: AppendData
) -> () {
    let native_recorder = unsafe {
        feature_glue::get_instance_data::<dyn AudioRecorder>(handle)
            .expect("Failed to get impl for 'AudioRecorder' trait")
    };
    let native_recorder = unsafe {  &mut *native_recorder };
    native_recorder.release();
}

/* clang-format on */