cargo-features = ["path-bases"]

[package]
name = "simple"
version.workspace = true
edition.workspace = true

[lib]
name = "simple"

[dependencies]
libc = { workspace = true }
feature_macros = { workspace = true }
feature_frm = { workspace = true }
async-trait = { workspace = true }
vdk = { workspace = true }
