/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_ARRAYBUFFER_TEST_H_
#define JSON_AST_GEN_MODULE_ARRAYBUFFER_TEST_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void arraybuffer_test_onRegister(const char* feature_name);
void arraybuffer_test_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void arraybuffer_test_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void arraybuffer_test_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void arraybuffer_test_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void arraybuffer_test_onUnregister(const char* feature_name);

// Struct defines

// Function wrappers to be implemented
void arraybuffer_test_wrap_setArraybuffer(FeatureInstanceHandle feature, AppendData append_data, FtInt a, FtAny buffer);
FtAny arraybuffer_test_wrap_getArraybuffer(FeatureInstanceHandle feature, AppendData append_data);
FtAny arraybuffer_test_wrap_getTypedArraybuffer(FeatureInstanceHandle feature, AppendData append_data, FtInt type);
void arraybuffer_test_wrap_print(FeatureInstanceHandle feature, AppendData append_data, FtVariParams vari_params);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_ARRAYBUFFER_TEST_H_
/* clang-format on */
