/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "cipher.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_main_exports.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL callback 'success_cb_obj_bool_opt' ******/
static const FeatureType system_cipher_success_cb_obj_bool_opt_parameters[] = {
    FT_ANY_REF,
    FT_PARAM_END
};

static const CallbackType system_cipher_success_cb_obj_bool_opt_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_cipher_success_cb_obj_bool_opt_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'success_cb_obj_str_opt' ******/
static const FeatureType system_cipher_success_cb_obj_str_opt_parameters[] = {
    FT_ANY_REF,
    FT_PARAM_END
};

static const CallbackType system_cipher_success_cb_obj_str_opt_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_cipher_success_cb_obj_str_opt_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'fail_cb' ******/
static const FeatureType system_cipher_fail_cb_parameters[] = {
    FT_ANY_REF,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_cipher_fail_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_cipher_fail_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_cipher_complete_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_cipher_complete_cb_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_cipher_complete_cb_parameters,
    .return_type = FT_VOID
};


static OptionalType system_cipher_RSAParam_member_hashType_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "SHA256"
};

/****** for JIDL struct 'RSAParam' ******/
static ObjectMember system_cipher_RSAParam_struct_members[] = {
    { "action", FT_STRING, offsetof(system_cipher_RSAParam, _action), sizeof(FtString) },
    { "text", FT_STRING, offsetof(system_cipher_RSAParam, _text), sizeof(FtString) },
    { "key", FT_STRING, offsetof(system_cipher_RSAParam, _key), sizeof(FtString) },
    { "hashType", FT_MK_OPTIONAL(&system_cipher_RSAParam_member_hashType_opt_type), offsetof(system_cipher_RSAParam, _hashType), sizeof(FtString) },
    { "success", FT_MK_COMPLEX_REF(&system_cipher_success_cb_obj_str_opt_callback_type), offsetof(system_cipher_RSAParam, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX_REF(&system_cipher_fail_cb_callback_type), offsetof(system_cipher_RSAParam, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX_REF(&system_cipher_complete_cb_callback_type), offsetof(system_cipher_RSAParam, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_cipher_RSAParam_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_cipher_RSAParam) },
    .members = system_cipher_RSAParam_struct_members
};

system_cipher_RSAParam* system_cipherMallocRSAParam () {
    return (system_cipher_RSAParam*)FeatureMalloc(
        sizeof(system_cipher_RSAParam), FT_MK_COMPLEX_REF(&system_cipher_RSAParam_struct_type));
}


/****** for JIDL function 'rsa' ******/
static const FeatureType system_cipher_rsa_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_RSAParam_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_rsa_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_rsa) },
    .parameters = system_cipher_rsa_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'sign' ******/
static const FeatureType system_cipher_sign_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_RSAParam_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_sign_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_sign) },
    .parameters = system_cipher_sign_parameters,
    .return_type = FT_VOID,
};


static OptionalType system_cipher_RSAVerifyParam_member_hashType_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "SHA256"
};

static OptionalType system_cipher_RSAVerifyParam_member_signature_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = ""
};

/****** for JIDL struct 'RSAVerifyParam' ******/
static ObjectMember system_cipher_RSAVerifyParam_struct_members[] = {
    { "text", FT_STRING, offsetof(system_cipher_RSAVerifyParam, _text), sizeof(FtString) },
    { "key", FT_STRING, offsetof(system_cipher_RSAVerifyParam, _key), sizeof(FtString) },
    { "hashType", FT_MK_OPTIONAL(&system_cipher_RSAVerifyParam_member_hashType_opt_type), offsetof(system_cipher_RSAVerifyParam, _hashType), sizeof(FtString) },
    { "signature", FT_MK_OPTIONAL(&system_cipher_RSAVerifyParam_member_signature_opt_type), offsetof(system_cipher_RSAVerifyParam, _signature), sizeof(FtString) },
    { "success", FT_MK_COMPLEX_REF(&system_cipher_success_cb_obj_bool_opt_callback_type), offsetof(system_cipher_RSAVerifyParam, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX_REF(&system_cipher_fail_cb_callback_type), offsetof(system_cipher_RSAVerifyParam, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX_REF(&system_cipher_complete_cb_callback_type), offsetof(system_cipher_RSAVerifyParam, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_cipher_RSAVerifyParam_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_cipher_RSAVerifyParam) },
    .members = system_cipher_RSAVerifyParam_struct_members
};

system_cipher_RSAVerifyParam* system_cipherMallocRSAVerifyParam () {
    return (system_cipher_RSAVerifyParam*)FeatureMalloc(
        sizeof(system_cipher_RSAVerifyParam), FT_MK_COMPLEX_REF(&system_cipher_RSAVerifyParam_struct_type));
}


/****** for JIDL function 'verify' ******/
static const FeatureType system_cipher_verify_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_RSAVerifyParam_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_verify_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_verify) },
    .parameters = system_cipher_verify_parameters,
    .return_type = FT_VOID,
};


static OptionalType system_cipher_DigestParam_member_hashType_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "SHA256"
};

/****** for JIDL struct 'DigestParam' ******/
static ObjectMember system_cipher_DigestParam_struct_members[] = {
    { "hashType", FT_MK_OPTIONAL(&system_cipher_DigestParam_member_hashType_opt_type), offsetof(system_cipher_DigestParam, _hashType), sizeof(FtString) },
    { "text", FT_STRING, offsetof(system_cipher_DigestParam, _text), sizeof(FtString) },
    { "success", FT_MK_COMPLEX_REF(&system_cipher_success_cb_obj_str_opt_callback_type), offsetof(system_cipher_DigestParam, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX_REF(&system_cipher_fail_cb_callback_type), offsetof(system_cipher_DigestParam, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX_REF(&system_cipher_complete_cb_callback_type), offsetof(system_cipher_DigestParam, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_cipher_DigestParam_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_cipher_DigestParam) },
    .members = system_cipher_DigestParam_struct_members
};

system_cipher_DigestParam* system_cipherMallocDigestParam () {
    return (system_cipher_DigestParam*)FeatureMalloc(
        sizeof(system_cipher_DigestParam), FT_MK_COMPLEX_REF(&system_cipher_DigestParam_struct_type));
}


/****** for JIDL function 'digest' ******/
static const FeatureType system_cipher_digest_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_DigestParam_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_digest_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_digest) },
    .parameters = system_cipher_digest_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'Md5Param' ******/
static ObjectMember system_cipher_Md5Param_struct_members[] = {
    { "text", FT_STRING, offsetof(system_cipher_Md5Param, _text), sizeof(FtString) },
    { "success", FT_MK_COMPLEX_REF(&system_cipher_success_cb_obj_str_opt_callback_type), offsetof(system_cipher_Md5Param, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX_REF(&system_cipher_fail_cb_callback_type), offsetof(system_cipher_Md5Param, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX_REF(&system_cipher_complete_cb_callback_type), offsetof(system_cipher_Md5Param, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_cipher_Md5Param_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_cipher_Md5Param) },
    .members = system_cipher_Md5Param_struct_members
};

system_cipher_Md5Param* system_cipherMallocMd5Param () {
    return (system_cipher_Md5Param*)FeatureMalloc(
        sizeof(system_cipher_Md5Param), FT_MK_COMPLEX_REF(&system_cipher_Md5Param_struct_type));
}


/****** for JIDL function 'md5' ******/
static const FeatureType system_cipher_md5_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_Md5Param_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_md5_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_md5) },
    .parameters = system_cipher_md5_parameters,
    .return_type = FT_VOID,
};


static OptionalType system_cipher_AESParam_member_iv_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = ""
};

static OptionalType system_cipher_AESParam_member_ivOffset_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 0
};

static OptionalType system_cipher_AESParam_member_ivLen_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 16
};

/****** for JIDL struct 'AESParam' ******/
static ObjectMember system_cipher_AESParam_struct_members[] = {
    { "action", FT_STRING, offsetof(system_cipher_AESParam, _action), sizeof(FtString) },
    { "text", FT_STRING, offsetof(system_cipher_AESParam, _text), sizeof(FtString) },
    { "key", FT_STRING, offsetof(system_cipher_AESParam, _key), sizeof(FtString) },
    { "iv", FT_MK_OPTIONAL(&system_cipher_AESParam_member_iv_opt_type), offsetof(system_cipher_AESParam, _iv), sizeof(FtString) },
    { "ivOffset", FT_MK_OPTIONAL(&system_cipher_AESParam_member_ivOffset_opt_type), offsetof(system_cipher_AESParam, _ivOffset), sizeof(FtInt) },
    { "ivLen", FT_MK_OPTIONAL(&system_cipher_AESParam_member_ivLen_opt_type), offsetof(system_cipher_AESParam, _ivLen), sizeof(FtInt) },
    { "success", FT_MK_COMPLEX_REF(&system_cipher_success_cb_obj_str_opt_callback_type), offsetof(system_cipher_AESParam, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX_REF(&system_cipher_fail_cb_callback_type), offsetof(system_cipher_AESParam, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX_REF(&system_cipher_complete_cb_callback_type), offsetof(system_cipher_AESParam, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_cipher_AESParam_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_cipher_AESParam) },
    .members = system_cipher_AESParam_struct_members
};

system_cipher_AESParam* system_cipherMallocAESParam () {
    return (system_cipher_AESParam*)FeatureMalloc(
        sizeof(system_cipher_AESParam), FT_MK_COMPLEX_REF(&system_cipher_AESParam_struct_type));
}


/****** for JIDL function 'aes' ******/
static const FeatureType system_cipher_aes_parameters[] = {
    FT_MK_COMPLEX(&system_cipher_AESParam_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_cipher_aes_member_method = {
    .func = { .callback = FFI_FN(system_cipher_wrap_aes) },
    .parameters = system_cipher_aes_parameters,
    .return_type = FT_VOID,
};


// members
static const Member system_cipher_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "rsa",
        .method = &system_cipher_rsa_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sign",
        .method = &system_cipher_sign_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "verify",
        .method = &system_cipher_verify_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "digest",
        .method = &system_cipher_digest_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "md5",
        .method = &system_cipher_md5_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "aes",
        .method = &system_cipher_aes_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_cipher_callbacks {
    system_cipher_onRegister,
    system_cipher_onCreate,
    system_cipher_onRequired,
    system_cipher_onDetached,
    system_cipher_onDestroy,
    system_cipher_onUnregister
};

static const FeatureDescription system_cipher_desc = {
    .version = 1,
    .name = "system.cipher",
    .description = "system.cipher",
    { .dynamic = false },
    .native_callbacks = &system_cipher_callbacks,
    .member_count = countof(system_cipher_members),
    .members = system_cipher_members,
};

QAPPFEATURE_INIT(system_cipher)
{
    return FeatureRegisterFeature(handle, &system_cipher_desc);
}
/* clang-format on */
