/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "crypto.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'HashDigestParam' ******/
extern const ObjectMapType system_crypto_HashDigestParam_struct_type;

static OptionalType system_crypto_HashDigestParam_member_algo_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "SHA256"
};

static ObjectMember system_crypto_HashDigestParam_struct_members[] = {
    { "data", FT_ANY_REF, offsetof(system_crypto_HashDigestParam, data), sizeof(FtAny) },
    { "uri", FT_STRING, offsetof(system_crypto_HashDigestParam, uri), sizeof(FtString) },
    { "algo", FT_MK_OPTIONAL(&system_crypto_HashDigestParam_member_algo_opt_type), offsetof(system_crypto_HashDigestParam, algo), sizeof(FtString) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_HashDigestParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_HashDigestParam) },
    .members = system_crypto_HashDigestParam_struct_members
};

system_crypto_HashDigestParam* system_cryptoMallocHashDigestParam () {
    return (system_crypto_HashDigestParam*)FeatureMalloc(
        sizeof(system_crypto_HashDigestParam), FT_MK_COMPLEX(&system_crypto_HashDigestParam_struct_type));
}


/****** for JIDL function 'hashDigest' ******/
static const FeatureType system_crypto_hashDigest_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_HashDigestParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_hashDigest_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    *((FtString*)ret) = system_crypto_wrap_hashDigest(handle, adata
        , *(system_crypto_HashDigestParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_hashDigest_member_method = {
    .func_stub = system_crypto_hashDigest_stub,
    .parameters = system_crypto_hashDigest_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL callback 'success_cb_bool_opt' ******/
static const FeatureType system_crypto_success_cb_bool_opt_parameters[] = {
    FT_BOOLEAN,
    FT_PARAM_END
};

static const CallbackType system_crypto_success_cb_bool_opt_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_crypto_success_cb_bool_opt_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'success_cb_obj_str_opt' ******/
static const FeatureType system_crypto_success_cb_obj_str_opt_parameters[] = {
    FT_ANY_REF,
    FT_PARAM_END
};

static const CallbackType system_crypto_success_cb_obj_str_opt_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_crypto_success_cb_obj_str_opt_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'success_cb_obj_str_u8a_opt' ******/
static const FeatureType system_crypto_success_cb_obj_str_u8a_opt_parameters[] = {
    FT_ANY_REF,
    FT_PARAM_END
};

static const CallbackType system_crypto_success_cb_obj_str_u8a_opt_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_crypto_success_cb_obj_str_u8a_opt_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'fail_cb' ******/
static const FeatureType system_crypto_fail_cb_parameters[] = {
    FT_ANY_REF,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_crypto_fail_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_crypto_fail_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_crypto_complete_cb_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_crypto_complete_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_crypto_complete_cb_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'HmacDigestParam' ******/
extern const ObjectMapType system_crypto_HmacDigestParam_struct_type;

static OptionalType system_crypto_HmacDigestParam_member_algo_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "SHA256"
};

static ObjectMember system_crypto_HmacDigestParam_struct_members[] = {
    { "data", FT_STRING, offsetof(system_crypto_HmacDigestParam, data), sizeof(FtString) },
    { "algo", FT_MK_OPTIONAL(&system_crypto_HmacDigestParam_member_algo_opt_type), offsetof(system_crypto_HmacDigestParam, algo), sizeof(FtString) },
    { "key", FT_STRING, offsetof(system_crypto_HmacDigestParam, key), sizeof(FtString) },
    { "success", FT_MK_COMPLEX(&system_crypto_success_cb_obj_str_opt_callback_type), offsetof(system_crypto_HmacDigestParam, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_crypto_fail_cb_callback_type), offsetof(system_crypto_HmacDigestParam, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_crypto_complete_cb_callback_type), offsetof(system_crypto_HmacDigestParam, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_HmacDigestParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_HmacDigestParam) },
    .members = system_crypto_HmacDigestParam_struct_members
};

system_crypto_HmacDigestParam* system_cryptoMallocHmacDigestParam () {
    return (system_crypto_HmacDigestParam*)FeatureMalloc(
        sizeof(system_crypto_HmacDigestParam), FT_MK_COMPLEX(&system_crypto_HmacDigestParam_struct_type));
}


/****** for JIDL function 'hmacDigest' ******/
static const FeatureType system_crypto_hmacDigest_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_HmacDigestParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_hmacDigest_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    system_crypto_wrap_hmacDigest(handle, adata
        , *(system_crypto_HmacDigestParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_hmacDigest_member_method = {
    .func_stub = system_crypto_hmacDigest_stub,
    .parameters = system_crypto_hmacDigest_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'SignParam' ******/
extern const ObjectMapType system_crypto_SignParam_struct_type;

static OptionalType system_crypto_SignParam_member_algo_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "RSA-SHA256"
};

static ObjectMember system_crypto_SignParam_struct_members[] = {
    { "data", FT_ANY_REF, offsetof(system_crypto_SignParam, data), sizeof(FtAny) },
    { "uri", FT_STRING, offsetof(system_crypto_SignParam, uri), sizeof(FtString) },
    { "algo", FT_MK_OPTIONAL(&system_crypto_SignParam_member_algo_opt_type), offsetof(system_crypto_SignParam, algo), sizeof(FtString) },
    { "privateKey", FT_STRING, offsetof(system_crypto_SignParam, privateKey), sizeof(FtString) },
    { "success", FT_MK_COMPLEX(&system_crypto_success_cb_obj_str_u8a_opt_callback_type), offsetof(system_crypto_SignParam, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_crypto_fail_cb_callback_type), offsetof(system_crypto_SignParam, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_crypto_complete_cb_callback_type), offsetof(system_crypto_SignParam, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_SignParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_SignParam) },
    .members = system_crypto_SignParam_struct_members
};

system_crypto_SignParam* system_cryptoMallocSignParam () {
    return (system_crypto_SignParam*)FeatureMalloc(
        sizeof(system_crypto_SignParam), FT_MK_COMPLEX(&system_crypto_SignParam_struct_type));
}


/****** for JIDL function 'sign' ******/
static const FeatureType system_crypto_sign_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_SignParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_sign_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    system_crypto_wrap_sign(handle, adata
        , *(system_crypto_SignParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_sign_member_method = {
    .func_stub = system_crypto_sign_stub,
    .parameters = system_crypto_sign_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'RSAVerifyParam' ******/
extern const ObjectMapType system_crypto_RSAVerifyParam_struct_type;

static OptionalType system_crypto_RSAVerifyParam_member_algo_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "RSA-SHA256"
};

static ObjectMember system_crypto_RSAVerifyParam_struct_members[] = {
    { "data", FT_ANY_REF, offsetof(system_crypto_RSAVerifyParam, data), sizeof(FtAny) },
    { "uri", FT_STRING, offsetof(system_crypto_RSAVerifyParam, uri), sizeof(FtString) },
    { "algo", FT_MK_OPTIONAL(&system_crypto_RSAVerifyParam_member_algo_opt_type), offsetof(system_crypto_RSAVerifyParam, algo), sizeof(FtString) },
    { "signature", FT_ANY_REF, offsetof(system_crypto_RSAVerifyParam, signature), sizeof(FtAny) },
    { "publicKey", FT_STRING, offsetof(system_crypto_RSAVerifyParam, publicKey), sizeof(FtString) },
    { "success", FT_MK_COMPLEX(&system_crypto_success_cb_bool_opt_callback_type), offsetof(system_crypto_RSAVerifyParam, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_crypto_fail_cb_callback_type), offsetof(system_crypto_RSAVerifyParam, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_crypto_complete_cb_callback_type), offsetof(system_crypto_RSAVerifyParam, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_RSAVerifyParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_RSAVerifyParam) },
    .members = system_crypto_RSAVerifyParam_struct_members
};

system_crypto_RSAVerifyParam* system_cryptoMallocRSAVerifyParam () {
    return (system_crypto_RSAVerifyParam*)FeatureMalloc(
        sizeof(system_crypto_RSAVerifyParam), FT_MK_COMPLEX(&system_crypto_RSAVerifyParam_struct_type));
}


/****** for JIDL function 'verify' ******/
static const FeatureType system_crypto_verify_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_RSAVerifyParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_verify_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    system_crypto_wrap_verify(handle, adata
        , *(system_crypto_RSAVerifyParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_verify_member_method = {
    .func_stub = system_crypto_verify_stub,
    .parameters = system_crypto_verify_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'MixinCryptOption' ******/
extern const ObjectMapType system_crypto_MixinCryptOption_struct_type;

static OptionalType system_crypto_MixinCryptOption_member_ivOffset_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 0
};

static OptionalType system_crypto_MixinCryptOption_member_ivLen_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 16
};

static ObjectMember system_crypto_MixinCryptOption_struct_members[] = {
    { "transformation", FT_STRING, offsetof(system_crypto_MixinCryptOption, transformation), sizeof(FtString) },
    { "iv", FT_STRING, offsetof(system_crypto_MixinCryptOption, iv), sizeof(FtString) },
    { "ivOffset", FT_MK_OPTIONAL(&system_crypto_MixinCryptOption_member_ivOffset_opt_type), offsetof(system_crypto_MixinCryptOption, ivOffset), sizeof(FtInt) },
    { "ivLen", FT_MK_OPTIONAL(&system_crypto_MixinCryptOption_member_ivLen_opt_type), offsetof(system_crypto_MixinCryptOption, ivLen), sizeof(FtInt) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_MixinCryptOption_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_MixinCryptOption) },
    .members = system_crypto_MixinCryptOption_struct_members
};

system_crypto_MixinCryptOption* system_cryptoMallocMixinCryptOption () {
    return (system_crypto_MixinCryptOption*)FeatureMalloc(
        sizeof(system_crypto_MixinCryptOption), FT_MK_COMPLEX(&system_crypto_MixinCryptOption_struct_type));
}


/****** for JIDL struct 'CryptParam' ******/
extern const ObjectMapType system_crypto_CryptParam_struct_type;

static OptionalType system_crypto_CryptParam_member_algo_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "RSA"
};

static ObjectMember system_crypto_CryptParam_struct_members[] = {
    { "data", FT_ANY_REF, offsetof(system_crypto_CryptParam, data), sizeof(FtAny) },
    { "algo", FT_MK_OPTIONAL(&system_crypto_CryptParam_member_algo_opt_type), offsetof(system_crypto_CryptParam, algo), sizeof(FtString) },
    { "key", FT_STRING, offsetof(system_crypto_CryptParam, key), sizeof(FtString) },
    { "options", FT_MK_COMPLEX(&system_crypto_MixinCryptOption_struct_type), offsetof(system_crypto_CryptParam, options), sizeof(system_crypto_MixinCryptOption *) },
    { "success", FT_MK_COMPLEX(&system_crypto_success_cb_obj_str_u8a_opt_callback_type), offsetof(system_crypto_CryptParam, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_crypto_fail_cb_callback_type), offsetof(system_crypto_CryptParam, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_crypto_complete_cb_callback_type), offsetof(system_crypto_CryptParam, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
const ObjectMapType system_crypto_CryptParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_crypto_CryptParam) },
    .members = system_crypto_CryptParam_struct_members
};

system_crypto_CryptParam* system_cryptoMallocCryptParam () {
    return (system_crypto_CryptParam*)FeatureMalloc(
        sizeof(system_crypto_CryptParam), FT_MK_COMPLEX(&system_crypto_CryptParam_struct_type));
}


/****** for JIDL function 'encrypt' ******/
static const FeatureType system_crypto_encrypt_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_CryptParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_encrypt_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    system_crypto_wrap_encrypt(handle, adata
        , *(system_crypto_CryptParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_encrypt_member_method = {
    .func_stub = system_crypto_encrypt_stub,
    .parameters = system_crypto_encrypt_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'decrypt' ******/
static const FeatureType system_crypto_decrypt_parameters[] = {
    FT_MK_COMPLEX(&system_crypto_CryptParam_struct_type),
    FT_PARAM_END
};

static void system_crypto_decrypt_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    system_crypto_wrap_decrypt(handle, adata
        , *(system_crypto_CryptParam **)(argv[0])
    );
}

static const MemberMethod system_crypto_decrypt_member_method = {
    .func_stub = system_crypto_decrypt_stub,
    .parameters = system_crypto_decrypt_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'btoa' ******/
static const FeatureType system_crypto_btoa_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static void system_crypto_btoa_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    *((FtString*)ret) = system_crypto_wrap_btoa(handle, adata
        , *(FtString*)(argv[0])
    );
}

static const MemberMethod system_crypto_btoa_member_method = {
    .func_stub = system_crypto_btoa_stub,
    .parameters = system_crypto_btoa_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL function 'atob' ******/
static const FeatureType system_crypto_atob_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static void system_crypto_atob_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    *((FtString*)ret) = system_crypto_wrap_atob(handle, adata
        , *(FtString*)(argv[0])
    );
}

static const MemberMethod system_crypto_atob_member_method = {
    .func_stub = system_crypto_atob_stub,
    .parameters = system_crypto_atob_parameters,
    .return_type = FT_STRING,
};


// members
static const Member system_crypto_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "hashDigest",
        .method = &system_crypto_hashDigest_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "hmacDigest",
        .method = &system_crypto_hmacDigest_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "sign",
        .method = &system_crypto_sign_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "verify",
        .method = &system_crypto_verify_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "encrypt",
        .method = &system_crypto_encrypt_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "decrypt",
        .method = &system_crypto_decrypt_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "btoa",
        .method = &system_crypto_btoa_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "atob",
        .method = &system_crypto_atob_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_crypto_callbacks = {
    system_crypto_onRegister,
    system_crypto_onCreate,
    system_crypto_onRequired,
    system_crypto_onDetached,
    system_crypto_onDestroy,
    system_crypto_onUnregister
};

static const FeatureDescription system_crypto_desc = {
    .version = 1,
    .name = "system.crypto",
    .description = "system.crypto",
    .dynamic = false,
    .native_callbacks = &system_crypto_callbacks,
    .member_count = countof(system_crypto_members),
    .members = system_crypto_members,
};

QAPPFEATURE_INIT(system_crypto)
{
    return FeatureRegisterFeature(handle, &system_crypto_desc);
}
/* clang-format on */
