/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef _CRYPTO_NATIVE_H_
#define _CRYPTO_NATIVE_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern const char* crypto_err;

// no need to free the return char* because it is FeatureMalloced
char* digest(const char* type_str, uint8_t* text_str, size_t text_size, const char* key_str);

// no need to free the return char* because it is FeatureMalloced
char* digest_file(const char* type_str, const char* uri_str, const char* pkg_str);

// must free the return char* because it is malloced
char* rsa_encrypt(const char* key_str, uint8_t* buff, size_t* buff_size, bool* is_text);

// must free the return char* because it is malloced
char* rsa_decrypt(const char* key_str, uint8_t* buff, size_t* buff_size, bool* is_text);

// must free the return char* because it is malloced
char* aes_encrypt(int mode, int padding, const char* key_str, const char* iv_str, int ivOffset, int ivLen, uint8_t* buff, size_t* size, bool* is_text);

// must free the return char* because it is malloced
char* aes_decrypt(int mode, int padding, const char* key_str, const char* iv_str, int ivOffset, int ivLen, uint8_t* buff, size_t* size, bool* is_text);

// must free the return char* because it is malloced
char* rsa_sign(const char* type_str, const char* key_str, uint8_t* buff, size_t* buff_size, bool* is_text);

// must free the return char* because it is malloced
char* rsa_sign_file(const char* type_str, const char* key_str, const char* uri_str, const char* pkg_str);

bool rsa_verify(const char* type_str, const char* key_str, uint8_t* buff, size_t buff_size, uint8_t* sig_buff, size_t seg_size,  bool sig_text);

bool rsa_verify_file(const char* type_str, const char* key_str, const char* uri_str, const char* sig_str, const char* pkg_str);

// no need to free the return char* because it is FeatureMalloced
char* base64(const char* type_str, const char* text_str);

#endif // _CRYPTO_NATIVE_H_