/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_CRYPTO_H_
#define JSON_AST_GEN_MODULE_SYSTEM_CRYPTO_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_crypto_onRegister(const char* feature_name);
void system_crypto_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_crypto_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_crypto_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_crypto_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_crypto_onUnregister(const char* feature_name);

// Struct defines
typedef struct _HashDigestParam {
  FtAny data;
  FtString uri;
  FtString algo;
} system_crypto_HashDigestParam;

system_crypto_HashDigestParam* system_cryptoMallocHashDigestParam(void);

typedef struct _HmacDigestParam {
  FtString data;
  FtString algo;
  FtString key;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_crypto_HmacDigestParam;

system_crypto_HmacDigestParam* system_cryptoMallocHmacDigestParam(void);

typedef struct _SignParam {
  FtAny data;
  FtString uri;
  FtString algo;
  FtString privateKey;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_crypto_SignParam;

system_crypto_SignParam* system_cryptoMallocSignParam(void);

typedef struct _RSAVerifyParam {
  FtAny data;
  FtString uri;
  FtString algo;
  FtAny signature;
  FtString publicKey;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_crypto_RSAVerifyParam;

system_crypto_RSAVerifyParam* system_cryptoMallocRSAVerifyParam(void);

typedef struct _MixinCryptOption {
  FtString transformation;
  FtString iv;
  FtInt ivOffset;
  FtInt ivLen;
} system_crypto_MixinCryptOption;

system_crypto_MixinCryptOption* system_cryptoMallocMixinCryptOption(void);

typedef struct _CryptParam {
  FtAny data;
  FtString algo;
  FtString key;
  system_crypto_MixinCryptOption * options;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_crypto_CryptParam;

system_crypto_CryptParam* system_cryptoMallocCryptParam(void);


// Function wrappers to be implemented
FtString system_crypto_wrap_hashDigest(FeatureInstanceHandle feature, AppendData append_data, system_crypto_HashDigestParam * options);
void system_crypto_wrap_hmacDigest(FeatureInstanceHandle feature, AppendData append_data, system_crypto_HmacDigestParam * options);
void system_crypto_wrap_sign(FeatureInstanceHandle feature, AppendData append_data, system_crypto_SignParam * options);
void system_crypto_wrap_verify(FeatureInstanceHandle feature, AppendData append_data, system_crypto_RSAVerifyParam * options);
void system_crypto_wrap_encrypt(FeatureInstanceHandle feature, AppendData append_data, system_crypto_CryptParam * options);
void system_crypto_wrap_decrypt(FeatureInstanceHandle feature, AppendData append_data, system_crypto_CryptParam * options);
FtString system_crypto_wrap_btoa(FeatureInstanceHandle feature, AppendData append_data, FtString text);
FtString system_crypto_wrap_atob(FeatureInstanceHandle feature, AppendData append_data, FtString text);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_CRYPTO_H_
/* clang-format on */
