/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_CYPHER_H_
#define JSON_AST_GEN_MODULE_SYSTEM_CYPHER_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_cypher_onRegister(const char* feature_name);
void system_cypher_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_cypher_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_cypher_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_cypher_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_cypher_onUnregister(const char* feature_name);

// Struct defines
typedef struct _RSAParam {
  FtString _action;
  FtString _text;
  FtString _key;
  FtString _hashType;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_cypher_RSAParam;

system_cypher_RSAParam* system_cypherMallocRSAParam();

typedef struct _RSAVerifyParam {
  FtString _text;
  FtString _key;
  FtString _hashType;
  FtString _signature;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_cypher_RSAVerifyParam;

system_cypher_RSAVerifyParam* system_cypherMallocRSAVerifyParam();

typedef struct _DigestParam {
  FtString _hashType;
  FtString _text;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_cypher_DigestParam;

system_cypher_DigestParam* system_cypherMallocDigestParam();

typedef struct _Md5Param {
  FtString _text;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_cypher_Md5Param;

system_cypher_Md5Param* system_cypherMallocMd5Param();

typedef struct _AESParam {
  FtString _action;
  FtString _text;
  FtString _key;
  FtString _iv;
  FtInt _ivOffset;
  FtInt _ivLen;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_cypher_AESParam;

system_cypher_AESParam* system_cypherMallocAESParam();


// Function wrappers to be implemented
void system_cypher_wrap_rsa(FeatureInstanceHandle feature, AppendData append_data, system_cypher_RSAParam * opts);
void system_cypher_wrap_sign(FeatureInstanceHandle feature, AppendData append_data, system_cypher_RSAParam * opts);
void system_cypher_wrap_verify(FeatureInstanceHandle feature, AppendData append_data, system_cypher_RSAVerifyParam * opts);
void system_cypher_wrap_digest(FeatureInstanceHandle feature, AppendData append_data, system_cypher_DigestParam * opts);
void system_cypher_wrap_md5(FeatureInstanceHandle feature, AppendData append_data, system_cypher_Md5Param * opts);
void system_cypher_wrap_aes(FeatureInstanceHandle feature, AppendData append_data, system_cypher_AESParam * opts);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_CYPHER_H_
/* clang-format on */
