/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_INTERFACE_TEST_H_
#define JSON_AST_GEN_MODULE_INTERFACE_TEST_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void interface_test_onRegister(const char* feature_name);
void interface_test_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void interface_test_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void interface_test_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void interface_test_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void interface_test_onUnregister(const char* feature_name);

// Struct defines

// Function wrappers to be implemented
FeatureInterfaceHandle interface_test_wrap_createDog(FeatureInstanceHandle feature, AppendData append_data, FtInt type);
FeatureInterfaceHandle interface_test_wrap_createPigeon(FeatureInstanceHandle feature, AppendData append_data);
FeatureInterfaceHandle interface_test_wrap_createCock(FeatureInstanceHandle feature, AppendData append_data);
FeatureInterfaceHandle interface_test_wrap_createCat(FeatureInstanceHandle feature, AppendData append_data);
void interface_test_wrap_setAnimal(FeatureInstanceHandle feature, AppendData append_data, FeatureInterfaceHandle animal);
void interface_test_wrap_flyFar(FeatureInstanceHandle feature, AppendData append_data, FtPromiseId pid, FtInt distance);
void interface_test_wrap_print(FeatureInstanceHandle feature, AppendData append_data, FtVariParams vari_params);

// Interface constructors
FeatureInterfaceHandle interface_test_createDog_instance(FeatureInstanceHandle feature);
FeatureInterfaceHandle interface_test_createPigeon_instance(FeatureInstanceHandle feature);
FeatureInterfaceHandle interface_test_createCock_instance(FeatureInstanceHandle feature);

// interface vtable functions to be implemented
// vtable functions for interface constructor function 'createDog'
void interface_test_Animal_interface_dog_finalize(FeatureInterfaceHandle handle);
FtString interface_test_Animal_interface_dog_get_name(FeatureInterfaceHandle handle, AppendData append_data);
void interface_test_Animal_interface_dog_set_name(FeatureInterfaceHandle handle, AppendData append_data, FtString name);
FtInt interface_test_Animal_interface_dog_get_legCount(FeatureInterfaceHandle handle, AppendData append_data);
FtInt interface_test_Animal_interface_dog_eatFood(FeatureInterfaceHandle handle, AppendData append_data, FtArray* foods);
FtString interface_test_Animal_interface_dog_run(FeatureInterfaceHandle handle, AppendData append_data, FtInt distance, FtString destination);

// vtable functions for interface constructor function 'createPigeon'
void interface_test_Bird_interface_pigeon_finalize(FeatureInterfaceHandle handle);
FtArray* interface_test_Bird_interface_pigeon_fly(FeatureInterfaceHandle handle, AppendData append_data);
FtString interface_test_Bird_interface_pigeon_get_breed(FeatureInterfaceHandle handle, AppendData append_data);
void interface_test_Bird_interface_pigeon_set_breed(FeatureInterfaceHandle handle, AppendData append_data, FtString breed);

// vtable functions for interface constructor function 'createCock'
void interface_test_Chicken_interface_cock_finalize(FeatureInterfaceHandle handle);
FtString interface_test_Chicken_interface_cock_get_name(FeatureInterfaceHandle handle, AppendData append_data);
void interface_test_Chicken_interface_cock_set_name(FeatureInterfaceHandle handle, AppendData append_data, FtString name);
FtInt interface_test_Chicken_interface_cock_get_legCount(FeatureInterfaceHandle handle, AppendData append_data);
FtInt interface_test_Chicken_interface_cock_eatFood(FeatureInterfaceHandle handle, AppendData append_data, FtArray* foods);
FtString interface_test_Chicken_interface_cock_run(FeatureInterfaceHandle handle, AppendData append_data, FtInt distance, FtString destination);
FtArray* interface_test_Chicken_interface_cock_fly(FeatureInterfaceHandle handle, AppendData append_data);
FtString interface_test_Chicken_interface_cock_get_breed(FeatureInterfaceHandle handle, AppendData append_data);
void interface_test_Chicken_interface_cock_set_breed(FeatureInterfaceHandle handle, AppendData append_data, FtString breed);
FtInt interface_test_Chicken_interface_cock_get_weight(FeatureInterfaceHandle handle, AppendData append_data);
void interface_test_Chicken_interface_cock_set_weight(FeatureInterfaceHandle handle, AppendData append_data, FtInt weight);
void interface_test_Chicken_interface_cock_walk(FeatureInterfaceHandle handle, AppendData append_data, FtPromiseId pid);


// Property getters and setters to be implemented

// Array malloc functions
FtArray* interface_test_malloc_string_array(void);

#endif // JSON_AST_GEN_MODULE_INTERFACE_TEST_H_
/* clang-format on */
