/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "null_test.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'Chapter' ******/
extern const ObjectMapType null_test_Chapter_struct_type;

static OptionalType null_test_Chapter_member_page_count_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 10
};

static OptionalType null_test_Chapter_member_title_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "monkey born from a stone"
};

static ObjectMember null_test_Chapter_struct_members[] = {
    { "page_count", FT_MK_OPTIONAL(&null_test_Chapter_member_page_count_opt_type), offsetof(null_test_Chapter, page_count), sizeof(FtInt) },
    { "title", FT_MK_OPTIONAL(&null_test_Chapter_member_title_opt_type), offsetof(null_test_Chapter, title), sizeof(FtString) },
    { NULL },
};

// complex defination
const ObjectMapType null_test_Chapter_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(null_test_Chapter) },
    .members = null_test_Chapter_struct_members
};

null_test_Chapter* null_testMallocChapter () {
    return (null_test_Chapter*)FeatureMalloc(
        sizeof(null_test_Chapter), FT_MK_COMPLEX(&null_test_Chapter_struct_type));
}


/****** for JIDL callback 'ChapChanged' ******/
static const FeatureType null_test_ChapChanged_parameters[] = {
    FT_INT,
    FT_STRING,
    FT_PARAM_END
};

static const CallbackType null_test_ChapChanged_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = null_test_ChapChanged_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'Book' ******/
extern const ObjectMapType null_test_Book_struct_type;

static OptionalType null_test_Book_member_book_info_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_ANY_REF,
    .ptr = NULL
};

static OptionalType null_test_Book_member_page_count_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_INT,
    .ival = 500
};

static OptionalType null_test_Book_member_title_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_STRING,
    .str = "monkey king"
};

static OptionalType null_test_Book_member_first_chap_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_MK_COMPLEX(&null_test_Chapter_struct_type),
    .ptr = NULL
};

static OptionalType null_test_Book_member_chap_changed_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_MK_COMPLEX(&null_test_ChapChanged_callback_type),
    .ptr = NULL
};

static ObjectMember null_test_Book_struct_members[] = {
    { "book_info", FT_MK_OPTIONAL(&null_test_Book_member_book_info_opt_type), offsetof(null_test_Book, book_info), sizeof(FtAny) },
    { "page_count", FT_MK_OPTIONAL(&null_test_Book_member_page_count_opt_type), offsetof(null_test_Book, page_count), sizeof(FtInt) },
    { "title", FT_MK_OPTIONAL(&null_test_Book_member_title_opt_type), offsetof(null_test_Book, title), sizeof(FtString) },
    { "first_chap", FT_MK_OPTIONAL(&null_test_Book_member_first_chap_opt_type), offsetof(null_test_Book, first_chap), sizeof(null_test_Chapter *) },
    { "chap_changed", FT_MK_OPTIONAL(&null_test_Book_member_chap_changed_opt_type), offsetof(null_test_Book, chap_changed), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
const ObjectMapType null_test_Book_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(null_test_Book) },
    .members = null_test_Book_struct_members
};

null_test_Book* null_testMallocBook () {
    return (null_test_Book*)FeatureMalloc(
        sizeof(null_test_Book), FT_MK_COMPLEX(&null_test_Book_struct_type));
}


/****** for JIDL function 'setChapter' ******/
static OptionalType null_test_setChapter_param_chap_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_MK_COMPLEX(&null_test_Chapter_struct_type),
    .ptr = NULL
};

static const FeatureType null_test_setChapter_parameters[] = {
    FT_INT,
    FT_MK_OPTIONAL(&null_test_setChapter_param_chap_opt_type),
    FT_PARAM_END
};

static void null_test_setChapter_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    null_test_wrap_setChapter(handle, adata
        , *(FtInt*)(argv[0])
        , *(null_test_Chapter **)(argv[1])
    );
}

static const MemberMethod null_test_setChapter_member_method = {
    .func_stub = null_test_setChapter_stub,
    .parameters = null_test_setChapter_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'setChapChangedCb' ******/
static OptionalType null_test_setChapChangedCb_param_chap_changed_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_MK_COMPLEX(&null_test_ChapChanged_callback_type),
    .ptr = NULL
};

static const FeatureType null_test_setChapChangedCb_parameters[] = {
    FT_MK_OPTIONAL(&null_test_setChapChangedCb_param_chap_changed_opt_type),
    FT_PARAM_END
};

static void null_test_setChapChangedCb_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    null_test_wrap_setChapChangedCb(handle, adata
        , *(FtCallbackId*)(argv[0])
    );
}

static const MemberMethod null_test_setChapChangedCb_member_method = {
    .func_stub = null_test_setChapChangedCb_stub,
    .parameters = null_test_setChapChangedCb_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'setBook' ******/
static OptionalType null_test_setBook_param_book_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_MK_COMPLEX(&null_test_Book_struct_type),
    .ptr = NULL
};

static const FeatureType null_test_setBook_parameters[] = {
    FT_MK_OPTIONAL(&null_test_setBook_param_book_opt_type),
    FT_PARAM_END
};

static void null_test_setBook_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    null_test_wrap_setBook(handle, adata
        , *(null_test_Book **)(argv[0])
    );
}

static const MemberMethod null_test_setBook_member_method = {
    .func_stub = null_test_setBook_stub,
    .parameters = null_test_setBook_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'print' ******/
static const FeatureType null_test_print_parameters[] = {
    FT_PARAM_REST_END,
};

static void null_test_print_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret)
{
    null_test_wrap_print(handle, adata
        , *(FtVariParams*)(argv[0])
    );
}

static const MemberMethod null_test_print_member_method = {
    .func_stub = null_test_print_stub,
    .parameters = null_test_print_parameters,
    .return_type = FT_VOID,
};


// members
static const Member null_test_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "setChapter",
        .method = &null_test_setChapter_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setChapChangedCb",
        .method = &null_test_setChapChangedCb_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setBook",
        .method = &null_test_setBook_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "print",
        .method = &null_test_print_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks null_test_callbacks = {
    null_test_onRegister,
    null_test_onCreate,
    null_test_onRequired,
    null_test_onDetached,
    null_test_onDestroy,
    null_test_onUnregister
};

static const FeatureDescription null_test_desc = {
    .version = 1,
    .name = "null_test",
    .description = "null_test",
    .dynamic = false,
    .native_callbacks = &null_test_callbacks,
    .member_count = countof(null_test_members),
    .members = null_test_members,
};

QAPPFEATURE_INIT(null_test)
{
    return FeatureRegisterFeature(handle, &null_test_desc);
}
/* clang-format on */
