/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_NULL_TEST_H_
#define JSON_AST_GEN_MODULE_NULL_TEST_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void null_test_onRegister(const char* feature_name);
void null_test_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void null_test_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void null_test_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void null_test_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void null_test_onUnregister(const char* feature_name);

// Struct defines
typedef struct _Chapter {
  FtInt page_count;
  FtString title;
} null_test_Chapter;

null_test_Chapter* null_testMallocChapter(void);

typedef struct _Book {
  FtAny book_info;
  FtInt page_count;
  FtString title;
  null_test_Chapter * first_chap;
  FtCallbackId chap_changed;
} null_test_Book;

null_test_Book* null_testMallocBook(void);


// Function wrappers to be implemented
void null_test_wrap_setChapter(FeatureInstanceHandle feature, AppendData append_data, FtInt index, null_test_Chapter * chap);
void null_test_wrap_setChapChangedCb(FeatureInstanceHandle feature, AppendData append_data, FtCallbackId chap_changed);
void null_test_wrap_setBook(FeatureInstanceHandle feature, AppendData append_data, null_test_Book * book);
void null_test_wrap_print(FeatureInstanceHandle feature, AppendData append_data, FtVariParams vari_params);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_NULL_TEST_H_
/* clang-format on */
