/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_STRUCT_TEST_H_
#define JSON_AST_GEN_MODULE_STRUCT_TEST_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void struct_test_onRegister(const char* feature_name);
void struct_test_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void struct_test_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void struct_test_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void struct_test_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void struct_test_onUnregister(const char* feature_name);

// Struct defines
typedef struct _Chapter {
  FtInt page_count;
  FtString title;
  FtBool is_end;
} struct_test_Chapter;

struct_test_Chapter* struct_testMallocChapter(void);

typedef struct _Book {
  FtAny any_param;
  FtInt page_count;
  FtString title;
  FtArray* chap_titles;
  struct_test_Chapter * first_chap;
  FtCallbackId chap_changed;
} struct_test_Book;

struct_test_Book* struct_testMallocBook(void);


// Function wrappers to be implemented
void struct_test_wrap_foo(FeatureInstanceHandle feature, AppendData append_data, FtInt a, struct_test_Chapter * b);
struct_test_Chapter * struct_test_wrap_bar(FeatureInstanceHandle feature, AppendData append_data, FtInt a);
void struct_test_wrap_bar2(FeatureInstanceHandle feature, AppendData append_data, struct_test_Book * a);
void struct_test_wrap_print(FeatureInstanceHandle feature, AppendData append_data, FtVariParams vari_params);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented

// Array malloc functions
FtArray* struct_test_malloc_string_array(void);

#endif // JSON_AST_GEN_MODULE_STRUCT_TEST_H_
/* clang-format on */
